#!/usr/bin/env node
import fs from 'node:fs';

const args = process.argv.slice(2);
const recipePath = args[0];
const targetIndex = args.indexOf('--target');
const target = targetIndex >= 0 ? args[targetIndex + 1] : 'pine-v6';

if (!recipePath) {
  console.error('Usage: node render.mjs <recipe.json> --target pine-v6|mql5|ctrader|mql4|ctrader-python|bookmap-python|ninjatrader|quantower|sierra-acsil|prorealtime|gocharting-lipi|motivewave|vela');
  process.exit(1);
}

const recipe = JSON.parse(fs.readFileSync(recipePath, 'utf8'));
validateRecipe(recipe);

const renderers = {
  'pine-v6': renderPine,
  'mql5': renderMql5,
  'ctrader': renderCTrader,
  'mql4': renderMql4,
  'ctrader-python': renderCTraderPython,
  'bookmap-python': renderBookmapPython,
  'ninjatrader': renderNinja,
  'quantower': renderQuantower,
  'sierra-acsil': renderSierra,
  'prorealtime': renderProRealTime,
  'gocharting-lipi': renderLipi,
  'motivewave': renderMotiveWave,
  'vela': renderVela
};

if (!renderers[target]) {
  throw new Error(`Unsupported target: ${target}`);
}

process.stdout.write(renderers[target](recipe));

function validateRecipe(recipe) {
  if (recipe?.schemaVersion !== '0.1') throw new Error('schemaVersion must be 0.1');
  if (!recipe?.name || !Array.isArray(recipe?.blocks)) throw new Error('name and blocks are required');

  const ids = new Set();
  for (const block of recipe.blocks) {
    if (!/^[a-z][a-z0-9_]*$/.test(block.id || '')) throw new Error(`Invalid block id: ${block.id}`);
    if (ids.has(block.id)) throw new Error(`Duplicate block id: ${block.id}`);
    ids.add(block.id);
    if (!block.type || typeof block.params !== 'object') throw new Error(`Invalid block: ${block.id}`);
  }

  for (const block of recipe.blocks) {
    const p = block.params;
    for (const ref of referencesFor(block)) {
      if (!ids.has(ref) && !['open','high','low','close','hl2','hlc3','ohlc4'].includes(ref)) {
        throw new Error(`Block ${block.id} references missing id: ${ref}`);
      }
    }
    if (['indicator.ema','indicator.sma','indicator.rsi','indicator.atr'].includes(block.type)) {
      if (!Number.isInteger(p.length) || p.length < 1 || p.length > 10000) {
        throw new Error(`Block ${block.id} has invalid length`);
      }
    }
  }
}

function referencesFor(block) {
  const p = block.params || {};
  switch (block.type) {
    case 'signal.cross': return [p.left, p.right].filter(Boolean);
    case 'signal.threshold': return [p.left].filter(Boolean);
    case 'signal.combine': return Array.isArray(p.signals) ? p.signals : [];
    case 'visual.plot': return [p.source].filter(Boolean);
    case 'alert.condition': return [p.when].filter(Boolean);
    default: return [];
  }
}

function sourceName(v = 'close') {
  const allowed = new Set(['open','high','low','close','hl2','hlc3','ohlc4']);
  if (!allowed.has(v)) throw new Error(`Unsupported price source: ${v}`);
  return v;
}

function q(s) {
  return JSON.stringify(String(s ?? ''));
}

function safeTitle(recipe) {
  return String(recipe.name).replace(/["\r\n]/g, ' ').trim();
}

function className(recipe) {
  const c = safeTitle(recipe).replace(/[^A-Za-z0-9]+/g, ' ').trim()
    .split(/\s+/).map(x => x.charAt(0).toUpperCase() + x.slice(1)).join('');
  return (c || 'BSVCustomTool').replace(/^[0-9]/, 'BSV$&');
}

function blockMap(recipe) {
  return new Map(recipe.blocks.map(b => [b.id, b]));
}

function renderPine(recipe) {
  const lines = [];
  const map = blockMap(recipe);

  lines.push('//@version=6');
  lines.push(`indicator(${q('BSV — ' + safeTitle(recipe))}, overlay=${recipe.overlay ? 'true' : 'false'})`);
  lines.push('');
  lines.push('// Generated by BSV Trader Tool Blocks.');
  lines.push('// Structural starter only: compile and inspect on your TradingView version before relying on it.');
  lines.push('');

  for (const b of recipe.blocks) {
    const p = b.params || {};
    switch (b.type) {
      case 'indicator.ema':
        lines.push(`${b.id} = ta.ema(${sourceName(p.source)}, ${p.length})`);
        break;
      case 'indicator.sma':
        lines.push(`${b.id} = ta.sma(${sourceName(p.source)}, ${p.length})`);
        break;
      case 'indicator.rsi':
        lines.push(`${b.id} = ta.rsi(${sourceName(p.source)}, ${p.length})`);
        break;
      case 'indicator.atr':
        lines.push(`${b.id} = ta.atr(${p.length})`);
        break;
      case 'filter.session': {
        const session = String(p.session || '0000-2359');
        const tz = String(p.timezone || 'Etc/UTC');
        lines.push(`${b.id} = not na(time(timeframe.period, ${q(session)}, ${q(tz)}))`);
        break;
      }
      case 'signal.cross':
        lines.push(`${b.id} = ${p.direction === 'below' ? 'ta.crossunder' : 'ta.crossover'}(${p.left}, ${p.right})`);
        break;
      case 'signal.threshold': {
        const op = ['>','>=','<','<=','==','!='].includes(p.op) ? p.op : '>=';
        if (!Number.isFinite(Number(p.value))) throw new Error(`Invalid threshold in ${b.id}`);
        lines.push(`${b.id} = ${p.left} ${op} ${Number(p.value)}`);
        break;
      }
      case 'signal.combine': {
        const op = p.mode === 'any' ? ' or ' : ' and ';
        lines.push(`${b.id} = ${(p.signals || []).map(x => '(' + x + ')').join(op) || 'false'}`);
        break;
      }
      case 'visual.plot':
        lines.push(`plot(${p.source}, title=${q(p.title || p.source)})`);
        break;
      case 'alert.condition':
        lines.push(`alertcondition(${p.when}, title=${q(b.id)}, message=${q(p.message || b.id)})`);
        break;
      default:
        lines.push(`// TODO unsupported block ${b.type}: ${b.id}`);
    }
  }

  lines.push('');
  lines.push('// End BSV generated starter.');
  return lines.join('\n') + '\n';
}

function renderMql5(recipe) {
  const map = blockMap(recipe);
  const plots = recipe.blocks.filter(b => b.type === 'visual.plot');
  const alerts = recipe.blocks.filter(b => b.type === 'alert.condition');
  const inds = recipe.blocks.filter(b => ['indicator.ema', 'indicator.sma', 'indicator.rsi', 'indicator.atr'].includes(b.type));
  const appliedPrice = { open: 'PRICE_OPEN', high: 'PRICE_HIGH', low: 'PRICE_LOW', close: 'PRICE_CLOSE', hl2: 'PRICE_MEDIAN', hlc3: 'PRICE_TYPICAL' };
  const S = '_Symbol, _Period';
  const priceExpr = { open: `iOpen(${S}, i)`, high: `iHigh(${S}, i)`, low: `iLow(${S}, i)`, close: `iClose(${S}, i)`,
    hl2: `(iHigh(${S}, i) + iLow(${S}, i)) / 2.0`, hlc3: `(iHigh(${S}, i) + iLow(${S}, i) + iClose(${S}, i)) / 3.0`,
    ohlc4: `(iOpen(${S}, i) + iHigh(${S}, i) + iLow(${S}, i) + iClose(${S}, i)) / 4.0` };
  const val = (ref, at) => isPrice(ref) ? priceExpr[ref].replace(/, i\)/g, `, ${at})`) : (isBoolType(map.get(ref)?.type) ? `(S_${ref}(${at}) ? 1.0 : 0.0)` : `V_${ref}(${at})`);
  const bool = (ref, at) => isBoolType(map.get(ref)?.type) ? `S_${ref}(${at})` : `(${val(ref, at)} != 0.0 && ${val(ref, at)} != EMPTY_VALUE)`;
  const colors = ['clrDodgerBlue', 'clrOrange', 'clrLimeGreen', 'clrMagenta', 'clrGold', 'clrAqua'];
  const L = [];
  L.push('// ORIGINAL BSV STARTER — MT5 / MQL5 custom indicator. Compile in MetaEditor (MT5) before use.');
  L.push('// Generated by BSV Trader Tool Blocks. Not runtime tested by BSV. Not investment advice.');
  L.push(recipe.overlay ? '#property indicator_chart_window' : '#property indicator_separate_window');
  L.push(`#property indicator_buffers ${plots.length}`);
  L.push(`#property indicator_plots   ${plots.length}`);
  plots.forEach((p, k) => {
    L.push(`#property indicator_type${k + 1}   DRAW_LINE`);
    L.push(`#property indicator_color${k + 1}  ${colors[k % colors.length]}`);
    L.push(`#property indicator_label${k + 1}  ${q(String(p.params?.title || p.params?.source || p.id).replace(/[\r\n]/g, ' '))}`);
  });
  L.push('');
  for (const p of plots) L.push(`double Buf_${p.id}[];`);
  for (const b of inds) L.push(`int    h_${b.id} = INVALID_HANDLE;`, `double A_${b.id}[];`);
  for (const a of alerts) L.push(`datetime g_alert_${a.id} = 0;`);
  L.push(`#define BSV_WARMUP ${warmup(recipe)}`);
  L.push('');
  for (const b of recipe.blocks) {
    const p = b.params || {};
    switch (b.type) {
      case 'indicator.ema': case 'indicator.sma': case 'indicator.rsi': case 'indicator.atr':
        L.push(`double V_${b.id}(int i) { return A_${b.id}[i]; }`);
        break;
      case 'filter.session': {
        const ss = parseSession(p);
        L.push(`// TODO ${b.id}: session ${p.session || ''} is evaluated in broker server time; convert from ${p.timezone || 'Etc/UTC'} for your broker.`);
        L.push(`bool S_${b.id}(int i) { MqlDateTime t; TimeToStruct(iTime(${S}, i), t); int m = t.hour * 60 + t.min; return ${ss.start <= ss.end ? `m >= ${ss.start} && m < ${ss.end}` : `m >= ${ss.start} || m < ${ss.end}`}; }`);
        break;
      }
      case 'signal.cross': {
        const [gt, le] = p.direction === 'below' ? ['<', '>='] : ['>', '<='];
        L.push(`bool S_${b.id}(int i) { return ${val(p.left, 'i')} ${gt} ${val(p.right, 'i')} && ${val(p.left, 'i+1')} ${le} ${val(p.right, 'i+1')}; }`);
        break;
      }
      case 'signal.threshold':
        if (!Number.isFinite(Number(p.value))) throw new Error(`Invalid threshold in ${b.id}`);
        L.push(`bool S_${b.id}(int i) { return ${val(p.left, 'i')} ${thresholdOp(p)} ${Number(p.value)}; }`);
        break;
      case 'signal.combine':
        L.push(`bool S_${b.id}(int i) { return ${(p.signals || []).map(x => bool(x, 'i')).join(p.mode === 'any' ? ' || ' : ' && ') || 'false'}; }`);
        break;
      case 'visual.plot': case 'alert.condition':
        break;
      default:
        if (isBoolType(b.type)) L.push(`bool S_${b.id}(int i) { return false; } // TODO unsupported block ${b.type}: ${b.id}`);
        else L.push(`double V_${b.id}(int i) { return EMPTY_VALUE; } // TODO unsupported block ${b.type}: ${b.id}`);
    }
  }
  L.push('');
  L.push('int OnInit()');
  L.push('{');
  plots.forEach((p, k) => { L.push(`   SetIndexBuffer(${k}, Buf_${p.id}, INDICATOR_DATA);`); L.push(`   ArraySetAsSeries(Buf_${p.id}, true);`); });
  for (const b of inds) {
    const p = b.params || {};
    const src = b.type === 'indicator.atr' ? 'close' : sourceName(p.source);
    const ap = appliedPrice[src] || 'PRICE_CLOSE';
    const note = (b.type !== 'indicator.atr' && !appliedPrice[src]) ? ' // TODO ohlc4 has no MQL5 applied price; using close' : '';
    if (b.type === 'indicator.ema') L.push(`   h_${b.id} = iMA(${S}, ${p.length}, 0, MODE_EMA, ${ap});${note}`);
    if (b.type === 'indicator.sma') L.push(`   h_${b.id} = iMA(${S}, ${p.length}, 0, MODE_SMA, ${ap});${note}`);
    if (b.type === 'indicator.rsi') L.push(`   h_${b.id} = iRSI(${S}, ${p.length}, ${ap});${note}`);
    if (b.type === 'indicator.atr') L.push(`   h_${b.id} = iATR(${S}, ${p.length});`);
    L.push(`   if (h_${b.id} == INVALID_HANDLE) return(INIT_FAILED);`);
    L.push(`   ArraySetAsSeries(A_${b.id}, true);`);
  }
  L.push(`   IndicatorSetString(INDICATOR_SHORTNAME, ${q('BSV — ' + safeTitle(recipe))});`);
  L.push('   return(INIT_SUCCEEDED);');
  L.push('}');
  L.push('');
  L.push('void OnDeinit(const int reason)');
  L.push('{');
  for (const b of inds) L.push(`   if (h_${b.id} != INVALID_HANDLE) IndicatorRelease(h_${b.id});`);
  L.push('}');
  L.push('');
  L.push('int OnCalculate(const int rates_total, const int prev_calculated,');
  L.push('                const datetime &time[], const double &open[], const double &high[],');
  L.push('                const double &low[], const double &close[], const long &tick_volume[],');
  L.push('                const long &volume[], const int &spread[])');
  L.push('{');
  L.push('   if (rates_total <= BSV_WARMUP) return(0);');
  L.push('   // Series indexing (0 = newest bar), the same as the MQL4 target.');
  L.push('   int limit = rates_total - prev_calculated;');
  L.push('   if (prev_calculated > 0) limit++;');
  L.push('   if (limit > rates_total - BSV_WARMUP) limit = rates_total - BSV_WARMUP;');
  L.push('   int need = MathMin(rates_total, MathMax(limit + 2, 3));');
  for (const b of inds) L.push(`   if (CopyBuffer(h_${b.id}, 0, 0, need, A_${b.id}) < need) return(0); // data not ready yet`);
  L.push('   for (int i = limit - 1; i >= 0; i--)');
  L.push('   {');
  for (const p of plots) L.push(`      Buf_${p.id}[i] = ${val(p.params?.source, 'i')};`);
  L.push('   }');
  for (const a of alerts) {
    L.push(`   // ${a.id}: alert once per closed bar.`);
    L.push(`   if (${bool(a.params?.when, '1')} && g_alert_${a.id} != iTime(${S}, 1)) { g_alert_${a.id} = iTime(${S}, 1); Alert(${q(String(a.params?.message || a.id).replace(/[\r\n]/g, ' '))}); }`);
  }
  L.push('   return(rates_total);');
  L.push('}');
  L.push('');
  L.push('// Compile in MetaEditor, check every TODO, then test on history and a demo account before relying on it.');
  return L.join('\n') + '\n';
}

function renderCTrader(recipe) {
  const map = blockMap(recipe);
  const cls = className(recipe);
  const plots = recipe.blocks.filter(b => b.type === 'visual.plot');
  const alerts = recipe.blocks.filter(b => b.type === 'alert.condition');
  const inds = recipe.blocks.filter(b => ['indicator.ema', 'indicator.sma', 'indicator.rsi', 'indicator.atr'].includes(b.type));
  const series = { open: 'Bars.OpenPrices', high: 'Bars.HighPrices', low: 'Bars.LowPrices', close: 'Bars.ClosePrices', hl2: 'Bars.MedianPrices', hlc3: 'Bars.TypicalPrices' };
  const priceAt = (ref, at) => ref === 'ohlc4' ? `(Bars.OpenPrices[${at}] + Bars.HighPrices[${at}] + Bars.LowPrices[${at}] + Bars.ClosePrices[${at}]) / 4.0` : `${series[ref]}[${at}]`;
  const val = (ref, at) => isPrice(ref) ? priceAt(ref, at) : (isBoolType(map.get(ref)?.type) ? `(S_${ref}(${at}) ? 1.0 : 0.0)` : `V_${ref}(${at})`);
  const bool = (ref, at) => isBoolType(map.get(ref)?.type) ? `S_${ref}(${at})` : `(${val(ref, at)} != 0.0 && !double.IsNaN(${val(ref, at)}))`;
  const L = [];
  L.push('// ORIGINAL BSV STARTER — cTrader Algo (C#) custom indicator. Build in cTrader before use.');
  L.push('// Generated by BSV Trader Tool Blocks. Not runtime tested by BSV. Not investment advice.');
  L.push('using System;');
  L.push('using cAlgo.API;');
  L.push('using cAlgo.API.Indicators;');
  L.push('');
  L.push('namespace cAlgo');
  L.push('{');
  L.push(`    [Indicator(IsOverlay = ${recipe.overlay ? 'true' : 'false'}, TimeZone = TimeZones.UTC, AccessRights = AccessRights.None)]`);
  L.push(`    public class ${cls} : Indicator`);
  L.push('    {');
  L.push(`        private const int Warmup = ${warmup(recipe)};`);
  for (const b of inds) {
    const t = { 'indicator.ema': 'ExponentialMovingAverage', 'indicator.sma': 'SimpleMovingAverage', 'indicator.rsi': 'RelativeStrengthIndex', 'indicator.atr': 'AverageTrueRange' }[b.type];
    L.push(`        private ${t} _${b.id};`);
  }
  for (const a of alerts) L.push(`        private int _alert_${a.id} = -1;`);
  for (const p of plots) {
    L.push('');
    L.push(`        [Output(${q(String(p.params?.title || p.id).replace(/"/g, ''))})]`);
    L.push(`        public IndicatorDataSeries Out_${p.id} { get; set; }`);
  }
  L.push('');
  L.push('        protected override void Initialize()');
  L.push('        {');
  for (const b of inds) {
    const p = b.params || {};
    const src = () => series[sourceName(p.source)] || 'Bars.ClosePrices';
    const note = () => sourceName(p.source) === 'ohlc4' ? ' // TODO ohlc4 has no built-in series; using close' : '';
    if (b.type === 'indicator.ema') L.push(`            _${b.id} = Indicators.ExponentialMovingAverage(${src()}, ${p.length});${note()}`);
    if (b.type === 'indicator.sma') L.push(`            _${b.id} = Indicators.SimpleMovingAverage(${src()}, ${p.length});${note()}`);
    if (b.type === 'indicator.rsi') L.push(`            _${b.id} = Indicators.RelativeStrengthIndex(${src()}, ${p.length});${note()}`);
    if (b.type === 'indicator.atr') L.push(`            _${b.id} = Indicators.AverageTrueRange(${p.length}, MovingAverageType.WilderSmoothing);`);
  }
  L.push('        }');
  L.push('');
  L.push('        public override void Calculate(int index)');
  L.push('        {');
  L.push('            if (index < Warmup)');
  L.push('                return;');
  for (const p of plots) L.push(`            Out_${p.id}[index] = ${val(p.params?.source, 'index')};`);
  if (alerts.length) {
    L.push('            if (!IsLastBar)');
    L.push('                return;');
    L.push('            int i = index - 1; // last closed bar');
    for (const a of alerts) {
      L.push(`            if (${bool(a.params?.when, 'i')} && _alert_${a.id} != i)`);
      L.push('            {');
      L.push(`                _alert_${a.id} = i;`);
      L.push(`                Print(${q(String(a.params?.message || a.id).replace(/[\r\n]/g, ' '))}); // swap for Notifications if you want sound/email; no auto-trading`);
      L.push('            }');
    }
  }
  L.push('        }');
  for (const b of recipe.blocks) {
    const p = b.params || {};
    switch (b.type) {
      case 'indicator.ema': case 'indicator.sma': case 'indicator.rsi': case 'indicator.atr':
        L.push('', `        private double V_${b.id}(int i) { return _${b.id}.Result[i]; }`);
        break;
      case 'filter.session': {
        const ss = parseSession(p);
        L.push('', `        // TODO ${b.id}: bar times are UTC (see TimeZone attribute); convert session ${p.session || ''} from ${p.timezone || 'Etc/UTC'}.`,
          `        private bool S_${b.id}(int i) { var t = Bars.OpenTimes[i]; int m = t.Hour * 60 + t.Minute; return ${ss.start <= ss.end ? `m >= ${ss.start} && m < ${ss.end}` : `m >= ${ss.start} || m < ${ss.end}`}; }`);
        break;
      }
      case 'signal.cross': {
        const [gt, le] = p.direction === 'below' ? ['<', '>='] : ['>', '<='];
        L.push('', `        private bool S_${b.id}(int i) { return ${val(p.left, 'i')} ${gt} ${val(p.right, 'i')} && ${val(p.left, 'i - 1')} ${le} ${val(p.right, 'i - 1')}; }`);
        break;
      }
      case 'signal.threshold':
        if (!Number.isFinite(Number(p.value))) throw new Error(`Invalid threshold in ${b.id}`);
        L.push('', `        private bool S_${b.id}(int i) { return ${val(p.left, 'i')} ${thresholdOp(p)} ${Number(p.value)}; }`);
        break;
      case 'signal.combine':
        L.push('', `        private bool S_${b.id}(int i) { return ${(p.signals || []).map(x => bool(x, 'i')).join(p.mode === 'any' ? ' || ' : ' && ') || 'false'}; }`);
        break;
      case 'visual.plot': case 'alert.condition':
        break;
      default:
        if (isBoolType(b.type)) L.push('', `        private bool S_${b.id}(int i) { return false; } // TODO unsupported block ${b.type}: ${b.id}`);
        else L.push('', `        private double V_${b.id}(int i) { return double.NaN; } // TODO unsupported block ${b.type}: ${b.id}`);
    }
  }
  L.push('    }');
  L.push('}');
  return L.join('\n') + '\n';
}

// ---------------------------------------------------------------------------
// Shared helpers for the MQL4 / cTrader Python / Bookmap Python targets.
// Blocks of type signal.* / filter.* / alert.* are booleans; everything else is a value.
// ---------------------------------------------------------------------------
function isPrice(ref) {
  return ['open','high','low','close','hl2','hlc3','ohlc4'].includes(ref);
}

function isBoolType(type) {
  return /^(signal|filter|alert)\./.test(type || '');
}

function parseSession(p) {
  const m = /^(\d{2})(\d{2})-(\d{2})(\d{2})$/.exec(String(p.session || '0000-2359'));
  if (!m) throw new Error('session must look like HHMM-HHMM');
  return { start: (+m[1]) * 60 + (+m[2]), end: (+m[3]) * 60 + (+m[4]) };
}

function thresholdOp(p) {
  return ['>','>=','<','<=','==','!='].includes(p.op) ? p.op : '>=';
}

function warmup(recipe) {
  let n = 2;
  for (const b of recipe.blocks) if (Number.isInteger(b.params?.length)) n = Math.max(n, b.params.length * 3 + 2);
  return n;
}

function renderMql4(recipe) {
  const map = blockMap(recipe);
  const plots = recipe.blocks.filter(b => b.type === 'visual.plot');
  const alerts = recipe.blocks.filter(b => b.type === 'alert.condition');
  const appliedPrice = { open: 'PRICE_OPEN', high: 'PRICE_HIGH', low: 'PRICE_LOW', close: 'PRICE_CLOSE', hl2: 'PRICE_MEDIAN', hlc3: 'PRICE_TYPICAL' };
  const priceExpr = { open: 'Open[i]', high: 'High[i]', low: 'Low[i]', close: 'Close[i]', hl2: '(High[i]+Low[i])/2.0', hlc3: '(High[i]+Low[i]+Close[i])/3.0', ohlc4: '(Open[i]+High[i]+Low[i]+Close[i])/4.0' };
  const val = (ref, at) => isPrice(ref) ? priceExpr[ref].replace(/\[i\]/g, `[${at}]`) : (isBoolType(map.get(ref)?.type) ? `(S_${ref}(${at}) ? 1.0 : 0.0)` : `V_${ref}(${at})`);
  const bool = (ref, at) => isBoolType(map.get(ref)?.type) ? `S_${ref}(${at})` : `(${val(ref, at)} != 0.0 && ${val(ref, at)} != EMPTY_VALUE)`;
  const colors = ['clrDodgerBlue','clrOrange','clrLimeGreen','clrMagenta','clrGold','clrAqua'];
  const L = [];
  L.push('// ORIGINAL BSV STARTER — MT4 / MQL4 custom indicator. Compile in MetaEditor (MT4) before use.');
  L.push('// Generated by BSV Trader Tool Blocks. Not runtime tested by BSV. Not investment advice.');
  L.push('#property strict');
  L.push(recipe.overlay ? '#property indicator_chart_window' : '#property indicator_separate_window');
  L.push(`#property indicator_buffers ${plots.length}`);
  L.push('');
  for (const p of plots) L.push(`double Buf_${p.id}[];`);
  for (const a of alerts) L.push(`datetime g_alert_${a.id} = 0;`);
  L.push(`#define BSV_WARMUP ${warmup(recipe)}`);
  L.push('');
  for (const b of recipe.blocks) {
    const p = b.params || {};
    switch (b.type) {
      case 'indicator.ema':
      case 'indicator.sma': {
        const mode = b.type === 'indicator.ema' ? 'MODE_EMA' : 'MODE_SMA';
        const src = sourceName(p.source);
        if (appliedPrice[src]) L.push(`double V_${b.id}(int i) { return iMA(NULL, 0, ${p.length}, 0, ${mode}, ${appliedPrice[src]}, i); }`);
        else L.push(`double V_${b.id}(int i) { return iMA(NULL, 0, ${p.length}, 0, ${mode}, PRICE_CLOSE, i); } // TODO ohlc4 has no MQL4 applied price; using close`);
        break;
      }
      case 'indicator.rsi': {
        const src = sourceName(p.source);
        if (appliedPrice[src]) L.push(`double V_${b.id}(int i) { return iRSI(NULL, 0, ${p.length}, ${appliedPrice[src]}, i); }`);
        else L.push(`double V_${b.id}(int i) { return iRSI(NULL, 0, ${p.length}, PRICE_CLOSE, i); } // TODO ohlc4 has no MQL4 applied price; using close`);
        break;
      }
      case 'indicator.atr':
        L.push(`double V_${b.id}(int i) { return iATR(NULL, 0, ${p.length}, i); }`);
        break;
      case 'filter.session': {
        const ss = parseSession(p);
        L.push(`// TODO ${b.id}: session ${p.session || ''} is evaluated in broker server time; convert from ${p.timezone || 'Etc/UTC'} for your broker.`);
        L.push(`bool S_${b.id}(int i) { int m = TimeHour(Time[i]) * 60 + TimeMinute(Time[i]); return ${ss.start <= ss.end ? `m >= ${ss.start} && m < ${ss.end}` : `m >= ${ss.start} || m < ${ss.end}`}; }`);
        break;
      }
      case 'signal.cross': {
        const [gt, le] = p.direction === 'below' ? ['<', '>='] : ['>', '<='];
        L.push(`bool S_${b.id}(int i) { return ${val(p.left, 'i')} ${gt} ${val(p.right, 'i')} && ${val(p.left, 'i+1')} ${le} ${val(p.right, 'i+1')}; }`);
        break;
      }
      case 'signal.threshold':
        if (!Number.isFinite(Number(p.value))) throw new Error(`Invalid threshold in ${b.id}`);
        L.push(`bool S_${b.id}(int i) { return ${val(p.left, 'i')} ${thresholdOp(p)} ${Number(p.value)}; }`);
        break;
      case 'signal.combine':
        L.push(`bool S_${b.id}(int i) { return ${(p.signals || []).map(x => bool(x, 'i')).join(p.mode === 'any' ? ' || ' : ' && ') || 'false'}; }`);
        break;
      case 'visual.plot':
      case 'alert.condition':
        break;
      default:
        if (isBoolType(b.type)) L.push(`bool S_${b.id}(int i) { return false; } // TODO unsupported block ${b.type}: ${b.id}`);
        else L.push(`double V_${b.id}(int i) { return EMPTY_VALUE; } // TODO unsupported block ${b.type}: ${b.id}`);
    }
  }
  L.push('');
  L.push('int OnInit()');
  L.push('{');
  L.push(`   IndicatorShortName(${q('BSV — ' + safeTitle(recipe))});`);
  plots.forEach((p, k) => {
    L.push(`   SetIndexBuffer(${k}, Buf_${p.id});`);
    L.push(`   SetIndexStyle(${k}, DRAW_LINE, STYLE_SOLID, 1, ${colors[k % colors.length]});`);
    L.push(`   SetIndexLabel(${k}, ${q(p.params?.title || p.params?.source || p.id)});`);
  });
  L.push('   return(INIT_SUCCEEDED);');
  L.push('}');
  L.push('');
  L.push('int OnCalculate(const int rates_total, const int prev_calculated,');
  L.push('                const datetime &time[], const double &open[], const double &high[],');
  L.push('                const double &low[], const double &close[], const long &tick_volume[],');
  L.push('                const long &volume[], const int &spread[])');
  L.push('{');
  L.push('   if (rates_total <= BSV_WARMUP) return(0);');
  L.push('   int limit = rates_total - prev_calculated;');
  L.push('   if (prev_calculated > 0) limit++;');
  L.push('   if (limit > rates_total - BSV_WARMUP) limit = rates_total - BSV_WARMUP;');
  L.push('   for (int i = limit - 1; i >= 0; i--)');
  L.push('   {');
  for (const p of plots) L.push(`      Buf_${p.id}[i] = ${val(p.params?.source, 'i')};`);
  L.push('   }');
  for (const a of alerts) {
    L.push(`   // ${a.id}: alert once per closed bar.`);
    L.push(`   if (${bool(a.params?.when, '1')} && g_alert_${a.id} != Time[1]) { g_alert_${a.id} = Time[1]; Alert(${q(String(a.params?.message || a.id).replace(/[\r\n]/g, ' '))}); }`);
  }
  L.push('   return(rates_total);');
  L.push('}');
  L.push('');
  L.push('// Compile in MetaEditor, check every TODO, then test on history and a demo account before relying on it.');
  return L.join('\n') + '\n';
}

function renderCTraderPython(recipe) {
  const map = blockMap(recipe);
  const cls = className(recipe);
  const plots = recipe.blocks.filter(b => b.type === 'visual.plot');
  const alerts = recipe.blocks.filter(b => b.type === 'alert.condition');
  const series = { open: 'api.Bars.OpenPrices', high: 'api.Bars.HighPrices', low: 'api.Bars.LowPrices', close: 'api.Bars.ClosePrices', hl2: 'api.Bars.MedianPrices', hlc3: 'api.Bars.TypicalPrices' };
  const priceAt = (ref, at) => ref === 'ohlc4' ? `(api.Bars.OpenPrices[${at}] + api.Bars.HighPrices[${at}] + api.Bars.LowPrices[${at}] + api.Bars.ClosePrices[${at}]) / 4.0` : `${series[ref]}[${at}]`;
  const val = (ref, at) => isPrice(ref) ? priceAt(ref, at) : (isBoolType(map.get(ref)?.type) ? `(1.0 if self.s_${ref}(${at}) else 0.0)` : `self.v_${ref}(${at})`);
  const bool = (ref, at) => isBoolType(map.get(ref)?.type) ? `self.s_${ref}(${at})` : `bool(${val(ref, at)})`;
  const L = [];
  L.push('# ORIGINAL BSV STARTER — cTrader Algo Python custom indicator. Build in cTrader before use.');
  L.push('# Generated by BSV Trader Tool Blocks. Not runtime tested by BSV. Not investment advice.');
  L.push('#');
  L.push(`# 1) In cTrader Algo create a new Python indicator named ${cls}.`);
  L.push(`# 2) Replace the attribute file ${cls}.cs with:`);
  L.push('#');
  L.push('#    using System;');
  L.push('#    using cAlgo.API;');
  L.push('#    namespace cAlgo.Indicators;');
  L.push(`#    [Indicator(IsOverlay = ${recipe.overlay ? 'true' : 'false'}, TimeZone = TimeZones.UTC, AccessRights = AccessRights.None)]`);
  L.push(`#    public partial class ${cls} : Indicator`);
  L.push('#    {');
  for (const p of plots) {
    L.push(`#        [Output(${q(String(p.params?.title || p.id).replace(/"/g, ''))})]`);
    L.push(`#        public IndicatorDataSeries Out_${p.id} { get; set; }`);
  }
  L.push('#    }');
  L.push('#');
  L.push(`# 3) Replace ${cls}_main.py with this file and build.`);
  L.push('');
  L.push('import clr');
  L.push('clr.AddReference("cAlgo.API")');
  L.push('from cAlgo.API import *');
  L.push('');
  L.push(`WARMUP = ${warmup(recipe)}`);
  L.push('');
  L.push(`class ${cls}():`);
  L.push('    def initialize(self):');
  L.push('        self.last_alert = {}');
  for (const b of recipe.blocks) {
    const p = b.params || {};
    const src = () => series[sourceName(p.source)] || 'api.Bars.ClosePrices';
    const note = () => sourceName(p.source) === 'ohlc4' ? '  # TODO ohlc4 has no built-in series; using close' : '';
    if (b.type === 'indicator.ema') L.push(`        self.${b.id} = api.Indicators.ExponentialMovingAverage(${src()}, ${p.length})${note()}`);
    if (b.type === 'indicator.sma') L.push(`        self.${b.id} = api.Indicators.SimpleMovingAverage(${src()}, ${p.length})${note()}`);
    if (b.type === 'indicator.rsi') L.push(`        self.${b.id} = api.Indicators.RelativeStrengthIndex(${src()}, ${p.length})${note()}`);
    if (b.type === 'indicator.atr') L.push(`        self.${b.id} = api.Indicators.AverageTrueRange(${p.length}, MovingAverageType.WilderSmoothing)`);
  }
  L.push('');
  L.push('    def calculate(self, index):');
  L.push('        if index < WARMUP:');
  L.push('            return');
  for (const p of plots) L.push(`        api.Out_${p.id}[index] = ${val(p.params?.source, 'index')}`);
  if (alerts.length) {
    L.push('        if api.IsLastBar:');
    L.push('            i = index - 1  # last closed bar');
    for (const a of alerts) {
      L.push(`            if ${bool(a.params?.when, 'i')} and self.last_alert.get(${q(a.id)}) != i:`);
      L.push(`                self.last_alert[${q(a.id)}] = i`);
      L.push(`                api.Print(${q(String(a.params?.message || a.id).replace(/[\r\n]/g, ' '))})  # swap for api.Notifications if you want sound/email`);
    }
  }
  for (const b of recipe.blocks) {
    const p = b.params || {};
    switch (b.type) {
      case 'indicator.ema': case 'indicator.sma': case 'indicator.rsi': case 'indicator.atr':
        L.push('', `    def v_${b.id}(self, i):`, `        return self.${b.id}.Result[i]`);
        break;
      case 'filter.session': {
        const ss = parseSession(p);
        L.push('', `    def s_${b.id}(self, i):`, `        # TODO ${b.id}: bar times are UTC (see TimeZone attribute); convert session ${p.session || ''} from ${p.timezone || 'Etc/UTC'}.`,
          '        t = api.Bars.OpenTimes[i]', '        m = t.Hour * 60 + t.Minute', `        return ${ss.start <= ss.end ? `${ss.start} <= m < ${ss.end}` : `m >= ${ss.start} or m < ${ss.end}`}`);
        break;
      }
      case 'signal.cross': {
        const [gt, le] = p.direction === 'below' ? ['<', '>='] : ['>', '<='];
        L.push('', `    def s_${b.id}(self, i):`, `        return ${val(p.left, 'i')} ${gt} ${val(p.right, 'i')} and ${val(p.left, 'i - 1')} ${le} ${val(p.right, 'i - 1')}`);
        break;
      }
      case 'signal.threshold':
        if (!Number.isFinite(Number(p.value))) throw new Error(`Invalid threshold in ${b.id}`);
        L.push('', `    def s_${b.id}(self, i):`, `        return ${val(p.left, 'i')} ${thresholdOp(p)} ${Number(p.value)}`);
        break;
      case 'signal.combine':
        L.push('', `    def s_${b.id}(self, i):`, `        return ${(p.signals || []).map(x => bool(x, 'i')).join(p.mode === 'any' ? ' or ' : ' and ') || 'False'}`);
        break;
      case 'visual.plot': case 'alert.condition':
        break;
      default:
        if (isBoolType(b.type)) L.push('', `    def s_${b.id}(self, i):`, `        return False  # TODO unsupported block ${b.type}: ${b.id}`);
        else L.push('', `    def v_${b.id}(self, i):`, `        return float('nan')  # TODO unsupported block ${b.type}: ${b.id}`);
    }
  }
  return L.join('\n') + '\n';
}

function renderBookmapPython(recipe) {
  const plots = recipe.blocks.filter(b => b.type === 'visual.plot');
  const graph = recipe.overlay ? 'PRIMARY' : 'BOTTOM';
  const R = ref => `vals.get(${q(ref)})`;
  const L = [];
  L.push("# ORIGINAL BSV STARTER — Bookmap Python API add-on (Bookmap's Python API is in open beta).");
  L.push('# Generated by BSV Trader Tool Blocks. Not runtime tested by BSV. Not investment advice.');
  L.push('# Bookmap is order-flow based: this starter builds time bars from trades (BAR_SECONDS)');
  L.push('# and evaluates the recipe on each closed bar. Load it via the Bookmap Python API add-on.');
  L.push('# API reference: https://github.com/BookmapAPI/python-api');
  L.push('import time');
  L.push('from collections import deque');
  L.push('import bookmap as bm');
  L.push('');
  L.push('BAR_SECONDS = 60');
  L.push('INTERVALS_PER_BAR = BAR_SECONDS * 10  # on_interval fires every 0.1 s');
  L.push(`PLOTS = ${JSON.stringify(plots.map(p => [p.id, String(p.params?.title || p.id)]))}`);
  L.push(`GRAPH = ${q(graph)}  # PRIMARY = price heatmap, BOTTOM = sub-chart`);
  L.push('');
  L.push('class Ema:');
  L.push('    def __init__(self, n): self.n, self.a, self.v, self.k, self.s = n, 2.0 / (n + 1), None, 0, 0.0');
  L.push('    def update(self, x):');
  L.push('        if self.v is None:');
  L.push('            self.k += 1; self.s += x');
  L.push('            if self.k >= self.n: self.v = self.s / self.n');
  L.push('        else:');
  L.push('            self.v = x * self.a + self.v * (1 - self.a)');
  L.push('        return self.v');
  L.push('');
  L.push('class Sma:');
  L.push('    def __init__(self, n): self.n, self.q = n, deque(maxlen=n)');
  L.push('    def update(self, x):');
  L.push('        self.q.append(x)');
  L.push('        return sum(self.q) / self.n if len(self.q) == self.n else None');
  L.push('');
  L.push('class Rsi:  # Wilder smoothing');
  L.push('    def __init__(self, n): self.n, self.prev, self.g, self.l, self.k = n, None, 0.0, 0.0, 0');
  L.push('    def update(self, x):');
  L.push('        if self.prev is None:');
  L.push('            self.prev = x');
  L.push('            return None');
  L.push('        ch, self.prev = x - self.prev, x');
  L.push('        up, dn = max(ch, 0.0), max(-ch, 0.0)');
  L.push('        self.k += 1');
  L.push('        if self.k <= self.n:');
  L.push('            self.g += up / self.n; self.l += dn / self.n');
  L.push('            if self.k < self.n: return None');
  L.push('        else:');
  L.push('            self.g = (self.g * (self.n - 1) + up) / self.n; self.l = (self.l * (self.n - 1) + dn) / self.n');
  L.push('        return 100.0 if self.l == 0 else 100.0 - 100.0 / (1 + self.g / self.l)');
  L.push('');
  L.push('class Atr:  # Wilder smoothing of true range');
  L.push('    def __init__(self, n): self.n, self.pc, self.v, self.k, self.s = n, None, None, 0, 0.0');
  L.push('    def update(self, b):');
  L.push('        tr = b["h"] - b["l"] if self.pc is None else max(b["h"] - b["l"], abs(b["h"] - self.pc), abs(b["l"] - self.pc))');
  L.push('        self.pc = b["c"]');
  L.push('        if self.v is None:');
  L.push('            self.k += 1; self.s += tr');
  L.push('            if self.k >= self.n: self.v = self.s / self.n');
  L.push('        else:');
  L.push('            self.v = (self.v * (self.n - 1) + tr) / self.n');
  L.push('        return self.v');
  L.push('');
  L.push('def make_calc():');
  L.push('    return {');
  for (const b of recipe.blocks) {
    const p = b.params || {};
    const cls = { 'indicator.ema': 'Ema', 'indicator.sma': 'Sma', 'indicator.rsi': 'Rsi', 'indicator.atr': 'Atr' }[b.type];
    if (cls) L.push(`        ${q(b.id)}: ${cls}(${p.length}),`);
  }
  L.push('    }');
  L.push('');
  L.push('def evaluate(s, b):');
  L.push('    # Runs the recipe on one closed bar b = {o, h, l, c, t}; returns the values by block id.');
  L.push('    calc, prev = s["calc"], s["prev"]');
  L.push('    vals = {"open": b["o"], "high": b["h"], "low": b["l"], "close": b["c"], "hl2": (b["h"] + b["l"]) / 2.0,');
  L.push('            "hlc3": (b["h"] + b["l"] + b["c"]) / 3.0, "ohlc4": (b["o"] + b["h"] + b["l"] + b["c"]) / 4.0}');
  for (const b of recipe.blocks) {
    const p = b.params || {};
    switch (b.type) {
      case 'indicator.ema': case 'indicator.sma': case 'indicator.rsi':
        L.push(`    vals[${q(b.id)}] = calc[${q(b.id)}].update(vals[${q(sourceName(p.source))}])`);
        break;
      case 'indicator.atr':
        L.push(`    vals[${q(b.id)}] = calc[${q(b.id)}].update(b)`);
        break;
      case 'filter.session': {
        const ss = parseSession(p);
        L.push(`    # TODO ${b.id}: bar time is UTC here; convert session ${p.session || ''} from ${p.timezone || 'Etc/UTC'}.`);
        L.push('    g = time.gmtime(b["t"])');
        L.push('    m = g.tm_hour * 60 + g.tm_min');
        L.push(`    vals[${q(b.id)}] = ${ss.start <= ss.end ? `${ss.start} <= m < ${ss.end}` : `m >= ${ss.start} or m < ${ss.end}`}`);
        break;
      }
      case 'signal.cross': {
        const [gt, le] = p.direction === 'below' ? ['<', '>='] : ['>', '<='];
        L.push(`    l, r, pl, pr = ${R(p.left)}, ${R(p.right)}, prev.get(${q(p.left)}), prev.get(${q(p.right)})`);
        L.push(`    vals[${q(b.id)}] = None not in (l, r, pl, pr) and l ${gt} r and pl ${le} pr`);
        break;
      }
      case 'signal.threshold':
        if (!Number.isFinite(Number(p.value))) throw new Error(`Invalid threshold in ${b.id}`);
        L.push(`    v = ${R(p.left)}`);
        L.push(`    vals[${q(b.id)}] = v is not None and v ${thresholdOp(p)} ${Number(p.value)}`);
        break;
      case 'signal.combine':
        L.push(`    vals[${q(b.id)}] = ${(p.signals || []).map(x => `bool(${R(x)})`).join(p.mode === 'any' ? ' or ' : ' and ') || 'False'}`);
        break;
      case 'visual.plot': case 'alert.condition':
        break;
      default:
        L.push(`    vals[${q(b.id)}] = None  # TODO unsupported block ${b.type}: ${b.id}`);
    }
  }
  L.push('    return vals');
  L.push('');
  L.push('def on_bar_closed(addon, alias, s, b):');
  L.push('    vals = evaluate(s, b)');
  for (const p of plots) {
    L.push(`    v = vals.get(${q(p.params?.source)})`);
    L.push(`    if v is not None and ${q(p.id)} in s["ind"]:`);
    L.push(`        bm.add_point(addon, alias, s["ind"][${q(p.id)}], ${graph === 'PRIMARY' ? 'v / s["pips"])  # PRIMARY points are price levels' : 'float(v))  # check BOTTOM scaling in your Bookmap version'}`);
  }
  for (const a of recipe.blocks.filter(b => b.type === 'alert.condition')) {
    L.push(`    if vals.get(${q(a.params?.when)}):`);
    L.push(`        print(alias, ${q(String(a.params?.message || a.id).replace(/[\r\n]/g, ' '))}, flush=True)  # one line per closed bar`);
  }
  L.push('    s["prev"] = vals');
  L.push('');
  L.push('state = {}');
  L.push('requests = {}');
  L.push('next_req = [1]');
  L.push('');
  L.push('def handle_subscribe_instrument(addon, alias, full_name, is_crypto, pips, size_multiplier, instrument_multiplier, supported_features):');
  L.push('    state[alias] = {"pips": pips, "bar": None, "ticks": 0, "calc": make_calc(), "prev": {}, "ind": {}}');
  L.push('    for pid, title in PLOTS:');
  L.push('        req = next_req[0]');
  L.push('        next_req[0] += 1');
  L.push('        requests[req] = (alias, pid)');
  L.push('        bm.register_indicator(addon, alias, req, "BSV " + title, GRAPH)');
  L.push('    req = next_req[0]');
  L.push('    next_req[0] += 1');
  L.push('    bm.subscribe_to_trades(addon, alias, req)');
  L.push('');
  L.push('def handle_unsubscribe_instrument(addon, alias):');
  L.push('    state.pop(alias, None)');
  L.push('');
  L.push('def handle_indicator_response(addon, request_id, indicator_id):');
  L.push('    if request_id in requests:');
  L.push('        alias, pid = requests[request_id]');
  L.push('        if alias in state:');
  L.push('            state[alias]["ind"][pid] = indicator_id');
  L.push('');
  L.push('def handle_trades(addon, alias, price_level, size_level, is_otc, is_bid, is_execution_start, is_execution_end, aggressor_order_id, passive_order_id):');
  L.push('    s = state.get(alias)');
  L.push('    if s is None:');
  L.push('        return');
  L.push('    px = price_level * s["pips"]');
  L.push('    b = s["bar"]');
  L.push('    if b is None:');
  L.push('        s["bar"] = {"o": px, "h": px, "l": px, "c": px, "t": time.time()}');
  L.push('    else:');
  L.push('        b["h"] = max(b["h"], px)');
  L.push('        b["l"] = min(b["l"], px)');
  L.push('        b["c"] = px');
  L.push('');
  L.push('def on_interval(addon, alias):');
  L.push('    s = state.get(alias)');
  L.push('    if s is None:');
  L.push('        return');
  L.push('    s["ticks"] += 1');
  L.push('    if s["ticks"] >= INTERVALS_PER_BAR:');
  L.push('        s["ticks"] = 0');
  L.push('        b, s["bar"] = s["bar"], None');
  L.push('        if b is not None:  # bars without trades are skipped');
  L.push('            on_bar_closed(addon, alias, s, b)');
  L.push('');
  L.push('if __name__ == "__main__":');
  L.push('    addon = bm.create_addon()');
  L.push('    bm.add_trades_handler(addon, handle_trades)');
  L.push('    bm.add_on_interval_handler(addon, on_interval)');
  L.push('    bm.add_indicator_response_handler(addon, handle_indicator_response)');
  L.push('    bm.start_addon(addon, handle_subscribe_instrument, handle_unsubscribe_instrument)');
  L.push('    bm.wait_until_addon_is_turned_off(addon)');
  return L.join('\n') + '\n';
}

function plotName(p) {
  return String(p.params?.title || p.id).replace(/[^A-Za-z0-9]+/g, '') || p.id;
}

function renderNinja(recipe) {
  const map = blockMap(recipe);
  const cls = 'Bsv' + className(recipe);
  const plots = recipe.blocks.filter(b => b.type === 'visual.plot');
  const alerts = recipe.blocks.filter(b => b.type === 'alert.condition');
  const inds = recipe.blocks.filter(b => ['indicator.ema', 'indicator.sma', 'indicator.rsi', 'indicator.atr'].includes(b.type));
  const series = { open: 'Open', high: 'High', low: 'Low', close: 'Close', hl2: 'Median', hlc3: 'Typical' };
  const priceAt = (ref, at) => ref === 'ohlc4' ? `(Open[${at}] + High[${at}] + Low[${at}] + Close[${at}]) / 4.0` : `${series[ref]}[${at}]`;
  const val = (ref, at) => isPrice(ref) ? priceAt(ref, at) : (isBoolType(map.get(ref)?.type) ? `(S_${ref}(${at}) ? 1.0 : 0.0)` : `V_${ref}(${at})`);
  const bool = (ref, at) => isBoolType(map.get(ref)?.type) ? `S_${ref}(${at})` : `(${val(ref, at)} != 0.0 && !double.IsNaN(${val(ref, at)}))`;
  const brushes = ['DodgerBlue', 'Orange', 'LimeGreen', 'Magenta', 'Gold', 'Aqua'];
  const L = [];
  L.push('// ORIGINAL BSV STARTER — NinjaTrader 8 NinjaScript indicator. Compile in the NinjaScript Editor before use.');
  L.push('// Generated by BSV Trader Tool Blocks. Not runtime tested by BSV. Not investment advice.');
  L.push(`// Save as Documents\\NinjaTrader 8\\bin\\Custom\\Indicators\\${cls}.cs (or create a new indicator named ${cls} and paste).`);
  L.push('#region Using declarations');
  L.push('using System;');
  L.push('using System.Windows.Media;');
  L.push('using NinjaTrader.Gui;');
  L.push('using NinjaTrader.Data;');
  L.push('using NinjaTrader.NinjaScript;');
  L.push('#endregion');
  L.push('');
  L.push('namespace NinjaTrader.NinjaScript.Indicators');
  L.push('{');
  L.push(`    public class ${cls} : Indicator`);
  L.push('    {');
  L.push(`        private const int Warmup = ${warmup(recipe)};`);
  for (const b of inds) L.push(`        private ${{ 'indicator.ema': 'EMA', 'indicator.sma': 'SMA', 'indicator.rsi': 'RSI', 'indicator.atr': 'ATR' }[b.type]} _${b.id};`);
  L.push('');
  L.push('        protected override void OnStateChange()');
  L.push('        {');
  L.push('            if (State == State.SetDefaults)');
  L.push('            {');
  L.push(`                Name = ${q(cls)};`);
  L.push(`                Description = ${q('BSV — ' + safeTitle(recipe))};`);
  L.push('                Calculate = Calculate.OnBarClose;');
  L.push(`                IsOverlay = ${recipe.overlay ? 'true' : 'false'};`);
  L.push('                IsSuspendedWhileInactive = true;');
  plots.forEach((p, k) => L.push(`                AddPlot(Brushes.${brushes[k % brushes.length]}, ${q(plotName(p))});`));
  L.push('            }');
  L.push('            else if (State == State.DataLoaded)');
  L.push('            {');
  for (const b of inds) {
    const p = b.params || {};
    const src = () => series[sourceName(p.source)] || 'Close';
    const note = () => sourceName(p.source) === 'ohlc4' ? ' // TODO ohlc4 has no built-in series; using Close' : '';
    if (b.type === 'indicator.ema') L.push(`                _${b.id} = EMA(${src()}, ${p.length});${note()}`);
    if (b.type === 'indicator.sma') L.push(`                _${b.id} = SMA(${src()}, ${p.length});${note()}`);
    if (b.type === 'indicator.rsi') L.push(`                _${b.id} = RSI(${src()}, ${p.length}, 1);${note()}`);
    if (b.type === 'indicator.atr') L.push(`                _${b.id} = ATR(${p.length});`);
  }
  L.push('            }');
  L.push('        }');
  L.push('');
  L.push('        protected override void OnBarUpdate()');
  L.push('        {');
  L.push('            if (CurrentBar < Warmup)');
  L.push('                return;');
  L.push('            // Calculate.OnBarClose: barsAgo 0 is the bar that just closed.');
  plots.forEach((p, k) => L.push(`            Values[${k}][0] = ${val(p.params?.source, '0')};`));
  for (const a of alerts) {
    L.push(`            // ${a.id}: Alert() only fires in State.Realtime; once per closed bar.`);
    L.push(`            if (${bool(a.params?.when, '0')})`);
    L.push(`                Alert(${q('bsv_' + a.id)}, Priority.Medium, ${q(String(a.params?.message || a.id).replace(/[\r\n]/g, ' '))}, "", 0, Brushes.Black, Brushes.Yellow);`);
  }
  L.push('        }');
  for (const b of recipe.blocks) {
    const p = b.params || {};
    switch (b.type) {
      case 'indicator.ema': case 'indicator.sma': case 'indicator.rsi': case 'indicator.atr':
        L.push('', `        private double V_${b.id}(int ago) { return _${b.id}[ago]; }`);
        break;
      case 'filter.session': {
        const ss = parseSession(p);
        L.push('', `        // TODO ${b.id}: Time[] uses the NinjaTrader time zone setting (Tools > Options > General); convert session ${p.session || ''} from ${p.timezone || 'Etc/UTC'}.`,
          `        private bool S_${b.id}(int ago) { DateTime t = Time[ago]; int m = t.Hour * 60 + t.Minute; return ${ss.start <= ss.end ? `m >= ${ss.start} && m < ${ss.end}` : `m >= ${ss.start} || m < ${ss.end}`}; }`);
        break;
      }
      case 'signal.cross': {
        const [gt, le] = p.direction === 'below' ? ['<', '>='] : ['>', '<='];
        L.push('', `        private bool S_${b.id}(int ago) { return ${val(p.left, 'ago')} ${gt} ${val(p.right, 'ago')} && ${val(p.left, 'ago + 1')} ${le} ${val(p.right, 'ago + 1')}; }`);
        break;
      }
      case 'signal.threshold':
        if (!Number.isFinite(Number(p.value))) throw new Error(`Invalid threshold in ${b.id}`);
        L.push('', `        private bool S_${b.id}(int ago) { return ${val(p.left, 'ago')} ${thresholdOp(p)} ${Number(p.value)}; }`);
        break;
      case 'signal.combine':
        L.push('', `        private bool S_${b.id}(int ago) { return ${(p.signals || []).map(x => bool(x, 'ago')).join(p.mode === 'any' ? ' || ' : ' && ') || 'false'}; }`);
        break;
      case 'visual.plot': case 'alert.condition':
        break;
      default:
        if (isBoolType(b.type)) L.push('', `        private bool S_${b.id}(int ago) { return false; } // TODO unsupported block ${b.type}: ${b.id}`);
        else L.push('', `        private double V_${b.id}(int ago) { return double.NaN; } // TODO unsupported block ${b.type}: ${b.id}`);
    }
  }
  L.push('    }');
  L.push('}');
  L.push('// The NinjaScript Editor appends its own "NinjaScript generated code" region on compile; do not hand-edit it.');
  return L.join('\n') + '\n';
}

function renderQuantower(recipe) {
  const map = blockMap(recipe);
  const cls = 'Bsv' + className(recipe);
  const plots = recipe.blocks.filter(b => b.type === 'visual.plot');
  const alerts = recipe.blocks.filter(b => b.type === 'alert.condition');
  const inds = recipe.blocks.filter(b => ['indicator.ema', 'indicator.sma', 'indicator.rsi', 'indicator.atr'].includes(b.type));
  const pt = { open: 'PriceType.Open', high: 'PriceType.High', low: 'PriceType.Low', close: 'PriceType.Close', hl2: 'PriceType.Median', hlc3: 'PriceType.Typical' };
  const priceAt = (ref, at) => ref === 'ohlc4' ? `(GetPrice(PriceType.Open, ${at}) + GetPrice(PriceType.High, ${at}) + GetPrice(PriceType.Low, ${at}) + GetPrice(PriceType.Close, ${at})) / 4.0` : `GetPrice(${pt[ref]}, ${at})`;
  const val = (ref, at) => isPrice(ref) ? priceAt(ref, at) : (isBoolType(map.get(ref)?.type) ? `(S_${ref}(${at}) ? 1.0 : 0.0)` : `V_${ref}(${at})`);
  const bool = (ref, at) => isBoolType(map.get(ref)?.type) ? `S_${ref}(${at})` : `(${val(ref, at)} != 0.0 && !double.IsNaN(${val(ref, at)}))`;
  const colors = ['DodgerBlue', 'Orange', 'LimeGreen', 'Magenta', 'Gold', 'Aqua'];
  const L = [];
  L.push('// ORIGINAL BSV STARTER — Quantower Algo indicator (C#). Build in Quantower Algo / Visual Studio before use.');
  L.push('// Generated by BSV Trader Tool Blocks. Not runtime tested by BSV. Not investment advice.');
  L.push('using System;');
  L.push('using System.Drawing;');
  L.push('using TradingPlatform.BusinessLayer;');
  L.push('');
  L.push('namespace BsvIndicators');
  L.push('{');
  L.push(`    public class ${cls} : Indicator`);
  L.push('    {');
  L.push(`        private const int Warmup = ${warmup(recipe)};`);
  for (const b of inds) L.push(`        private Indicator _${b.id};`);
  for (const a of alerts) L.push(`        private DateTime _alert_${a.id} = DateTime.MinValue;`);
  L.push('');
  L.push(`        public ${cls}()`);
  L.push('            : base()');
  L.push('        {');
  L.push(`            Name = ${q('BSV — ' + safeTitle(recipe))};`);
  L.push('            Description = "Original BSV generated starter. Not runtime tested by BSV.";');
  plots.forEach((p, k) => L.push(`            AddLineSeries(${q(String(p.params?.title || p.id).replace(/"/g, ''))}, Color.${colors[k % colors.length]}, 1, LineStyle.Solid);`));
  L.push(`            SeparateWindow = ${recipe.overlay ? 'false' : 'true'};`);
  L.push('        }');
  L.push('');
  L.push('        protected override void OnInit()');
  L.push('        {');
  for (const b of inds) {
    const p = b.params || {};
    const src = () => pt[sourceName(p.source)] || 'PriceType.Close';
    const note = () => sourceName(p.source) === 'ohlc4' ? ' // TODO ohlc4 has no PriceType; using Close' : '';
    if (b.type === 'indicator.ema') L.push(`            _${b.id} = Core.Indicators.BuiltIn.EMA(${p.length}, ${src()});${note()}`);
    if (b.type === 'indicator.sma') L.push(`            _${b.id} = Core.Indicators.BuiltIn.SMA(${p.length}, ${src()});${note()}`);
    if (b.type === 'indicator.rsi') L.push(`            _${b.id} = Core.Indicators.BuiltIn.RSI(${p.length}, ${src()}, RSIMode.Exponential, MaMode.SMA, 1);${note()}`);
    if (b.type === 'indicator.atr') L.push(`            _${b.id} = Core.Indicators.BuiltIn.ATR(${p.length}, MaMode.SMMA);`);
    L.push(`            AddIndicator(_${b.id});`);
  }
  L.push('        }');
  L.push('');
  L.push('        protected override void OnUpdate(UpdateArgs args)');
  L.push('        {');
  L.push('            if (Count <= Warmup)');
  L.push('                return;');
  plots.forEach((p, k) => L.push(`            SetValue(${val(p.params?.source, '0')}, ${k});`));
  if (alerts.length) {
    L.push('            if (args.Reason != UpdateReason.NewBar)');
    L.push('                return;');
    L.push('            int i = 1; // the bar that just closed');
    for (const a of alerts) {
      L.push(`            if (${bool(a.params?.when, 'i')} && _alert_${a.id} != Time(i))`);
      L.push('            {');
      L.push(`                _alert_${a.id} = Time(i);`);
      L.push(`                Core.Instance.Loggers.Log(${q(String(a.params?.message || a.id).replace(/[\r\n]/g, ' '))}); // event log line; no order placement`);
      L.push('            }');
    }
  }
  L.push('        }');
  for (const b of recipe.blocks) {
    const p = b.params || {};
    switch (b.type) {
      case 'indicator.ema': case 'indicator.sma': case 'indicator.rsi': case 'indicator.atr':
        L.push('', `        private double V_${b.id}(int offset) { return _${b.id}.GetValue(offset); }`);
        break;
      case 'filter.session': {
        const ss = parseSession(p);
        L.push('', `        // TODO ${b.id}: check the time zone of Time() for your connection; convert session ${p.session || ''} from ${p.timezone || 'Etc/UTC'}.`,
          `        private bool S_${b.id}(int offset) { DateTime t = Time(offset); int m = t.Hour * 60 + t.Minute; return ${ss.start <= ss.end ? `m >= ${ss.start} && m < ${ss.end}` : `m >= ${ss.start} || m < ${ss.end}`}; }`);
        break;
      }
      case 'signal.cross': {
        const [gt, le] = p.direction === 'below' ? ['<', '>='] : ['>', '<='];
        L.push('', `        private bool S_${b.id}(int offset) { return ${val(p.left, 'offset')} ${gt} ${val(p.right, 'offset')} && ${val(p.left, 'offset + 1')} ${le} ${val(p.right, 'offset + 1')}; }`);
        break;
      }
      case 'signal.threshold':
        if (!Number.isFinite(Number(p.value))) throw new Error(`Invalid threshold in ${b.id}`);
        L.push('', `        private bool S_${b.id}(int offset) { return ${val(p.left, 'offset')} ${thresholdOp(p)} ${Number(p.value)}; }`);
        break;
      case 'signal.combine':
        L.push('', `        private bool S_${b.id}(int offset) { return ${(p.signals || []).map(x => bool(x, 'offset')).join(p.mode === 'any' ? ' || ' : ' && ') || 'false'}; }`);
        break;
      case 'visual.plot': case 'alert.condition':
        break;
      default:
        if (isBoolType(b.type)) L.push('', `        private bool S_${b.id}(int offset) { return false; } // TODO unsupported block ${b.type}: ${b.id}`);
        else L.push('', `        private double V_${b.id}(int offset) { return double.NaN; } // TODO unsupported block ${b.type}: ${b.id}`);
    }
  }
  L.push('    }');
  L.push('}');
  return L.join('\n') + '\n';
}


function lipiText(s) {
  return '"' + String(s ?? '').replace(/["\\\r\n]/g, ' ').trim() + '"';
}

function renderLipi(recipe) {
  const RESERVED = new Set(['open', 'high', 'low', 'close', 'volume', 'hl2', 'hlc3', 'hlcc4', 'ohlc4', 'bar_index', 'time', 'time_close', 'timenow', 'year', 'month', 'dayofmonth', 'dayofweek', 'hour', 'minute', 'second', 'na', 'true', 'false', 'and', 'or', 'not', 'if', 'else', 'switch', 'case', 'default', 'static', 'intra', 'for', 'while', 'return', 'color', 'input', 'math', 'str', 'talib', 'plot', 'alert', 'session', 'interval', 'syminfo', 'barstate', 'float', 'int', 'bool', 'string', 'shape', 'location', 'size', 'orderflow', 'chartPoint']);
  const map = blockMap(recipe);
  const nm = new Map(recipe.blocks.map(b => [b.id, RESERVED.has(b.id) ? b.id + '_v' : b.id]));
  const ref = (r) => isPrice(r) ? r : nm.get(r);
  const bool = (r) => isBoolType(map.get(r)?.type) ? nm.get(r) : `(${ref(r)} != 0)`;
  const colors = ['30, 144, 255', '255, 165, 0', '50, 205, 50', '255, 0, 255', '0, 255, 255', '220, 80, 80'];
  const L = [];
  L.push('// ORIGINAL BSV STARTER — GoCharting Lipi indicator. Paste into the Lipi editor and check it there.');
  L.push('// Generated by BSV Trader Tool Blocks. Not runtime tested by BSV. Not investment advice.');
  L.push('// Lipi draws on the chart only: no orders, no other symbols, no other timeframes.');
  L.push(`indicator(${lipiText('BSV — ' + safeTitle(recipe))}, "BSV", ${recipe.overlay ? 'true' : 'false'})`);
  L.push('');
  for (const b of depOrder(recipe)) {
    const p = b.params || {}, n = nm.get(b.id);
    switch (b.type) {
      case 'indicator.ema': L.push(`float ${n} = talib.ema(${sourceName(p.source)}, ${p.length})`); break;
      case 'indicator.sma': L.push(`float ${n} = talib.sma(${sourceName(p.source)}, ${p.length})`); break;
      case 'indicator.rsi': L.push(`float ${n} = talib.rsi(${sourceName(p.source)}, ${p.length})`); break;
      case 'indicator.atr': L.push(`float ${n} = talib.atr(${p.length})`); break;
      case 'filter.session': {
        const ss = parseSession(p), tz = String(p.timezone || 'Etc/UTC').replace(/["\\\s]/g, '');
        L.push(`// ${b.id}: session ${p.session || '0000-2359'} in ${tz}, read from the bar's open time (check against your chart).`);
        L.push(`int ${n}_m = hour(time, "${tz}") * 60 + minute(time, "${tz}")`);
        L.push(`bool ${n} = ${ss.start <= ss.end ? `${n}_m >= ${ss.start} and ${n}_m < ${ss.end}` : `${n}_m >= ${ss.start} or ${n}_m < ${ss.end}`}`);
        break;
      }
      case 'signal.cross':
        L.push(`bool ${n} = ${p.direction === 'below' ? 'talib.crossunder' : 'talib.crossover'}(${ref(p.left)}, ${ref(p.right)})`);
        break;
      case 'signal.threshold':
        if (!Number.isFinite(Number(p.value))) throw new Error(`Invalid threshold in ${b.id}`);
        L.push(`bool ${n} = ${ref(p.left)} ${thresholdOp(p)} ${Number(p.value)}`);
        break;
      case 'signal.combine':
        L.push(`bool ${n} = ${(p.signals || []).length ? p.signals.map(x => bool(x)).join(p.mode === 'any' ? ' or ' : ' and ') : 'false'}`);
        break;
      case 'visual.plot': case 'alert.condition':
        break;
      default:
        L.push(isBoolType(b.type) ? `bool ${n} = false // TODO unsupported block ${b.type}: ${b.id}` : `float ${n} = na // TODO unsupported block ${b.type}: ${b.id}`);
    }
  }
  const plots = recipe.blocks.filter(b => b.type === 'visual.plot');
  if (plots.length) L.push('');
  plots.forEach((b, k) => L.push(`plot(${ref(b.params?.source)}, title = ${lipiText(b.params?.title || b.params?.source || b.id)}, color = color.rgb(${colors[k % colors.length]}), linewidth = 2)`));
  const alerts = recipe.blocks.filter(b => b.type === 'alert.condition');
  if (alerts.length) {
    L.push('');
    L.push('// Alerts: alertcondition offers a named condition in the GoCharting alert dialog; alert() fires on realtime bars only,');
    L.push('// at most once a bar. Testing the previous bar ([1]) makes it fire once per closed bar.');
    for (const a of alerts) {
      const w = bool(a.params?.when), msg = lipiText(a.params?.message || a.id);
      const down = signalDown(map, a.params?.when);
      L.push(`alertcondition(${w}, ${lipiText(a.id)}, ${msg})`);
      if (recipe.overlay) L.push(`plotshape(${w}, title = ${lipiText(a.id)}, shape = ${down ? 'shape.triangledown' : 'shape.triangleup'}, location = ${down ? 'location.abovebar' : 'location.belowbar'}, color = color.rgb(${down ? '220, 80, 80' : '50, 205, 50'}), size = size.tiny)`);
      L.push(`if ${/^[A-Za-z_][A-Za-z0-9_]*$/.test(w) ? w : '(' + w + ')'}[1] {`, `    alert(${msg})`, '}');
    }
  }
  L.push('');
  L.push('// End BSV generated starter.');
  return L.join('\n') + '\n';
}

function javaText(s) {
  return '"' + String(s ?? '').replace(/["\\\r\n]/g, ' ').trim() + '"';
}

function renderMotiveWave(recipe) {
  const map = blockMap(recipe);
  const cls = 'Bsv' + className(recipe);
  const plots = recipe.blocks.filter(b => b.type === 'visual.plot');
  const alerts = recipe.blocks.filter(b => b.type === 'alert.condition');
  const rsis = recipe.blocks.filter(b => b.type === 'indicator.rsi');
  const bi = { open: 'OPEN', high: 'HIGH', low: 'LOW', close: 'CLOSE', hl2: 'MIDPOINT', hlc3: 'TP', ohlc4: 'WP' };
  const px = { open: 'series.getOpen(i)', high: 'series.getHigh(i)', low: 'series.getLow(i)', close: 'series.getClose(i)', hl2: '(series.getHigh(i) + series.getLow(i)) / 2.0', hlc3: '(series.getHigh(i) + series.getLow(i) + series.getClose(i)) / 3.0', ohlc4: '(series.getOpen(i) + series.getHigh(i) + series.getLow(i) + series.getClose(i)) / 4.0' };
  const priceAt = (ref, at) => `P_${ref}(${at})`;
  const val = (ref, at) => isPrice(ref) ? priceAt(ref, at) : (isBoolType(map.get(ref)?.type) ? `(S_${ref}(${at}) ? 1.0 : 0.0)` : `V_${ref}(${at})`);
  const bool = (ref, at) => isBoolType(map.get(ref)?.type) ? `S_${ref}(${at})` : `(${val(ref, at)} != 0.0 && !Double.isNaN(${val(ref, at)}))`;
  const colors = ['30, 144, 255', '255, 165, 0', '50, 205, 50', '255, 0, 255', '0, 255, 255', '220, 80, 80'];
  const usedPrices = new Set();
  const scan = (ref) => { if (isPrice(ref)) usedPrices.add(ref); };
  for (const b of recipe.blocks) { const p = b.params || {}; [p.left, p.right, p.source].forEach(scan); }
  for (const b of rsis) usedPrices.add(sourceName(b.params?.source));
  const L = [];
  L.push('// ORIGINAL BSV STARTER — MotiveWave SDK custom study (Java). Build with the MotiveWave SDK before use.');
  L.push('// Generated by BSV Trader Tool Blocks. Not runtime tested by BSV. Not investment advice.');
  L.push(`// Save as ${cls}.java in an SDK project, build the jar and load it in MotiveWave (Extensions folder). No orders are placed.`);
  L.push('package com.botshelfvampire.generated;');
  L.push('');
  L.push('import java.awt.Color;');
  if (recipe.blocks.some(b => b.type === 'filter.session')) { L.push('import java.time.Instant;', 'import java.time.ZoneId;', 'import java.time.ZonedDateTime;'); }
  L.push('');
  L.push('import com.motivewave.platform.sdk.common.DataContext;');
  L.push('import com.motivewave.platform.sdk.common.DataSeries;');
  L.push('import com.motivewave.platform.sdk.common.Defaults;');
  L.push('import com.motivewave.platform.sdk.common.Enums;');
  L.push('import com.motivewave.platform.sdk.common.desc.PathDescriptor;');
  L.push('import com.motivewave.platform.sdk.study.Study;');
  L.push('import com.motivewave.platform.sdk.study.StudyHeader;');
  L.push('');
  L.push('@StudyHeader(');
  L.push('    namespace = "com.botshelfvampire.generated",');
  L.push(`    id = ${javaText(cls.toUpperCase())},`);
  L.push(`    name = ${javaText('BSV — ' + safeTitle(recipe))},`);
  L.push('    desc = "Original BSV generated starter. Not runtime tested by BSV.",');
  L.push('    menu = "BSV",');
  L.push(`    overlay = ${recipe.overlay ? 'true' : 'false'}${alerts.length ? ',' : ''}`);
  if (alerts.length) L.push('    signals = true');
  L.push(')');
  L.push(`public class ${cls} extends Study`);
  L.push('{');
  const vals = [...plots.map((_, k) => `PLOT${k}`), ...rsis.flatMap(b => [`U_${b.id}`, `D_${b.id}`])];
  L.push(`    enum Values { ${vals.length ? vals.join(', ') : 'NONE'} }`);
  if (alerts.length) L.push(`    enum Signals { ${alerts.map(a => 'A_' + a.id).join(', ')} }`);
  L.push(`    private static final int WARMUP = ${warmup(recipe)};`);
  L.push('    private DataSeries series;');
  L.push('');
  L.push('    @Override');
  L.push('    public void initialize(Defaults defaults)');
  L.push('    {');
  L.push('        var sd = createSD();');
  L.push('        var grp = sd.addTab("General").addGroup("Plots");');
  plots.forEach((p, k) => L.push(`        grp.addRow(new PathDescriptor("path${k}", ${javaText(p.params?.title || p.params?.source || p.id)}, new Color(${colors[k % colors.length]}), 1.5f, null, true, true, true));`));
  L.push('        var rd = createRD();');
  plots.forEach((p, k) => L.push(`        rd.declarePath(Values.PLOT${k}, "path${k}");`));
  if (plots.length) L.push(`        rd.setRangeKeys(${plots.map((_, k) => `Values.PLOT${k}`).join(', ')});`);
  for (const a of alerts) L.push(`        rd.declareSignal(Signals.A_${a.id}, ${javaText(a.params?.message || a.id)});`);
  L.push('    }');
  L.push('');
  L.push('    @Override');
  L.push('    protected void calculate(int index, DataContext ctx)');
  L.push('    {');
  L.push('        series = ctx.getDataSeries();');
  for (const b of rsis) {
    const s = sourceName(b.params?.source);
    L.push(`        if (index >= 1) { double ch = P_${s}(index) - P_${s}(index - 1); series.setDouble(index, Values.U_${b.id}, Math.max(ch, 0.0)); series.setDouble(index, Values.D_${b.id}, Math.max(-ch, 0.0)); }`);
  }
  L.push('        if (index < WARMUP)');
  L.push('            return;');
  plots.forEach((p, k) => L.push(`        { double v = ${val(p.params?.source, 'index')}; if (!Double.isNaN(v)) series.setDouble(index, Values.PLOT${k}, v); }`));
  L.push('        boolean closed = series.isBarComplete(index);');
  if (alerts.length) {
    L.push('        // Signals only on closed bars; MotiveWave raises each signal at most once per bar index.');
    for (const a of alerts) L.push(`        if (closed && ${bool(a.params?.when, 'index')})`, `            ctx.signal(index, Signals.A_${a.id}, ${javaText(a.params?.message || a.id)}, series.getClose(index));`);
  }
  L.push('        series.setComplete(index, closed);');
  L.push('    }');
  L.push('');
  L.push('    private static double d(Double v) { return v == null ? Double.NaN : v; }');
  for (const s of usedPrices) L.push(`    private double P_${s}(int i) { return ${px[s]}; }`);
  for (const b of recipe.blocks) {
    const p = b.params || {};
    switch (b.type) {
      case 'indicator.ema': L.push(`    private double V_${b.id}(int i) { return d(series.ema(i, ${p.length}, Enums.BarInput.${bi[sourceName(p.source)]})); }`); break;
      case 'indicator.sma': L.push(`    private double V_${b.id}(int i) { return d(series.sma(i, ${p.length}, Enums.BarInput.${bi[sourceName(p.source)]})); }`); break;
      case 'indicator.atr': L.push(`    private double V_${b.id}(int i) { return d(series.atr(i, ${p.length})); }`); break;
      case 'indicator.rsi':
        L.push(`    // ${b.id}: Wilder RSI from smoothed (SMMA) gains/losses stored per bar.`,
          `    private double V_${b.id}(int i) { double u = d(series.smma(i, ${p.length}, Values.U_${b.id})), dn = d(series.smma(i, ${p.length}, Values.D_${b.id})); if (Double.isNaN(u) || Double.isNaN(dn)) return Double.NaN; return dn == 0.0 ? 100.0 : 100.0 - 100.0 / (1.0 + u / dn); }`);
        break;
      case 'filter.session': {
        const ss = parseSession(p), tz = String(p.timezone || 'Etc/UTC').replace(/["\\\s]/g, '');
        L.push(`    // ${b.id}: session ${p.session || '0000-2359'} in ${tz}, read from the bar start time.`,
          `    private static final ZoneId TZ_${b.id} = ZoneId.of(${javaText(tz)});`,
          `    private boolean S_${b.id}(int i) { ZonedDateTime t = Instant.ofEpochMilli(series.getStartTime(i)).atZone(TZ_${b.id}); int m = t.getHour() * 60 + t.getMinute(); return ${ss.start <= ss.end ? `m >= ${ss.start} && m < ${ss.end}` : `m >= ${ss.start} || m < ${ss.end}`}; }`);
        break;
      }
      case 'signal.cross': {
        const [gt, le] = p.direction === 'below' ? ['<', '>='] : ['>', '<='];
        L.push(`    private boolean S_${b.id}(int i) { return i >= 1 && ${val(p.left, 'i')} ${gt} ${val(p.right, 'i')} && ${val(p.left, 'i - 1')} ${le} ${val(p.right, 'i - 1')}; }`);
        break;
      }
      case 'signal.threshold':
        if (!Number.isFinite(Number(p.value))) throw new Error(`Invalid threshold in ${b.id}`);
        L.push(`    private boolean S_${b.id}(int i) { return ${val(p.left, 'i')} ${thresholdOp(p)} ${Number(p.value)}; }`);
        break;
      case 'signal.combine':
        L.push(`    private boolean S_${b.id}(int i) { return ${(p.signals || []).map(x => bool(x, 'i')).join(p.mode === 'any' ? ' || ' : ' && ') || 'false'}; }`);
        break;
      case 'visual.plot': case 'alert.condition':
        break;
      default:
        if (isBoolType(b.type)) L.push(`    private boolean S_${b.id}(int i) { return false; } // TODO unsupported block ${b.type}: ${b.id}`);
        else L.push(`    private double V_${b.id}(int i) { return Double.NaN; } // TODO unsupported block ${b.type}: ${b.id}`);
    }
  }
  L.push('}');
  return L.join('\n') + '\n';
}

function renderVela(recipe) {
  const map = blockMap(recipe);
  const plots = recipe.blocks.filter(b => b.type === 'visual.plot');
  const alerts = recipe.blocks.filter(b => b.type === 'alert.condition');
  const nm = (r) => isPrice(r) ? `px.${r}` : `b_${r}`;
  const isB = (r) => !isPrice(r) && isBoolType(map.get(r)?.type);
  const num = (r) => isB(r) ? `toNum(${nm(r)})` : nm(r);
  const bool = (r) => isB(r) ? nm(r) : `toBool(${nm(r)})`;
  const colors = ['#1e90ff', '#ffa500', '#32cd32', '#ff00ff', '#00ffff', '#dc5050'];
  const L = [];
  L.push('// ORIGINAL BSV STARTER — Vela (LuxAlgo, Apache-2.0) chart with a small BSV recipe engine. Plain JavaScript, no Pine runtime.');
  L.push('// Generated by BSV Trader Tool Blocks. Not runtime tested by BSV. Not investment advice. No network requests, no orders.');
  L.push('// npm install @luxalgo/vela   then import this module from a page that has <div id="chart"></div> (see platforms/vela).');
  L.push("import { Vela } from '@luxalgo/vela';");
  L.push("import { stableSeriesId } from '@luxalgo/vela/plugin';");
  L.push('');
  L.push(`const TITLE = ${q('BSV — ' + safeTitle(recipe))};`);
  L.push(`const OVERLAY = ${recipe.overlay ? 'true' : 'false'};`);
  L.push('');
  L.push('// ---- helpers (Wilder RSI/ATR, SMA-seeded EMA; NaN until enough bars) ----');
  L.push('const toNum = (a) => a.map(x => (x ? 1 : 0));');
  L.push('const toBool = (a) => a.map(x => Number.isFinite(x) && x !== 0);');
  L.push('function sma(s, n) { const o = new Array(s.length).fill(NaN); let sum = 0, cnt = 0; for (let i = 0; i < s.length; i++) { sum += s[i]; cnt++; if (i >= n) { sum -= s[i - n]; cnt--; } if (cnt === n) o[i] = sum / n; } return o; }');
  L.push('function ema(s, n) { const o = new Array(s.length).fill(NaN), a = 2 / (n + 1); let p = NaN, sum = 0; for (let i = 0; i < s.length; i++) { if (i < n) { sum += s[i]; if (i === n - 1) p = sum / n; else continue; } else p = a * s[i] + (1 - a) * p; o[i] = p; } return o; }');
  L.push('function rma(s, n, from) { const o = new Array(s.length).fill(NaN); let p = NaN, sum = 0; for (let i = from; i < s.length; i++) { const k = i - from; if (k < n) { sum += s[i]; if (k === n - 1) p = sum / n; else continue; } else p = (p * (n - 1) + s[i]) / n; o[i] = p; } return o; }');
  L.push('function rsi(s, n) { const up = s.map((x, i) => (i ? Math.max(x - s[i - 1], 0) : 0)), dn = s.map((x, i) => (i ? Math.max(s[i - 1] - x, 0) : 0)); const u = rma(up, n, 1), d = rma(dn, n, 1); return u.map((x, i) => (Number.isNaN(x) ? NaN : d[i] === 0 ? 100 : 100 - 100 / (1 + x / d[i]))); }');
  L.push('function atr(bars, n) { const tr = bars.map((b, i) => (i ? Math.max(b.high - b.low, Math.abs(b.high - bars[i - 1].close), Math.abs(b.low - bars[i - 1].close)) : b.high - b.low)); return rma(tr, n, 0); }');
  L.push('function cross(a, b, up) { return a.map((x, i) => i > 0 && (up ? x > b[i] && a[i - 1] <= b[i - 1] : x < b[i] && a[i - 1] >= b[i - 1])); }');
  L.push('function minutesIn(tz) { const f = new Intl.DateTimeFormat(\'en-GB\', { timeZone: tz, hour: \'2-digit\', minute: \'2-digit\', hourCycle: \'h23\' }); return (t) => { const p = f.formatToParts(new Date(t)); return Number(p.find(x => x.type === \'hour\').value) * 60 + Number(p.find(x => x.type === \'minute\').value); }; }');
  L.push('');
  L.push('// ---- the recipe, compiled from its blocks ----');
  L.push('function compute(bars) {');
  L.push('  const px = { open: bars.map(b => b.open), high: bars.map(b => b.high), low: bars.map(b => b.low), close: bars.map(b => b.close) };');
  L.push('  px.hl2 = bars.map(b => (b.high + b.low) / 2); px.hlc3 = bars.map(b => (b.high + b.low + b.close) / 3); px.ohlc4 = bars.map(b => (b.open + b.high + b.low + b.close) / 4);');
  for (const b of depOrder(recipe)) {
    const p = b.params || {}, n = `b_${b.id}`;
    switch (b.type) {
      case 'indicator.ema': L.push(`  const ${n} = ema(px.${sourceName(p.source)}, ${p.length});`); break;
      case 'indicator.sma': L.push(`  const ${n} = sma(px.${sourceName(p.source)}, ${p.length});`); break;
      case 'indicator.rsi': L.push(`  const ${n} = rsi(px.${sourceName(p.source)}, ${p.length});`); break;
      case 'indicator.atr': L.push(`  const ${n} = atr(bars, ${p.length});`); break;
      case 'filter.session': {
        const ss = parseSession(p), tz = String(p.timezone || 'Etc/UTC').replace(/["\\\s']/g, '');
        L.push(`  // ${b.id}: session ${p.session || '0000-2359'} in ${tz}, read from each bar's open time.`);
        L.push(`  const m_${b.id} = minutesIn(${q(tz)});`);
        L.push(`  const ${n} = bars.map(x => { const m = m_${b.id}(x.time); return ${ss.start <= ss.end ? `m >= ${ss.start} && m < ${ss.end}` : `m >= ${ss.start} || m < ${ss.end}`}; });`);
        break;
      }
      case 'signal.cross': L.push(`  const ${n} = cross(${num(p.left)}, ${num(p.right)}, ${p.direction === 'below' ? 'false' : 'true'});`); break;
      case 'signal.threshold':
        if (!Number.isFinite(Number(p.value))) throw new Error(`Invalid threshold in ${b.id}`);
        L.push(`  const ${n} = ${num(p.left)}.map(x => x ${thresholdOp(p) === '==' ? '===' : thresholdOp(p) === '!=' ? '!==' : thresholdOp(p)} ${Number(p.value)});`);
        break;
      case 'signal.combine': {
        const sigs = (p.signals || []).map(bool);
        L.push(`  const ${n} = bars.map((_, i) => ${sigs.length ? sigs.map(s => `${s}[i]`).join(p.mode === 'any' ? ' || ' : ' && ') : 'false'});`);
        break;
      }
      case 'visual.plot': case 'alert.condition':
        break;
      default:
        L.push(isBoolType(b.type) ? `  const ${n} = bars.map(() => false); // TODO unsupported block ${b.type}: ${b.id}` : `  const ${n} = bars.map(() => NaN); // TODO unsupported block ${b.type}: ${b.id}`);
    }
  }
  L.push('  return {');
  L.push('    plots: [');
  plots.forEach((b, k) => L.push(`      { title: ${q(b.params?.title || b.params?.source || b.id)}, color: ${q(colors[k % colors.length])}, values: ${num(b.params?.source)} },`));
  L.push('    ],');
  L.push('    alerts: [');
  for (const a of alerts) {
    const down = signalDown(map, a.params?.when);
    L.push(`      { id: ${q(a.id)}, message: ${q(String(a.params?.message || a.id).replace(/[\r\n]/g, ' '))}, down: ${down ? 'true' : 'false'}, when: ${bool(a.params?.when)} },`);
  }
  L.push('    ]');
  L.push('  };');
  L.push('}');
  L.push('');
  L.push('// ---- a minimal ScriptingEngine (Vela engine port): static runs, no inputs, no network ----');
  L.push('export const bsvRecipeEngine = {');
  L.push("  language: 'bsv-recipe',");
  L.push('  capabilities: { streaming: false, visibleRange: false, inputs: false },');
  L.push("  async prepare(source, instanceId) { return { language: 'bsv-recipe', inputs: [], meta: { title: TITLE, overlay: OVERLAY }, reactsToViewport: false, token: { instanceId } }; },");
  L.push('  execute(req, handlers) {');
  L.push('    const id = req.prepared.token.instanceId; let stopped = false, armedAfter = null; const fired = new Set();');
  L.push('    const run = () => {');
  L.push('      if (stopped) return;');
  L.push('      try {');
  L.push('        const bars = req.getBars ? req.getBars() : req.bars; if (!bars.length) return;');
  L.push('        const r = compute(bars);');
  L.push("        const series = r.plots.map((p, k) => ({ id: stableSeriesId({ instanceId: id, kind: 'line', title: p.title, ordinal: k }), title: p.title, paneId: '', kind: 'line', points: bars.map((b, i) => ({ time: b.time, value: Number.isFinite(p.values[i]) ? p.values[i] : null })), style: { color: p.color, width: 2, lineStyle: 'solid' } }));");
  L.push("        const labels = [];");
  L.push("        if (OVERLAY) r.alerts.forEach((a) => { let k = 0; bars.forEach((b, i) => { if (!a.when[i]) return; labels.push({ id: stableSeriesId({ instanceId: id, kind: 'label', title: a.id, ordinal: k++ }), paneId: '', xloc: 'bar_time', x: b.time, y: a.down ? b.high : b.low, yloc: a.down ? 'abovebar' : 'belowbar', style: a.down ? 'triangledown' : 'triangleup', color: a.down ? '#dc5050' : '#32cd32', size: 'small', textAlign: 'center', fontFamily: 'default', tooltip: a.message }); }); });");
  L.push("        handlers.onModel({ id, title: TITLE, overlay: OVERLAY, paneHint: OVERLAY ? 'price' : 'new', series, labels, fills: [], backgrounds: [], priceLines: [], inputs: [], inputValues: {} });");
  L.push('        // Alerts: only for bars that close after the first run; the last bar may still be forming, so check the one before it.');
  L.push('        const last = bars.length - 1;');
  L.push('        if (armedAfter === null) armedAfter = bars[last].time;');
  L.push('        else if (last >= 1 && bars[last - 1].time >= armedAfter) for (const a of r.alerts) { const key = a.id + "@" + bars[last - 1].time; if (a.when[last - 1] && !fired.has(key)) { fired.add(key); handlers.onAlert && handlers.onAlert({ id: a.id, message: a.message, title: TITLE, time: bars[last - 1].time, barIndex: last - 1 }); } }');
  L.push('        handlers.onDone && handlers.onDone();');
  L.push('      } catch (e) { handlers.onError && handlers.onError(e); }');
  L.push('    };');
  L.push("    if (req.historyState !== 'backfill') Promise.resolve().then(run);");
  L.push("    return { stop() { stopped = true; }, update() { run(); }, setVisibleRange() {}, notifyBars(reason) { if (reason !== 'backfill') run(); } };");
  L.push('  }');
  L.push('};');
  L.push('');
  L.push('// ---- usage: replace sampleBars with your own OHLCV bars ({ time: epoch ms, open, high, low, close, volume }) ----');
  L.push('export function mountBsvChart(target, bars, timeframe = \'1h\') {');
  L.push("  const chart = new Vela(target, { data: bars, timeframe, theme: 'dark' });");
  L.push("  chart.registerEngine('bsv-recipe', bsvRecipeEngine);");
  L.push(`  const handle = chart.addIndicator(${q('bsv-recipe: ' + safeTitle(recipe))}, { language: 'bsv-recipe' });`);
  L.push("  handle.on('alert', (a) => console.log('[BSV alert]', new Date(a.time).toISOString(), a.message));");
  L.push("  handle.on('error', ({ error }) => console.error('[BSV]', error));");
  L.push('  return { chart, handle };');
  L.push('}');
  L.push('');
  L.push('// End BSV generated starter.');
  return L.join('\n') + '\n';
}

function signalDown(map, ref, seen = new Set()) {
  // true when the signal is (or combines) a downward cross: draw its marker above the bar.
  const b = map.get(ref);
  if (!b || seen.has(ref)) return false;
  seen.add(ref);
  if (b.type === 'signal.cross') return b.params?.direction === 'below';
  if (b.type === 'signal.combine') return (b.params?.signals || []).some(x => signalDown(map, x, seen));
  return false;
}

function depOrder(recipe) {
  // Dependency order for targets that need definitions before use (C++ lambdas). Falls back to recipe order on a loop.
  const map = blockMap(recipe), seen = new Map(), out = [];
  const visit = (b) => {
    const st = seen.get(b.id);
    if (st === 2) return true;
    if (st === 1) return false;
    seen.set(b.id, 1);
    for (const r of referencesFor(b)) { const d = map.get(r); if (d && !visit(d)) return false; }
    seen.set(b.id, 2); out.push(b); return true;
  };
  for (const b of recipe.blocks) if (!visit(b)) return recipe.blocks.slice();
  return out;
}

function renderSierra(recipe) {
  const map = blockMap(recipe);
  const fn = 'scsf_Bsv' + className(recipe);
  const plots = recipe.blocks.filter(b => b.type === 'visual.plot');
  const alerts = recipe.blocks.filter(b => b.type === 'alert.condition');
  const inds = recipe.blocks.filter(b => ['indicator.ema', 'indicator.sma', 'indicator.rsi', 'indicator.atr'].includes(b.type));
  if (plots.length + inds.length > 60) throw new Error('Sierra Chart supports up to 60 subgraphs per study');
  const base = { open: 'SC_OPEN', high: 'SC_HIGH', low: 'SC_LOW', close: 'SC_LAST' };
  const priceAt = (ref, at) => {
    const B = k => `sc.BaseDataIn[${base[k]}][${at}]`;
    if (base[ref]) return B(ref);
    if (ref === 'hl2') return `(${B('high')} + ${B('low')}) / 2.0f`;
    if (ref === 'hlc3') return `(${B('high')} + ${B('low')} + ${B('close')}) / 3.0f`;
    return `(${B('open')} + ${B('high')} + ${B('low')} + ${B('close')}) / 4.0f`;
  };
  const val = (ref, at) => isPrice(ref) ? priceAt(ref, at) : (isBoolType(map.get(ref)?.type) ? `(S_${ref}(${at}) ? 1.0f : 0.0f)` : `V_${ref}(${at})`);
  const bool = (ref, at) => isBoolType(map.get(ref)?.type) ? `S_${ref}(${at})` : `(${val(ref, at)} != 0.0f)`;
  const colors = ['RGB(30,144,255)', 'RGB(255,165,0)', 'RGB(50,205,50)', 'RGB(255,0,255)', 'RGB(255,215,0)', 'RGB(0,255,255)'];
  const sg = new Map();
  plots.forEach((p, k) => sg.set(p.id, k));
  inds.forEach((b, k) => sg.set(b.id, plots.length + k));
  const L = [];
  L.push('// ORIGINAL BSV STARTER — Sierra Chart ACSIL custom study (C++). Build with Analysis >> Build Custom Studies DLL before use.');
  L.push('// Generated by BSV Trader Tool Blocks. Not runtime tested by BSV. Not investment advice.');
  L.push(`// Save as ACS_Source\\Bsv${className(recipe)}.cpp, build the DLL, then add the study "${'BSV — ' + safeTitle(recipe)}" to a chart.`);
  L.push('#include "sierrachart.h"');
  L.push('');
  L.push(`SCDLLName(${q('BSV ' + safeTitle(recipe))})`);
  L.push('');
  L.push(`SCSFExport ${fn}(SCStudyInterfaceRef sc)`);
  L.push('{');
  for (const p of plots) L.push(`    SCSubgraphRef Sg_${p.id} = sc.Subgraph[${sg.get(p.id)}];`);
  for (const b of inds) L.push(`    SCSubgraphRef Sg_${b.id} = sc.Subgraph[${sg.get(b.id)}]; // calculation only (hidden)`);
  L.push(`    const int BSV_WARMUP = ${warmup(recipe)};`);
  L.push('');
  L.push('    if (sc.SetDefaults)');
  L.push('    {');
  L.push(`        sc.GraphName = ${q('BSV — ' + safeTitle(recipe))};`);
  L.push(`        sc.StudyDescription = ${q('Original BSV generated starter. Not runtime tested by BSV. Not investment advice.')};`);
  L.push('        sc.AutoLoop = 1;');
  L.push(`        sc.GraphRegion = ${recipe.overlay ? 0 : 1};`);
  plots.forEach((p, k) => {
    L.push(`        Sg_${p.id}.Name = ${q(p.params?.title || p.params?.source || p.id)};`);
    L.push(`        Sg_${p.id}.DrawStyle = DRAWSTYLE_LINE;`);
    L.push(`        Sg_${p.id}.PrimaryColor = ${colors[k % colors.length]};`);
  });
  for (const b of inds) { L.push(`        Sg_${b.id}.Name = ${q(b.id)};`); L.push(`        Sg_${b.id}.DrawStyle = DRAWSTYLE_IGNORE;`); }
  L.push('        return;');
  L.push('    }');
  L.push('');
  L.push('    // Built-in calculations run on every bar (automatic looping).');
  for (const b of inds) {
    const p = b.params || {};
    const src = b.type === 'indicator.atr' ? null : sourceName(p.source);
    let input = src && base[src] ? `sc.BaseDataIn[${base[src]}]` : null;
    if (src && !base[src]) {
      L.push(`    Sg_${b.id}.Arrays[9][sc.Index] = ${priceAt(src, 'sc.Index')}; // ${src} source`);
      input = `Sg_${b.id}.Arrays[9]`;
    }
    if (b.type === 'indicator.ema') L.push(`    sc.ExponentialMovAvg(${input}, Sg_${b.id}, ${p.length});`);
    if (b.type === 'indicator.sma') L.push(`    sc.SimpleMovAvg(${input}, Sg_${b.id}, ${p.length});`);
    if (b.type === 'indicator.rsi') L.push(`    sc.RSI(${input}, Sg_${b.id}, MOVAVGTYPE_WILDERS, ${p.length});`);
    if (b.type === 'indicator.atr') L.push(`    sc.ATR(sc.BaseDataIn, Sg_${b.id}, ${p.length}, MOVAVGTYPE_WILDERS);`);
  }
  L.push('');
  L.push('    // Block values and signals by absolute bar index (i). Defined in dependency order.');
  for (const b of depOrder(recipe)) {
    const p = b.params || {};
    switch (b.type) {
      case 'indicator.ema': case 'indicator.sma': case 'indicator.rsi': case 'indicator.atr':
        L.push(`    auto V_${b.id} = [&](int i) -> float { return Sg_${b.id}[i]; };`);
        break;
      case 'filter.session': {
        const ss = parseSession(p);
        L.push(`    // TODO ${b.id}: bar times use the chart time zone (Global Settings or chart setting); convert session ${p.session || ''} from ${p.timezone || 'Etc/UTC'}.`);
        L.push(`    auto S_${b.id} = [&](int i) -> bool { int m = sc.BaseDateTimeIn[i].GetTimeInSeconds() / 60; return ${ss.start <= ss.end ? `m >= ${ss.start} && m < ${ss.end}` : `m >= ${ss.start} || m < ${ss.end}`}; };`);
        break;
      }
      case 'signal.cross': {
        const [gt, le] = p.direction === 'below' ? ['<', '>='] : ['>', '<='];
        L.push(`    auto S_${b.id} = [&](int i) -> bool { return ${val(p.left, 'i')} ${gt} ${val(p.right, 'i')} && ${val(p.left, 'i - 1')} ${le} ${val(p.right, 'i - 1')}; };`);
        break;
      }
      case 'signal.threshold':
        if (!Number.isFinite(Number(p.value))) throw new Error(`Invalid threshold in ${b.id}`);
        L.push(`    auto S_${b.id} = [&](int i) -> bool { return ${val(p.left, 'i')} ${thresholdOp(p)} ${Number(p.value)}; };`);
        break;
      case 'signal.combine':
        L.push(`    auto S_${b.id} = [&](int i) -> bool { return ${(p.signals || []).map(x => bool(x, 'i')).join(p.mode === 'any' ? ' || ' : ' && ') || 'false'}; };`);
        break;
      case 'visual.plot': case 'alert.condition':
        break;
      default:
        if (isBoolType(b.type)) L.push(`    auto S_${b.id} = [&](int i) -> bool { return false; }; // TODO unsupported block ${b.type}: ${b.id}`);
        else L.push(`    auto V_${b.id} = [&](int i) -> float { return 0.0f; }; // TODO unsupported block ${b.type}: ${b.id}`);
    }
  }
  L.push('');
  L.push('    if (sc.Index < BSV_WARMUP) return;');
  for (const p of plots) L.push(`    Sg_${p.id}[sc.Index] = ${val(p.params?.source, 'sc.Index')};`);
  if (alerts.length) {
    L.push('');
    L.push('    // Alerts: evaluate the last closed bar once, only on the newest bar and not during a full recalculation.');
    L.push('    if (sc.Index == sc.ArraySize - 1 && !sc.IsFullRecalculation)');
    L.push('    {');
    L.push('        const int c = sc.Index - 1;');
    alerts.forEach((a, k) => {
      L.push(`        int& last_${a.id} = sc.GetPersistentInt(${k + 1});`);
      L.push(`        if (c > BSV_WARMUP && last_${a.id} != c && ${bool(a.params?.when, 'c')}) { last_${a.id} = c; sc.AddAlertLine(${q(String(a.params?.message || a.id).replace(/[\r\n]/g, ' '))}, 0); }`);
    });
    L.push('    }');
  }
  L.push('}');
  L.push('');
  L.push('// Build the DLL, resolve every marked item above, then test on history and in replay or simulation before relying on it.');
  return L.join('\n') + '\n';
}

function prtName(id, used) {
  let n = 'v' + id.split('_').map(x => x.charAt(0).toUpperCase() + x.slice(1)).join('').replace(/[^A-Za-z0-9]/g, '');
  while (used.has(n.toLowerCase())) n += 'X';
  used.add(n.toLowerCase());
  return n;
}

function renderProRealTime(recipe) {
  const map = blockMap(recipe);
  const used = new Set();
  const nm = new Map(recipe.blocks.map(b => [b.id, prtName(b.id, used)]));
  const plots = recipe.blocks.filter(b => b.type === 'visual.plot');
  const alerts = recipe.blocks.filter(b => b.type === 'alert.condition');
  const price = { open: 'Open', high: 'High', low: 'Low', close: 'Close', hl2: '((High + Low) / 2)', hlc3: '((High + Low + Close) / 3)', ohlc4: '((Open + High + Low + Close) / 4)' };
  const ref = (r) => isPrice(r) ? price[r] : nm.get(r);
  const bool = (r) => isBoolType(map.get(r)?.type) ? nm.get(r) : `(${ref(r)} <> 0)`;
  const colors = ['30,144,255', '255,165,0', '50,205,50', '255,0,255', '255,215,0', '0,255,255'];
  const L = [];
  L.push('// ORIGINAL BSV STARTER — ProRealTime ProBuilder indicator. Paste into a new indicator (Indicators >> New >> Creation by programming) and validate.');
  L.push('// Generated by BSV Trader Tool Blocks. Not runtime tested by BSV. Not investment advice.');
  L.push(`// ${safeTitle(recipe)} — add it ${recipe.overlay ? 'on the price chart' : 'below the price chart'}.`);
  L.push('// Block variables use names without underscores (block id -> name):');
  for (const b of recipe.blocks) L.push(`//   ${b.id} -> ${nm.get(b.id)}`);
  L.push('');
  for (const b of depOrder(recipe)) {
    const p = b.params || {}, n = nm.get(b.id);
    switch (b.type) {
      case 'indicator.ema': L.push(`${n} = ExponentialAverage[${p.length}](${price[sourceName(p.source)]})`); break;
      case 'indicator.sma': L.push(`${n} = Average[${p.length}](${price[sourceName(p.source)]})`); break;
      case 'indicator.rsi': L.push(`${n} = RSI[${p.length}](${price[sourceName(p.source)]})`); break;
      case 'indicator.atr': L.push(`${n} = AverageTrueRange[${p.length}](Close)`); break;
      case 'filter.session': {
        const ss = parseSession(p);
        const hhmmss = m => String(Math.floor(m / 60)).padStart(2, '0') + String(m % 60).padStart(2, '0') + '00';
        L.push(`// TODO ${b.id}: Time is the bar time in the platform time zone; convert session ${p.session || ''} from ${p.timezone || 'Etc/UTC'} and check bar open vs close time.`);
        L.push(`${n} = ${ss.start <= ss.end ? `(Time >= ${hhmmss(ss.start)} AND Time < ${hhmmss(ss.end)})` : `(Time >= ${hhmmss(ss.start)} OR Time < ${hhmmss(ss.end)})`}`);
        break;
      }
      case 'signal.cross':
        L.push(`${n} = (${ref(p.left)} CROSSES ${p.direction === 'below' ? 'UNDER' : 'OVER'} ${ref(p.right)})`);
        break;
      case 'signal.threshold': {
        if (!Number.isFinite(Number(p.value))) throw new Error(`Invalid threshold in ${b.id}`);
        const op = { '==': '=', '!=': '<>' }[thresholdOp(p)] || thresholdOp(p);
        L.push(`${n} = (${ref(p.left)} ${op} ${Number(p.value)})`);
        break;
      }
      case 'signal.combine':
        L.push(`${n} = ${(p.signals || []).length ? '(' + p.signals.map(bool).join(p.mode === 'any' ? ' OR ' : ' AND ') + ')' : '0'}`);
        break;
      case 'visual.plot': case 'alert.condition':
        break;
      default:
        L.push(`${n} = 0 // TODO unsupported block ${b.type}: ${b.id}`);
    }
  }
  const outs = [];
  plots.forEach((p, k) => outs.push(`${ref(p.params?.source)} COLOURED(${colors[k % colors.length]}) AS ${q(p.params?.title || p.params?.source || p.id)}`));
  if (alerts.length) {
    L.push('');
    L.push('// Alerts: ProBuilder indicators cannot raise alerts themselves; you create the alert in ProRealTime on an indicator line.');
    for (const a of alerts) {
      const n = nm.get(a.id), msg = String(a.params?.message || a.id).replace(/[\r\n]/g, ' ');
      L.push(`${n} = ${bool(a.params?.when)} // ${msg}`);
      if (recipe.overlay) {
        const down = signalDown(map, a.params?.when);
        L.push(`IF ${n} THEN`, down ? `  DRAWARROWDOWN(barindex, High) COLOURED(220,80,80)` : `  DRAWARROWUP(barindex, Low) COLOURED(50,205,50)`, 'ENDIF');
      } else {
        outs.push(`${n} AS ${q('Alert: ' + msg.replace(/"/g, ' ').slice(0, 60))}`);
      }
    }
    if (recipe.overlay) L.push(`// TODO alerts: this overlay only draws markers. For an alert, create a second indicator below the chart that returns ${alerts.map(a => nm.get(a.id)).join(', ')} (0/1) and set the alert on value 1.`);
    else L.push('// Set each alert on its 0/1 line (value = 1). Lines update with the live bar; prefer bar-close alert options where available.');
  }
  L.push('');
  L.push('RETURN ' + (outs.length ? outs.join(', ') : '0 AS "no output"'));
  return L.join('\n') + '\n';
}
