#!/usr/bin/env node
import fs from 'node:fs';

const args = process.argv.slice(2);
const recipePath = args[0];
const targetIndex = args.indexOf('--target');
const target = targetIndex >= 0 ? args[targetIndex + 1] : 'pine-v6';

if (!recipePath) {
  console.error('Usage: node render.mjs <recipe.json> --target pine-v6|mql5|ctrader|mql4|ctrader-python|bookmap-python');
  process.exit(1);
}

const recipe = JSON.parse(fs.readFileSync(recipePath, 'utf8'));
validateRecipe(recipe);

const renderers = {
  'pine-v6': renderPine,
  'mql5': renderMql5,
  'ctrader': renderCTrader,
  'mql4': renderMql4,
  'ctrader-python': renderCTraderPython,
  'bookmap-python': renderBookmapPython
};

if (!renderers[target]) {
  throw new Error(`Unsupported target: ${target}`);
}

process.stdout.write(renderers[target](recipe));

function validateRecipe(recipe) {
  if (recipe?.schemaVersion !== '0.1') throw new Error('schemaVersion must be 0.1');
  if (!recipe?.name || !Array.isArray(recipe?.blocks)) throw new Error('name and blocks are required');

  const ids = new Set();
  for (const block of recipe.blocks) {
    if (!/^[a-z][a-z0-9_]*$/.test(block.id || '')) throw new Error(`Invalid block id: ${block.id}`);
    if (ids.has(block.id)) throw new Error(`Duplicate block id: ${block.id}`);
    ids.add(block.id);
    if (!block.type || typeof block.params !== 'object') throw new Error(`Invalid block: ${block.id}`);
  }

  for (const block of recipe.blocks) {
    const p = block.params;
    for (const ref of referencesFor(block)) {
      if (!ids.has(ref) && !['open','high','low','close','hl2','hlc3','ohlc4'].includes(ref)) {
        throw new Error(`Block ${block.id} references missing id: ${ref}`);
      }
    }
    if (['indicator.ema','indicator.sma','indicator.rsi','indicator.atr'].includes(block.type)) {
      if (!Number.isInteger(p.length) || p.length < 1 || p.length > 10000) {
        throw new Error(`Block ${block.id} has invalid length`);
      }
    }
  }
}

function referencesFor(block) {
  const p = block.params || {};
  switch (block.type) {
    case 'signal.cross': return [p.left, p.right].filter(Boolean);
    case 'signal.threshold': return [p.left].filter(Boolean);
    case 'signal.combine': return Array.isArray(p.signals) ? p.signals : [];
    case 'visual.plot': return [p.source].filter(Boolean);
    case 'alert.condition': return [p.when].filter(Boolean);
    default: return [];
  }
}

function sourceName(v = 'close') {
  const allowed = new Set(['open','high','low','close','hl2','hlc3','ohlc4']);
  if (!allowed.has(v)) throw new Error(`Unsupported price source: ${v}`);
  return v;
}

function q(s) {
  return JSON.stringify(String(s ?? ''));
}

function safeTitle(recipe) {
  return String(recipe.name).replace(/["\r\n]/g, ' ').trim();
}

function className(recipe) {
  const c = safeTitle(recipe).replace(/[^A-Za-z0-9]+/g, ' ').trim()
    .split(/\s+/).map(x => x.charAt(0).toUpperCase() + x.slice(1)).join('');
  return (c || 'BSVCustomTool').replace(/^[0-9]/, 'BSV$&');
}

function blockMap(recipe) {
  return new Map(recipe.blocks.map(b => [b.id, b]));
}

function renderPine(recipe) {
  const lines = [];
  const map = blockMap(recipe);

  lines.push('//@version=6');
  lines.push(`indicator(${q('BSV — ' + safeTitle(recipe))}, overlay=${recipe.overlay ? 'true' : 'false'})`);
  lines.push('');
  lines.push('// Generated by BSV Trader Tool Blocks.');
  lines.push('// Structural starter only: compile and inspect on your TradingView version before relying on it.');
  lines.push('');

  for (const b of recipe.blocks) {
    const p = b.params || {};
    switch (b.type) {
      case 'indicator.ema':
        lines.push(`${b.id} = ta.ema(${sourceName(p.source)}, ${p.length})`);
        break;
      case 'indicator.sma':
        lines.push(`${b.id} = ta.sma(${sourceName(p.source)}, ${p.length})`);
        break;
      case 'indicator.rsi':
        lines.push(`${b.id} = ta.rsi(${sourceName(p.source)}, ${p.length})`);
        break;
      case 'indicator.atr':
        lines.push(`${b.id} = ta.atr(${p.length})`);
        break;
      case 'filter.session': {
        const session = String(p.session || '0000-2359');
        const tz = String(p.timezone || 'Etc/UTC');
        lines.push(`${b.id} = not na(time(timeframe.period, ${q(session)}, ${q(tz)}))`);
        break;
      }
      case 'signal.cross':
        lines.push(`${b.id} = ${p.direction === 'below' ? 'ta.crossunder' : 'ta.crossover'}(${p.left}, ${p.right})`);
        break;
      case 'signal.threshold': {
        const op = ['>','>=','<','<=','==','!='].includes(p.op) ? p.op : '>=';
        if (!Number.isFinite(Number(p.value))) throw new Error(`Invalid threshold in ${b.id}`);
        lines.push(`${b.id} = ${p.left} ${op} ${Number(p.value)}`);
        break;
      }
      case 'signal.combine': {
        const op = p.mode === 'any' ? ' or ' : ' and ';
        lines.push(`${b.id} = ${(p.signals || []).map(x => '(' + x + ')').join(op) || 'false'}`);
        break;
      }
      case 'visual.plot':
        lines.push(`plot(${p.source}, title=${q(p.title || p.source)})`);
        break;
      case 'alert.condition':
        lines.push(`alertcondition(${p.when}, title=${q(b.id)}, message=${q(p.message || b.id)})`);
        break;
      default:
        lines.push(`// TODO unsupported block ${b.type}: ${b.id}`);
    }
  }

  lines.push('');
  lines.push('// End BSV generated starter.');
  return lines.join('\n') + '\n';
}

function renderMql5(recipe) {
  const map = blockMap(recipe);
  const plots = recipe.blocks.filter(b => b.type === 'visual.plot');
  const alerts = recipe.blocks.filter(b => b.type === 'alert.condition');
  const inds = recipe.blocks.filter(b => ['indicator.ema', 'indicator.sma', 'indicator.rsi', 'indicator.atr'].includes(b.type));
  const appliedPrice = { open: 'PRICE_OPEN', high: 'PRICE_HIGH', low: 'PRICE_LOW', close: 'PRICE_CLOSE', hl2: 'PRICE_MEDIAN', hlc3: 'PRICE_TYPICAL' };
  const S = '_Symbol, _Period';
  const priceExpr = { open: `iOpen(${S}, i)`, high: `iHigh(${S}, i)`, low: `iLow(${S}, i)`, close: `iClose(${S}, i)`,
    hl2: `(iHigh(${S}, i) + iLow(${S}, i)) / 2.0`, hlc3: `(iHigh(${S}, i) + iLow(${S}, i) + iClose(${S}, i)) / 3.0`,
    ohlc4: `(iOpen(${S}, i) + iHigh(${S}, i) + iLow(${S}, i) + iClose(${S}, i)) / 4.0` };
  const val = (ref, at) => isPrice(ref) ? priceExpr[ref].replace(/, i\)/g, `, ${at})`) : (isBoolType(map.get(ref)?.type) ? `(S_${ref}(${at}) ? 1.0 : 0.0)` : `V_${ref}(${at})`);
  const bool = (ref, at) => isBoolType(map.get(ref)?.type) ? `S_${ref}(${at})` : `(${val(ref, at)} != 0.0 && ${val(ref, at)} != EMPTY_VALUE)`;
  const colors = ['clrDodgerBlue', 'clrOrange', 'clrLimeGreen', 'clrMagenta', 'clrGold', 'clrAqua'];
  const L = [];
  L.push('// ORIGINAL BSV STARTER — MT5 / MQL5 custom indicator. Compile in MetaEditor (MT5) before use.');
  L.push('// Generated by BSV Trader Tool Blocks. Not runtime tested by BSV. Not investment advice.');
  L.push(recipe.overlay ? '#property indicator_chart_window' : '#property indicator_separate_window');
  L.push(`#property indicator_buffers ${plots.length}`);
  L.push(`#property indicator_plots   ${plots.length}`);
  plots.forEach((p, k) => {
    L.push(`#property indicator_type${k + 1}   DRAW_LINE`);
    L.push(`#property indicator_color${k + 1}  ${colors[k % colors.length]}`);
    L.push(`#property indicator_label${k + 1}  ${q(String(p.params?.title || p.params?.source || p.id).replace(/[\r\n]/g, ' '))}`);
  });
  L.push('');
  for (const p of plots) L.push(`double Buf_${p.id}[];`);
  for (const b of inds) L.push(`int    h_${b.id} = INVALID_HANDLE;`, `double A_${b.id}[];`);
  for (const a of alerts) L.push(`datetime g_alert_${a.id} = 0;`);
  L.push(`#define BSV_WARMUP ${warmup(recipe)}`);
  L.push('');
  for (const b of recipe.blocks) {
    const p = b.params || {};
    switch (b.type) {
      case 'indicator.ema': case 'indicator.sma': case 'indicator.rsi': case 'indicator.atr':
        L.push(`double V_${b.id}(int i) { return A_${b.id}[i]; }`);
        break;
      case 'filter.session': {
        const ss = parseSession(p);
        L.push(`// TODO ${b.id}: session ${p.session || ''} is evaluated in broker server time; convert from ${p.timezone || 'Etc/UTC'} for your broker.`);
        L.push(`bool S_${b.id}(int i) { MqlDateTime t; TimeToStruct(iTime(${S}, i), t); int m = t.hour * 60 + t.min; return ${ss.start <= ss.end ? `m >= ${ss.start} && m < ${ss.end}` : `m >= ${ss.start} || m < ${ss.end}`}; }`);
        break;
      }
      case 'signal.cross': {
        const [gt, le] = p.direction === 'below' ? ['<', '>='] : ['>', '<='];
        L.push(`bool S_${b.id}(int i) { return ${val(p.left, 'i')} ${gt} ${val(p.right, 'i')} && ${val(p.left, 'i+1')} ${le} ${val(p.right, 'i+1')}; }`);
        break;
      }
      case 'signal.threshold':
        if (!Number.isFinite(Number(p.value))) throw new Error(`Invalid threshold in ${b.id}`);
        L.push(`bool S_${b.id}(int i) { return ${val(p.left, 'i')} ${thresholdOp(p)} ${Number(p.value)}; }`);
        break;
      case 'signal.combine':
        L.push(`bool S_${b.id}(int i) { return ${(p.signals || []).map(x => bool(x, 'i')).join(p.mode === 'any' ? ' || ' : ' && ') || 'false'}; }`);
        break;
      case 'visual.plot': case 'alert.condition':
        break;
      default:
        if (isBoolType(b.type)) L.push(`bool S_${b.id}(int i) { return false; } // TODO unsupported block ${b.type}: ${b.id}`);
        else L.push(`double V_${b.id}(int i) { return EMPTY_VALUE; } // TODO unsupported block ${b.type}: ${b.id}`);
    }
  }
  L.push('');
  L.push('int OnInit()');
  L.push('{');
  plots.forEach((p, k) => { L.push(`   SetIndexBuffer(${k}, Buf_${p.id}, INDICATOR_DATA);`); L.push(`   ArraySetAsSeries(Buf_${p.id}, true);`); });
  for (const b of inds) {
    const p = b.params || {};
    const src = b.type === 'indicator.atr' ? 'close' : sourceName(p.source);
    const ap = appliedPrice[src] || 'PRICE_CLOSE';
    const note = (b.type !== 'indicator.atr' && !appliedPrice[src]) ? ' // TODO ohlc4 has no MQL5 applied price; using close' : '';
    if (b.type === 'indicator.ema') L.push(`   h_${b.id} = iMA(${S}, ${p.length}, 0, MODE_EMA, ${ap});${note}`);
    if (b.type === 'indicator.sma') L.push(`   h_${b.id} = iMA(${S}, ${p.length}, 0, MODE_SMA, ${ap});${note}`);
    if (b.type === 'indicator.rsi') L.push(`   h_${b.id} = iRSI(${S}, ${p.length}, ${ap});${note}`);
    if (b.type === 'indicator.atr') L.push(`   h_${b.id} = iATR(${S}, ${p.length});`);
    L.push(`   if (h_${b.id} == INVALID_HANDLE) return(INIT_FAILED);`);
    L.push(`   ArraySetAsSeries(A_${b.id}, true);`);
  }
  L.push(`   IndicatorSetString(INDICATOR_SHORTNAME, ${q('BSV — ' + safeTitle(recipe))});`);
  L.push('   return(INIT_SUCCEEDED);');
  L.push('}');
  L.push('');
  L.push('void OnDeinit(const int reason)');
  L.push('{');
  for (const b of inds) L.push(`   if (h_${b.id} != INVALID_HANDLE) IndicatorRelease(h_${b.id});`);
  L.push('}');
  L.push('');
  L.push('int OnCalculate(const int rates_total, const int prev_calculated,');
  L.push('                const datetime &time[], const double &open[], const double &high[],');
  L.push('                const double &low[], const double &close[], const long &tick_volume[],');
  L.push('                const long &volume[], const int &spread[])');
  L.push('{');
  L.push('   if (rates_total <= BSV_WARMUP) return(0);');
  L.push('   // Series indexing (0 = newest bar), the same as the MQL4 target.');
  L.push('   int limit = rates_total - prev_calculated;');
  L.push('   if (prev_calculated > 0) limit++;');
  L.push('   if (limit > rates_total - BSV_WARMUP) limit = rates_total - BSV_WARMUP;');
  L.push('   int need = MathMin(rates_total, MathMax(limit + 2, 3));');
  for (const b of inds) L.push(`   if (CopyBuffer(h_${b.id}, 0, 0, need, A_${b.id}) < need) return(0); // data not ready yet`);
  L.push('   for (int i = limit - 1; i >= 0; i--)');
  L.push('   {');
  for (const p of plots) L.push(`      Buf_${p.id}[i] = ${val(p.params?.source, 'i')};`);
  L.push('   }');
  for (const a of alerts) {
    L.push(`   // ${a.id}: alert once per closed bar.`);
    L.push(`   if (${bool(a.params?.when, '1')} && g_alert_${a.id} != iTime(${S}, 1)) { g_alert_${a.id} = iTime(${S}, 1); Alert(${q(String(a.params?.message || a.id).replace(/[\r\n]/g, ' '))}); }`);
  }
  L.push('   return(rates_total);');
  L.push('}');
  L.push('');
  L.push('// Compile in MetaEditor, check every TODO, then test on history and a demo account before relying on it.');
  return L.join('\n') + '\n';
}

function renderCTrader(recipe) {
  const map = blockMap(recipe);
  const cls = className(recipe);
  const plots = recipe.blocks.filter(b => b.type === 'visual.plot');
  const alerts = recipe.blocks.filter(b => b.type === 'alert.condition');
  const inds = recipe.blocks.filter(b => ['indicator.ema', 'indicator.sma', 'indicator.rsi', 'indicator.atr'].includes(b.type));
  const series = { open: 'Bars.OpenPrices', high: 'Bars.HighPrices', low: 'Bars.LowPrices', close: 'Bars.ClosePrices', hl2: 'Bars.MedianPrices', hlc3: 'Bars.TypicalPrices' };
  const priceAt = (ref, at) => ref === 'ohlc4' ? `(Bars.OpenPrices[${at}] + Bars.HighPrices[${at}] + Bars.LowPrices[${at}] + Bars.ClosePrices[${at}]) / 4.0` : `${series[ref]}[${at}]`;
  const val = (ref, at) => isPrice(ref) ? priceAt(ref, at) : (isBoolType(map.get(ref)?.type) ? `(S_${ref}(${at}) ? 1.0 : 0.0)` : `V_${ref}(${at})`);
  const bool = (ref, at) => isBoolType(map.get(ref)?.type) ? `S_${ref}(${at})` : `(${val(ref, at)} != 0.0 && !double.IsNaN(${val(ref, at)}))`;
  const L = [];
  L.push('// ORIGINAL BSV STARTER — cTrader Algo (C#) custom indicator. Build in cTrader before use.');
  L.push('// Generated by BSV Trader Tool Blocks. Not runtime tested by BSV. Not investment advice.');
  L.push('using System;');
  L.push('using cAlgo.API;');
  L.push('using cAlgo.API.Indicators;');
  L.push('');
  L.push('namespace cAlgo');
  L.push('{');
  L.push(`    [Indicator(IsOverlay = ${recipe.overlay ? 'true' : 'false'}, TimeZone = TimeZones.UTC, AccessRights = AccessRights.None)]`);
  L.push(`    public class ${cls} : Indicator`);
  L.push('    {');
  L.push(`        private const int Warmup = ${warmup(recipe)};`);
  for (const b of inds) {
    const t = { 'indicator.ema': 'ExponentialMovingAverage', 'indicator.sma': 'SimpleMovingAverage', 'indicator.rsi': 'RelativeStrengthIndex', 'indicator.atr': 'AverageTrueRange' }[b.type];
    L.push(`        private ${t} _${b.id};`);
  }
  for (const a of alerts) L.push(`        private int _alert_${a.id} = -1;`);
  for (const p of plots) {
    L.push('');
    L.push(`        [Output(${q(String(p.params?.title || p.id).replace(/"/g, ''))})]`);
    L.push(`        public IndicatorDataSeries Out_${p.id} { get; set; }`);
  }
  L.push('');
  L.push('        protected override void Initialize()');
  L.push('        {');
  for (const b of inds) {
    const p = b.params || {};
    const src = () => series[sourceName(p.source)] || 'Bars.ClosePrices';
    const note = () => sourceName(p.source) === 'ohlc4' ? ' // TODO ohlc4 has no built-in series; using close' : '';
    if (b.type === 'indicator.ema') L.push(`            _${b.id} = Indicators.ExponentialMovingAverage(${src()}, ${p.length});${note()}`);
    if (b.type === 'indicator.sma') L.push(`            _${b.id} = Indicators.SimpleMovingAverage(${src()}, ${p.length});${note()}`);
    if (b.type === 'indicator.rsi') L.push(`            _${b.id} = Indicators.RelativeStrengthIndex(${src()}, ${p.length});${note()}`);
    if (b.type === 'indicator.atr') L.push(`            _${b.id} = Indicators.AverageTrueRange(${p.length}, MovingAverageType.WilderSmoothing);`);
  }
  L.push('        }');
  L.push('');
  L.push('        public override void Calculate(int index)');
  L.push('        {');
  L.push('            if (index < Warmup)');
  L.push('                return;');
  for (const p of plots) L.push(`            Out_${p.id}[index] = ${val(p.params?.source, 'index')};`);
  if (alerts.length) {
    L.push('            if (!IsLastBar)');
    L.push('                return;');
    L.push('            int i = index - 1; // last closed bar');
    for (const a of alerts) {
      L.push(`            if (${bool(a.params?.when, 'i')} && _alert_${a.id} != i)`);
      L.push('            {');
      L.push(`                _alert_${a.id} = i;`);
      L.push(`                Print(${q(String(a.params?.message || a.id).replace(/[\r\n]/g, ' '))}); // swap for Notifications if you want sound/email; no auto-trading`);
      L.push('            }');
    }
  }
  L.push('        }');
  for (const b of recipe.blocks) {
    const p = b.params || {};
    switch (b.type) {
      case 'indicator.ema': case 'indicator.sma': case 'indicator.rsi': case 'indicator.atr':
        L.push('', `        private double V_${b.id}(int i) { return _${b.id}.Result[i]; }`);
        break;
      case 'filter.session': {
        const ss = parseSession(p);
        L.push('', `        // TODO ${b.id}: bar times are UTC (see TimeZone attribute); convert session ${p.session || ''} from ${p.timezone || 'Etc/UTC'}.`,
          `        private bool S_${b.id}(int i) { var t = Bars.OpenTimes[i]; int m = t.Hour * 60 + t.Minute; return ${ss.start <= ss.end ? `m >= ${ss.start} && m < ${ss.end}` : `m >= ${ss.start} || m < ${ss.end}`}; }`);
        break;
      }
      case 'signal.cross': {
        const [gt, le] = p.direction === 'below' ? ['<', '>='] : ['>', '<='];
        L.push('', `        private bool S_${b.id}(int i) { return ${val(p.left, 'i')} ${gt} ${val(p.right, 'i')} && ${val(p.left, 'i - 1')} ${le} ${val(p.right, 'i - 1')}; }`);
        break;
      }
      case 'signal.threshold':
        if (!Number.isFinite(Number(p.value))) throw new Error(`Invalid threshold in ${b.id}`);
        L.push('', `        private bool S_${b.id}(int i) { return ${val(p.left, 'i')} ${thresholdOp(p)} ${Number(p.value)}; }`);
        break;
      case 'signal.combine':
        L.push('', `        private bool S_${b.id}(int i) { return ${(p.signals || []).map(x => bool(x, 'i')).join(p.mode === 'any' ? ' || ' : ' && ') || 'false'}; }`);
        break;
      case 'visual.plot': case 'alert.condition':
        break;
      default:
        if (isBoolType(b.type)) L.push('', `        private bool S_${b.id}(int i) { return false; } // TODO unsupported block ${b.type}: ${b.id}`);
        else L.push('', `        private double V_${b.id}(int i) { return double.NaN; } // TODO unsupported block ${b.type}: ${b.id}`);
    }
  }
  L.push('    }');
  L.push('}');
  return L.join('\n') + '\n';
}

// ---------------------------------------------------------------------------
// Shared helpers for the MQL4 / cTrader Python / Bookmap Python targets.
// Blocks of type signal.* / filter.* / alert.* are booleans; everything else is a value.
// ---------------------------------------------------------------------------
function isPrice(ref) {
  return ['open','high','low','close','hl2','hlc3','ohlc4'].includes(ref);
}

function isBoolType(type) {
  return /^(signal|filter|alert)\./.test(type || '');
}

function parseSession(p) {
  const m = /^(\d{2})(\d{2})-(\d{2})(\d{2})$/.exec(String(p.session || '0000-2359'));
  if (!m) throw new Error('session must look like HHMM-HHMM');
  return { start: (+m[1]) * 60 + (+m[2]), end: (+m[3]) * 60 + (+m[4]) };
}

function thresholdOp(p) {
  return ['>','>=','<','<=','==','!='].includes(p.op) ? p.op : '>=';
}

function warmup(recipe) {
  let n = 2;
  for (const b of recipe.blocks) if (Number.isInteger(b.params?.length)) n = Math.max(n, b.params.length * 3 + 2);
  return n;
}

function renderMql4(recipe) {
  const map = blockMap(recipe);
  const plots = recipe.blocks.filter(b => b.type === 'visual.plot');
  const alerts = recipe.blocks.filter(b => b.type === 'alert.condition');
  const appliedPrice = { open: 'PRICE_OPEN', high: 'PRICE_HIGH', low: 'PRICE_LOW', close: 'PRICE_CLOSE', hl2: 'PRICE_MEDIAN', hlc3: 'PRICE_TYPICAL' };
  const priceExpr = { open: 'Open[i]', high: 'High[i]', low: 'Low[i]', close: 'Close[i]', hl2: '(High[i]+Low[i])/2.0', hlc3: '(High[i]+Low[i]+Close[i])/3.0', ohlc4: '(Open[i]+High[i]+Low[i]+Close[i])/4.0' };
  const val = (ref, at) => isPrice(ref) ? priceExpr[ref].replace(/\[i\]/g, `[${at}]`) : (isBoolType(map.get(ref)?.type) ? `(S_${ref}(${at}) ? 1.0 : 0.0)` : `V_${ref}(${at})`);
  const bool = (ref, at) => isBoolType(map.get(ref)?.type) ? `S_${ref}(${at})` : `(${val(ref, at)} != 0.0 && ${val(ref, at)} != EMPTY_VALUE)`;
  const colors = ['clrDodgerBlue','clrOrange','clrLimeGreen','clrMagenta','clrGold','clrAqua'];
  const L = [];
  L.push('// ORIGINAL BSV STARTER — MT4 / MQL4 custom indicator. Compile in MetaEditor (MT4) before use.');
  L.push('// Generated by BSV Trader Tool Blocks. Not runtime tested by BSV. Not investment advice.');
  L.push('#property strict');
  L.push(recipe.overlay ? '#property indicator_chart_window' : '#property indicator_separate_window');
  L.push(`#property indicator_buffers ${plots.length}`);
  L.push('');
  for (const p of plots) L.push(`double Buf_${p.id}[];`);
  for (const a of alerts) L.push(`datetime g_alert_${a.id} = 0;`);
  L.push(`#define BSV_WARMUP ${warmup(recipe)}`);
  L.push('');
  for (const b of recipe.blocks) {
    const p = b.params || {};
    switch (b.type) {
      case 'indicator.ema':
      case 'indicator.sma': {
        const mode = b.type === 'indicator.ema' ? 'MODE_EMA' : 'MODE_SMA';
        const src = sourceName(p.source);
        if (appliedPrice[src]) L.push(`double V_${b.id}(int i) { return iMA(NULL, 0, ${p.length}, 0, ${mode}, ${appliedPrice[src]}, i); }`);
        else L.push(`double V_${b.id}(int i) { return iMA(NULL, 0, ${p.length}, 0, ${mode}, PRICE_CLOSE, i); } // TODO ohlc4 has no MQL4 applied price; using close`);
        break;
      }
      case 'indicator.rsi': {
        const src = sourceName(p.source);
        if (appliedPrice[src]) L.push(`double V_${b.id}(int i) { return iRSI(NULL, 0, ${p.length}, ${appliedPrice[src]}, i); }`);
        else L.push(`double V_${b.id}(int i) { return iRSI(NULL, 0, ${p.length}, PRICE_CLOSE, i); } // TODO ohlc4 has no MQL4 applied price; using close`);
        break;
      }
      case 'indicator.atr':
        L.push(`double V_${b.id}(int i) { return iATR(NULL, 0, ${p.length}, i); }`);
        break;
      case 'filter.session': {
        const ss = parseSession(p);
        L.push(`// TODO ${b.id}: session ${p.session || ''} is evaluated in broker server time; convert from ${p.timezone || 'Etc/UTC'} for your broker.`);
        L.push(`bool S_${b.id}(int i) { int m = TimeHour(Time[i]) * 60 + TimeMinute(Time[i]); return ${ss.start <= ss.end ? `m >= ${ss.start} && m < ${ss.end}` : `m >= ${ss.start} || m < ${ss.end}`}; }`);
        break;
      }
      case 'signal.cross': {
        const [gt, le] = p.direction === 'below' ? ['<', '>='] : ['>', '<='];
        L.push(`bool S_${b.id}(int i) { return ${val(p.left, 'i')} ${gt} ${val(p.right, 'i')} && ${val(p.left, 'i+1')} ${le} ${val(p.right, 'i+1')}; }`);
        break;
      }
      case 'signal.threshold':
        if (!Number.isFinite(Number(p.value))) throw new Error(`Invalid threshold in ${b.id}`);
        L.push(`bool S_${b.id}(int i) { return ${val(p.left, 'i')} ${thresholdOp(p)} ${Number(p.value)}; }`);
        break;
      case 'signal.combine':
        L.push(`bool S_${b.id}(int i) { return ${(p.signals || []).map(x => bool(x, 'i')).join(p.mode === 'any' ? ' || ' : ' && ') || 'false'}; }`);
        break;
      case 'visual.plot':
      case 'alert.condition':
        break;
      default:
        if (isBoolType(b.type)) L.push(`bool S_${b.id}(int i) { return false; } // TODO unsupported block ${b.type}: ${b.id}`);
        else L.push(`double V_${b.id}(int i) { return EMPTY_VALUE; } // TODO unsupported block ${b.type}: ${b.id}`);
    }
  }
  L.push('');
  L.push('int OnInit()');
  L.push('{');
  L.push(`   IndicatorShortName(${q('BSV — ' + safeTitle(recipe))});`);
  plots.forEach((p, k) => {
    L.push(`   SetIndexBuffer(${k}, Buf_${p.id});`);
    L.push(`   SetIndexStyle(${k}, DRAW_LINE, STYLE_SOLID, 1, ${colors[k % colors.length]});`);
    L.push(`   SetIndexLabel(${k}, ${q(p.params?.title || p.params?.source || p.id)});`);
  });
  L.push('   return(INIT_SUCCEEDED);');
  L.push('}');
  L.push('');
  L.push('int OnCalculate(const int rates_total, const int prev_calculated,');
  L.push('                const datetime &time[], const double &open[], const double &high[],');
  L.push('                const double &low[], const double &close[], const long &tick_volume[],');
  L.push('                const long &volume[], const int &spread[])');
  L.push('{');
  L.push('   if (rates_total <= BSV_WARMUP) return(0);');
  L.push('   int limit = rates_total - prev_calculated;');
  L.push('   if (prev_calculated > 0) limit++;');
  L.push('   if (limit > rates_total - BSV_WARMUP) limit = rates_total - BSV_WARMUP;');
  L.push('   for (int i = limit - 1; i >= 0; i--)');
  L.push('   {');
  for (const p of plots) L.push(`      Buf_${p.id}[i] = ${val(p.params?.source, 'i')};`);
  L.push('   }');
  for (const a of alerts) {
    L.push(`   // ${a.id}: alert once per closed bar.`);
    L.push(`   if (${bool(a.params?.when, '1')} && g_alert_${a.id} != Time[1]) { g_alert_${a.id} = Time[1]; Alert(${q(String(a.params?.message || a.id).replace(/[\r\n]/g, ' '))}); }`);
  }
  L.push('   return(rates_total);');
  L.push('}');
  L.push('');
  L.push('// Compile in MetaEditor, check every TODO, then test on history and a demo account before relying on it.');
  return L.join('\n') + '\n';
}

function renderCTraderPython(recipe) {
  const map = blockMap(recipe);
  const cls = className(recipe);
  const plots = recipe.blocks.filter(b => b.type === 'visual.plot');
  const alerts = recipe.blocks.filter(b => b.type === 'alert.condition');
  const series = { open: 'api.Bars.OpenPrices', high: 'api.Bars.HighPrices', low: 'api.Bars.LowPrices', close: 'api.Bars.ClosePrices', hl2: 'api.Bars.MedianPrices', hlc3: 'api.Bars.TypicalPrices' };
  const priceAt = (ref, at) => ref === 'ohlc4' ? `(api.Bars.OpenPrices[${at}] + api.Bars.HighPrices[${at}] + api.Bars.LowPrices[${at}] + api.Bars.ClosePrices[${at}]) / 4.0` : `${series[ref]}[${at}]`;
  const val = (ref, at) => isPrice(ref) ? priceAt(ref, at) : (isBoolType(map.get(ref)?.type) ? `(1.0 if self.s_${ref}(${at}) else 0.0)` : `self.v_${ref}(${at})`);
  const bool = (ref, at) => isBoolType(map.get(ref)?.type) ? `self.s_${ref}(${at})` : `bool(${val(ref, at)})`;
  const L = [];
  L.push('# ORIGINAL BSV STARTER — cTrader Algo Python custom indicator. Build in cTrader before use.');
  L.push('# Generated by BSV Trader Tool Blocks. Not runtime tested by BSV. Not investment advice.');
  L.push('#');
  L.push(`# 1) In cTrader Algo create a new Python indicator named ${cls}.`);
  L.push(`# 2) Replace the attribute file ${cls}.cs with:`);
  L.push('#');
  L.push('#    using System;');
  L.push('#    using cAlgo.API;');
  L.push('#    namespace cAlgo.Indicators;');
  L.push(`#    [Indicator(IsOverlay = ${recipe.overlay ? 'true' : 'false'}, TimeZone = TimeZones.UTC, AccessRights = AccessRights.None)]`);
  L.push(`#    public partial class ${cls} : Indicator`);
  L.push('#    {');
  for (const p of plots) {
    L.push(`#        [Output(${q(String(p.params?.title || p.id).replace(/"/g, ''))})]`);
    L.push(`#        public IndicatorDataSeries Out_${p.id} { get; set; }`);
  }
  L.push('#    }');
  L.push('#');
  L.push(`# 3) Replace ${cls}_main.py with this file and build.`);
  L.push('');
  L.push('import clr');
  L.push('clr.AddReference("cAlgo.API")');
  L.push('from cAlgo.API import *');
  L.push('');
  L.push(`WARMUP = ${warmup(recipe)}`);
  L.push('');
  L.push(`class ${cls}():`);
  L.push('    def initialize(self):');
  L.push('        self.last_alert = {}');
  for (const b of recipe.blocks) {
    const p = b.params || {};
    const src = () => series[sourceName(p.source)] || 'api.Bars.ClosePrices';
    const note = () => sourceName(p.source) === 'ohlc4' ? '  # TODO ohlc4 has no built-in series; using close' : '';
    if (b.type === 'indicator.ema') L.push(`        self.${b.id} = api.Indicators.ExponentialMovingAverage(${src()}, ${p.length})${note()}`);
    if (b.type === 'indicator.sma') L.push(`        self.${b.id} = api.Indicators.SimpleMovingAverage(${src()}, ${p.length})${note()}`);
    if (b.type === 'indicator.rsi') L.push(`        self.${b.id} = api.Indicators.RelativeStrengthIndex(${src()}, ${p.length})${note()}`);
    if (b.type === 'indicator.atr') L.push(`        self.${b.id} = api.Indicators.AverageTrueRange(${p.length}, MovingAverageType.WilderSmoothing)`);
  }
  L.push('');
  L.push('    def calculate(self, index):');
  L.push('        if index < WARMUP:');
  L.push('            return');
  for (const p of plots) L.push(`        api.Out_${p.id}[index] = ${val(p.params?.source, 'index')}`);
  if (alerts.length) {
    L.push('        if api.IsLastBar:');
    L.push('            i = index - 1  # last closed bar');
    for (const a of alerts) {
      L.push(`            if ${bool(a.params?.when, 'i')} and self.last_alert.get(${q(a.id)}) != i:`);
      L.push(`                self.last_alert[${q(a.id)}] = i`);
      L.push(`                api.Print(${q(String(a.params?.message || a.id).replace(/[\r\n]/g, ' '))})  # swap for api.Notifications if you want sound/email`);
    }
  }
  for (const b of recipe.blocks) {
    const p = b.params || {};
    switch (b.type) {
      case 'indicator.ema': case 'indicator.sma': case 'indicator.rsi': case 'indicator.atr':
        L.push('', `    def v_${b.id}(self, i):`, `        return self.${b.id}.Result[i]`);
        break;
      case 'filter.session': {
        const ss = parseSession(p);
        L.push('', `    def s_${b.id}(self, i):`, `        # TODO ${b.id}: bar times are UTC (see TimeZone attribute); convert session ${p.session || ''} from ${p.timezone || 'Etc/UTC'}.`,
          '        t = api.Bars.OpenTimes[i]', '        m = t.Hour * 60 + t.Minute', `        return ${ss.start <= ss.end ? `${ss.start} <= m < ${ss.end}` : `m >= ${ss.start} or m < ${ss.end}`}`);
        break;
      }
      case 'signal.cross': {
        const [gt, le] = p.direction === 'below' ? ['<', '>='] : ['>', '<='];
        L.push('', `    def s_${b.id}(self, i):`, `        return ${val(p.left, 'i')} ${gt} ${val(p.right, 'i')} and ${val(p.left, 'i - 1')} ${le} ${val(p.right, 'i - 1')}`);
        break;
      }
      case 'signal.threshold':
        if (!Number.isFinite(Number(p.value))) throw new Error(`Invalid threshold in ${b.id}`);
        L.push('', `    def s_${b.id}(self, i):`, `        return ${val(p.left, 'i')} ${thresholdOp(p)} ${Number(p.value)}`);
        break;
      case 'signal.combine':
        L.push('', `    def s_${b.id}(self, i):`, `        return ${(p.signals || []).map(x => bool(x, 'i')).join(p.mode === 'any' ? ' or ' : ' and ') || 'False'}`);
        break;
      case 'visual.plot': case 'alert.condition':
        break;
      default:
        if (isBoolType(b.type)) L.push('', `    def s_${b.id}(self, i):`, `        return False  # TODO unsupported block ${b.type}: ${b.id}`);
        else L.push('', `    def v_${b.id}(self, i):`, `        return float('nan')  # TODO unsupported block ${b.type}: ${b.id}`);
    }
  }
  return L.join('\n') + '\n';
}

function renderBookmapPython(recipe) {
  const plots = recipe.blocks.filter(b => b.type === 'visual.plot');
  const graph = recipe.overlay ? 'PRIMARY' : 'BOTTOM';
  const R = ref => `vals.get(${q(ref)})`;
  const L = [];
  L.push("# ORIGINAL BSV STARTER — Bookmap Python API add-on (Bookmap's Python API is in open beta).");
  L.push('# Generated by BSV Trader Tool Blocks. Not runtime tested by BSV. Not investment advice.');
  L.push('# Bookmap is order-flow based: this starter builds time bars from trades (BAR_SECONDS)');
  L.push('# and evaluates the recipe on each closed bar. Load it via the Bookmap Python API add-on.');
  L.push('# API reference: https://github.com/BookmapAPI/python-api');
  L.push('import time');
  L.push('from collections import deque');
  L.push('import bookmap as bm');
  L.push('');
  L.push('BAR_SECONDS = 60');
  L.push('INTERVALS_PER_BAR = BAR_SECONDS * 10  # on_interval fires every 0.1 s');
  L.push(`PLOTS = ${JSON.stringify(plots.map(p => [p.id, String(p.params?.title || p.id)]))}`);
  L.push(`GRAPH = ${q(graph)}  # PRIMARY = price heatmap, BOTTOM = sub-chart`);
  L.push('');
  L.push('class Ema:');
  L.push('    def __init__(self, n): self.n, self.a, self.v, self.k, self.s = n, 2.0 / (n + 1), None, 0, 0.0');
  L.push('    def update(self, x):');
  L.push('        if self.v is None:');
  L.push('            self.k += 1; self.s += x');
  L.push('            if self.k >= self.n: self.v = self.s / self.n');
  L.push('        else:');
  L.push('            self.v = x * self.a + self.v * (1 - self.a)');
  L.push('        return self.v');
  L.push('');
  L.push('class Sma:');
  L.push('    def __init__(self, n): self.n, self.q = n, deque(maxlen=n)');
  L.push('    def update(self, x):');
  L.push('        self.q.append(x)');
  L.push('        return sum(self.q) / self.n if len(self.q) == self.n else None');
  L.push('');
  L.push('class Rsi:  # Wilder smoothing');
  L.push('    def __init__(self, n): self.n, self.prev, self.g, self.l, self.k = n, None, 0.0, 0.0, 0');
  L.push('    def update(self, x):');
  L.push('        if self.prev is None:');
  L.push('            self.prev = x');
  L.push('            return None');
  L.push('        ch, self.prev = x - self.prev, x');
  L.push('        up, dn = max(ch, 0.0), max(-ch, 0.0)');
  L.push('        self.k += 1');
  L.push('        if self.k <= self.n:');
  L.push('            self.g += up / self.n; self.l += dn / self.n');
  L.push('            if self.k < self.n: return None');
  L.push('        else:');
  L.push('            self.g = (self.g * (self.n - 1) + up) / self.n; self.l = (self.l * (self.n - 1) + dn) / self.n');
  L.push('        return 100.0 if self.l == 0 else 100.0 - 100.0 / (1 + self.g / self.l)');
  L.push('');
  L.push('class Atr:  # Wilder smoothing of true range');
  L.push('    def __init__(self, n): self.n, self.pc, self.v, self.k, self.s = n, None, None, 0, 0.0');
  L.push('    def update(self, b):');
  L.push('        tr = b["h"] - b["l"] if self.pc is None else max(b["h"] - b["l"], abs(b["h"] - self.pc), abs(b["l"] - self.pc))');
  L.push('        self.pc = b["c"]');
  L.push('        if self.v is None:');
  L.push('            self.k += 1; self.s += tr');
  L.push('            if self.k >= self.n: self.v = self.s / self.n');
  L.push('        else:');
  L.push('            self.v = (self.v * (self.n - 1) + tr) / self.n');
  L.push('        return self.v');
  L.push('');
  L.push('def make_calc():');
  L.push('    return {');
  for (const b of recipe.blocks) {
    const p = b.params || {};
    const cls = { 'indicator.ema': 'Ema', 'indicator.sma': 'Sma', 'indicator.rsi': 'Rsi', 'indicator.atr': 'Atr' }[b.type];
    if (cls) L.push(`        ${q(b.id)}: ${cls}(${p.length}),`);
  }
  L.push('    }');
  L.push('');
  L.push('def evaluate(s, b):');
  L.push('    # Runs the recipe on one closed bar b = {o, h, l, c, t}; returns the values by block id.');
  L.push('    calc, prev = s["calc"], s["prev"]');
  L.push('    vals = {"open": b["o"], "high": b["h"], "low": b["l"], "close": b["c"], "hl2": (b["h"] + b["l"]) / 2.0,');
  L.push('            "hlc3": (b["h"] + b["l"] + b["c"]) / 3.0, "ohlc4": (b["o"] + b["h"] + b["l"] + b["c"]) / 4.0}');
  for (const b of recipe.blocks) {
    const p = b.params || {};
    switch (b.type) {
      case 'indicator.ema': case 'indicator.sma': case 'indicator.rsi':
        L.push(`    vals[${q(b.id)}] = calc[${q(b.id)}].update(vals[${q(sourceName(p.source))}])`);
        break;
      case 'indicator.atr':
        L.push(`    vals[${q(b.id)}] = calc[${q(b.id)}].update(b)`);
        break;
      case 'filter.session': {
        const ss = parseSession(p);
        L.push(`    # TODO ${b.id}: bar time is UTC here; convert session ${p.session || ''} from ${p.timezone || 'Etc/UTC'}.`);
        L.push('    g = time.gmtime(b["t"])');
        L.push('    m = g.tm_hour * 60 + g.tm_min');
        L.push(`    vals[${q(b.id)}] = ${ss.start <= ss.end ? `${ss.start} <= m < ${ss.end}` : `m >= ${ss.start} or m < ${ss.end}`}`);
        break;
      }
      case 'signal.cross': {
        const [gt, le] = p.direction === 'below' ? ['<', '>='] : ['>', '<='];
        L.push(`    l, r, pl, pr = ${R(p.left)}, ${R(p.right)}, prev.get(${q(p.left)}), prev.get(${q(p.right)})`);
        L.push(`    vals[${q(b.id)}] = None not in (l, r, pl, pr) and l ${gt} r and pl ${le} pr`);
        break;
      }
      case 'signal.threshold':
        if (!Number.isFinite(Number(p.value))) throw new Error(`Invalid threshold in ${b.id}`);
        L.push(`    v = ${R(p.left)}`);
        L.push(`    vals[${q(b.id)}] = v is not None and v ${thresholdOp(p)} ${Number(p.value)}`);
        break;
      case 'signal.combine':
        L.push(`    vals[${q(b.id)}] = ${(p.signals || []).map(x => `bool(${R(x)})`).join(p.mode === 'any' ? ' or ' : ' and ') || 'False'}`);
        break;
      case 'visual.plot': case 'alert.condition':
        break;
      default:
        L.push(`    vals[${q(b.id)}] = None  # TODO unsupported block ${b.type}: ${b.id}`);
    }
  }
  L.push('    return vals');
  L.push('');
  L.push('def on_bar_closed(addon, alias, s, b):');
  L.push('    vals = evaluate(s, b)');
  for (const p of plots) {
    L.push(`    v = vals.get(${q(p.params?.source)})`);
    L.push(`    if v is not None and ${q(p.id)} in s["ind"]:`);
    L.push(`        bm.add_point(addon, alias, s["ind"][${q(p.id)}], ${graph === 'PRIMARY' ? 'v / s["pips"])  # PRIMARY points are price levels' : 'float(v))  # check BOTTOM scaling in your Bookmap version'}`);
  }
  for (const a of recipe.blocks.filter(b => b.type === 'alert.condition')) {
    L.push(`    if vals.get(${q(a.params?.when)}):`);
    L.push(`        print(alias, ${q(String(a.params?.message || a.id).replace(/[\r\n]/g, ' '))}, flush=True)  # one line per closed bar`);
  }
  L.push('    s["prev"] = vals');
  L.push('');
  L.push('state = {}');
  L.push('requests = {}');
  L.push('next_req = [1]');
  L.push('');
  L.push('def handle_subscribe_instrument(addon, alias, full_name, is_crypto, pips, size_multiplier, instrument_multiplier, supported_features):');
  L.push('    state[alias] = {"pips": pips, "bar": None, "ticks": 0, "calc": make_calc(), "prev": {}, "ind": {}}');
  L.push('    for pid, title in PLOTS:');
  L.push('        req = next_req[0]');
  L.push('        next_req[0] += 1');
  L.push('        requests[req] = (alias, pid)');
  L.push('        bm.register_indicator(addon, alias, req, "BSV " + title, GRAPH)');
  L.push('    req = next_req[0]');
  L.push('    next_req[0] += 1');
  L.push('    bm.subscribe_to_trades(addon, alias, req)');
  L.push('');
  L.push('def handle_unsubscribe_instrument(addon, alias):');
  L.push('    state.pop(alias, None)');
  L.push('');
  L.push('def handle_indicator_response(addon, request_id, indicator_id):');
  L.push('    if request_id in requests:');
  L.push('        alias, pid = requests[request_id]');
  L.push('        if alias in state:');
  L.push('            state[alias]["ind"][pid] = indicator_id');
  L.push('');
  L.push('def handle_trades(addon, alias, price_level, size_level, is_otc, is_bid, is_execution_start, is_execution_end, aggressor_order_id, passive_order_id):');
  L.push('    s = state.get(alias)');
  L.push('    if s is None:');
  L.push('        return');
  L.push('    px = price_level * s["pips"]');
  L.push('    b = s["bar"]');
  L.push('    if b is None:');
  L.push('        s["bar"] = {"o": px, "h": px, "l": px, "c": px, "t": time.time()}');
  L.push('    else:');
  L.push('        b["h"] = max(b["h"], px)');
  L.push('        b["l"] = min(b["l"], px)');
  L.push('        b["c"] = px');
  L.push('');
  L.push('def on_interval(addon, alias):');
  L.push('    s = state.get(alias)');
  L.push('    if s is None:');
  L.push('        return');
  L.push('    s["ticks"] += 1');
  L.push('    if s["ticks"] >= INTERVALS_PER_BAR:');
  L.push('        s["ticks"] = 0');
  L.push('        b, s["bar"] = s["bar"], None');
  L.push('        if b is not None:  # bars without trades are skipped');
  L.push('            on_bar_closed(addon, alias, s, b)');
  L.push('');
  L.push('if __name__ == "__main__":');
  L.push('    addon = bm.create_addon()');
  L.push('    bm.add_trades_handler(addon, handle_trades)');
  L.push('    bm.add_on_interval_handler(addon, on_interval)');
  L.push('    bm.add_indicator_response_handler(addon, handle_indicator_response)');
  L.push('    bm.start_addon(addon, handle_subscribe_instrument, handle_unsubscribe_instrument)');
  L.push('    bm.wait_until_addon_is_turned_off(addon)');
  return L.join('\n') + '\n';
}
