'use strict';
(() => {
  const $=id=>document.getElementById(id);
  const t=pair=>window.BSVLabs.text(pair[0],pair[1]);
  const data={
    s2:{name:'Sentinel-2 Level-2A',viewer:'Copernicus Browser',url:'https://browser.dataspace.copernicus.eu/',signal:['Surface reflectance; visible and near-infrared bands at 10 m, other bands at 20 or 60 m.','地表面反射率。可視・近赤外の一部バンドは10 m、ほかは20・60 m。'],tradeoff:['Needs sunlight and a cloud-free view of the target. Scene cloud percentage alone is insufficient.','日光と対象地点の雲のない視野が必要。シーン全体の雲量だけでは不十分。'],access:['Basic preview may be available anonymously. Use a free Copernicus Data Space account for analytical downloads and advanced features; service quotas apply.','基本プレビューは匿名で使える場合があります。解析用ダウンロードや高度な機能には無料のCopernicus Data Spaceアカウントを使います。サービス利用枠があります。']},
    s1:{name:'Sentinel-1 GRD',viewer:'Copernicus Browser',url:'https://browser.dataspace.copernicus.eu/',signal:['C-band radar backscatter; day/night and through clouds. Resolution and pixel spacing depend on the product.','Cバンドのレーダー後方散乱。昼夜・雲を通した観測。解像度と画素間隔は製品によります。'],tradeoff:['Speckle, terrain shadow and viewing geometry complicate water interpretation. Not a photograph.','スペックル、地形の影、観測方向が水域の判読に影響。写真とは異なります。'],access:['Basic preview may be available anonymously. A free Copernicus Data Space account supports analytical downloads; check the product and service quotas.','基本プレビューは匿名で使える場合があります。解析用ダウンロードには無料のCopernicus Data Spaceアカウントを使い、製品と利用枠を確認してください。']},
    landsat:{name:'Landsat Collection 2 Level-2',viewer:'USGS EarthExplorer',url:'https://earthexplorer.usgs.gov/',signal:['Surface reflectance for a long land record; compare compatible products and spectral bands across sensors.','長期の陸域記録を持つ地表面反射率。センサーをまたぐ比較では製品・波長帯をそろえます。'],tradeoff:['Optical reflectance needs daytime and clear views. Sensor differences can resemble real land change.','光学反射率は晴天の昼間が必要。センサーの違いを土地の変化と誤認しないようにします。'],access:['Landsat data are available at no cost. You can search in EarthExplorer; a free USGS EROS account is required to download or order scenes.','Landsatデータは無料。EarthExplorerで検索でき、シーンのダウンロード・注文には無料のUSGS EROSアカウントが必要です。']},
    viirs:{name:'VIIRS 375 m active-fire detections',viewer:'NASA FIRMS Fire Map',url:'https://firms.modaps.eosdis.nasa.gov/map/',signal:['Thermal anomalies, with daytime and nighttime detections. Nominal 375 m fire pixels.','昼夜の熱異常検出。火災画素の公称サイズは375 m。'],tradeoff:['Cloud and overpass gaps can hide fires. A hotspot pixel is neither a fire boundary nor proof of its cause.','雲や観測間隔により見逃しが発生。検出画素は火災の境界でも原因の証明でもありません。'],access:['The FIRMS public map is available for browsing. Historical files and programmatic services have separate access routes; check their current requirements before automating.','FIRMSの公開地図で閲覧できます。過去データとプログラム利用は別の入手経路なので、自動化の前に最新条件を確認してください。']}
  };
  function recommend({phenomenon,cloud,light}) {return phenomenon==='fire'?'viirs':phenomenon==='history'?'landsat':phenomenon==='flood'&&(cloud==='cloudy'||light==='night')?'s1':'s2';}
  window.BSVSatellite={recommend};
  function render(){
    document.querySelectorAll('option[data-en]').forEach(o=>{o.textContent=window.BSVLabs.lang()==='ja'?o.dataset.ja:o.dataset.en;});
    const q=Object.fromEntries(['phenomenon','scale','cloud','light'].map(id=>[id,$(id).value]));
    const key=recommend(q),d=data[key],optical=key==='s2'||key==='landsat',blocked=optical&&(q.cloud==='cloudy'||q.light==='night');
    const reason=key==='viirs'?['You asked for active-fire screening. Thermal anomalies are the relevant signal; daylight-only color imagery is not enough.','活動中の火災の把握には熱異常を利用します。昼間のカラー画像だけでは足りません。']:key==='landsat'?['You asked for change across decades. A long, comparable land-observation record matters more than choosing the smallest current pixels.','数十年単位の比較では、現在の最小画素より、比較可能な長期の陸域観測記録を重視します。']:key==='s1'?['You asked for water extent with persistent cloud or nighttime acquisition. Radar provides an observation path under those conditions.','雲の継続または夜間の条件で水域を見たいという入力です。レーダーなら、その条件下で観測する方法があります。']:q.phenomenon==='flood'?['You can use a clear daytime view. Optical water contrast is a practical starting point for visual comparison; radar remains an alternative.','晴天の昼間を利用できるため、光学画像の水と陸の違いから目視比較を始めます。レーダーも代替候補です。']:['You asked for vegetation condition. Red and near-infrared reflectance let you explore vegetation contrast and NDVI.','植生の状態を見るため、赤と近赤外の反射率から植生の違いやNDVIを調べます。'];
    const cautions=[];
    if(optical&&q.light==='night')cautions.push(['Requirement gap: this reflectance workflow cannot observe at night. Allow a daytime acquisition or change the question; radar does not reproduce the same optical index.','条件が不一致：この反射率の手順は夜間に観測できません。昼間の観測を許容するか問いを変更します。レーダーでは同じ光学指標を再現できません。']);
    if(optical&&q.cloud==='cloudy')cautions.push(['Requirement gap: cloud can hide the surface. Extend the date window or wait for a clear view. Compositing cannot recover a surface never observed clearly.','条件が不一致：雲が地表を隠します。期間を広げるか晴天を待ちます。合成処理でも、一度も見えていない地表は復元できません。']);
    if(key==='viirs'&&q.cloud==='cloudy')cautions.push(['Cloudy-period gap: no hotspot detection does not mean no fire. Inspect cloud cover, satellite overpass time and data gaps.','曇天の不足情報：検出がないことは火災がないことを意味しません。雲、衛星の通過時刻、データ欠損を確認します。']);
    if(key==='viirs'&&q.light==='night')cautions.push(['Nighttime screening is possible, but observations are intermittent. Filter by acquisition time and the day/night field, not just the calendar date.','夜間の検出は可能ですが連続観測ではありません。日付だけでなく観測時刻と昼夜区分で絞り込みます。']);
    if(q.scale==='local')cautions.push(key==='viirs'?['Scale mismatch: a 375 m detection pixel is too coarse to assign a fire to a small parcel or outline its perimeter. Use it to identify a wider area for follow-up.','範囲の不一致：375 mの検出画素では小さな区画や火災境界を特定できません。追加確認する広域の場所を絞るために使います。']:['Small-site check: inspect how many independent pixels cover the feature. Boundaries and mixed pixels can dominate a small field; do not interpret an individual building or tree.','小範囲の確認：対象に何画素が対応するかを確認。小さな圃場では境界や混合画素の影響が大きく、個々の建物や樹木は判読対象にしません。']);
    if(q.scale==='regional')cautions.push(['Basin/city check: one scene may not cover the whole area or observation period. Keep a consistent boundary and compare acquisition dates, not just layer names.','都市・流域の確認：1シーンで全域・全期間をカバーしない場合があります。境界を固定し、レイヤー名だけでなく観測日を比較します。']);
    if(q.scale==='large')cautions.push(['Large-area check: use a date-window composite or several scenes and record their dates. Start with a small pilot area before downloading a regional mosaic.','広域の確認：一定期間の合成画像または複数シーンを使い、各観測日を記録。広域画像を取得する前に小範囲で試します。']);
    cautions.push(key==='s1'?['Keep the same orbit direction, relative orbit and polarization when comparing. Radar shadow, smooth dry surfaces and wind-roughened water can confuse a simple dark-pixel test.','比較時は軌道方向、相対軌道、偏波をそろえます。レーダー影、滑らかな乾燥地表、風で荒れた水面により、暗い画素だけの判定は誤ります。']:key==='viirs'?['For research, prefer a consistent standard archive over mixing near-real-time and reprocessed products. Do not use this planning tool for emergency decisions.','研究では準リアルタイム製品と再処理製品を混ぜず、一貫した標準アーカイブを優先。この計画ツールを緊急判断には使わないでください。']:['Mask cloud, cloud shadow and invalid pixels. A change in illumination, season or image stretch can look like a change on the ground.','雲・雲影・無効画素を除外。照明条件、季節、表示の強調方法の違いを地表の変化と誤認しないようにします。']);
    let steps,example;
    if(key==='s1'){
      steps=[['Open Copernicus Browser, find your river or lake, and choose Sentinel-1 GRD. Begin with a small area containing known land and water.','Copernicus Browserで川・湖を探し、Sentinel-1 GRDを選択。既知の陸地と水面を含む小範囲から開始。'],['Find a reference date and a target date with matching orbit and polarization. Read product metadata before comparing.','基準日と対象日のデータを探し、軌道・偏波をそろえます。比較前に製品メタデータを確認。'],['Compare backscatter with the same display range. Mark new low-backscatter patches as candidates, not confirmed flooding.','同じ表示範囲で後方散乱を比較。新たな低散乱域は浸水の候補として記録し、確定とはしません。'],['For quantitative mapping, use calibrated, terrain-corrected data, handle speckle, and validate candidates against independent observations. Save product IDs, dates and processing choices.','定量地図では校正・地形補正済みデータを用い、スペックルを扱い、別の観測で候補を検証。製品ID・日付・処理条件を保存。']];
      example=['Practice around Lake Mead, USA: search two Sentinel-1 GRD acquisitions in June 2021 and June 2022. Match the relative orbit and polarization, inspect a shoreline, and list changes you can and cannot distinguish. This is a water-extent exercise, not a flood claim.','米国ミード湖で練習：2021年6月と2022年6月のSentinel-1 GRDを検索。同じ相対軌道・偏波で湖岸を比較し、区別できる変化とできない変化を列挙します。水域範囲の練習であり、洪水があったという主張ではありません。'];
    }else if(key==='viirs'){
      steps=[['Open NASA FIRMS and select VIIRS active-fire detections. Choose an area and a short date range that you can inspect manually.','NASA FIRMSでVIIRSの活動火災検出を選び、手作業で確認できる範囲と短い期間を指定。'],['Inspect acquisition time in UTC, confidence and day/night information. Compare the points with imagery and cloud conditions for that date.','UTCの観測時刻、信頼度、昼夜区分を確認。同日の画像や雲の状況と照合。'],['Group nearby detections across overpasses; repeated points can be the same event. Do not count each pixel as a separate fire.','複数の観測時刻の近接検出をまとめます。同じ現象を繰り返し観測することがあるため、画素数を火災件数としません。'],['Write a screening note with the observation times, uncertainties and a follow-up source. For historical analysis, use the archive rather than assuming the live map covers old dates.','観測時刻、不確実性、追加確認先を記録。過去分析ではライブ地図で古い日付を見られると仮定せず、アーカイブを使います。']];
      example=['Practice over northern Australia using the most recent seven days available in FIRMS. Compare one day and one night overpass. If no points appear, record “no detections in the inspected data,” then check cloud and coverage; do not record “no fire.”','オーストラリア北部で、FIRMSで利用できる直近7日を使い練習。昼と夜の通過を1回ずつ比較。点がなければ「確認したデータ内で検出なし」と記録し、雲と観測範囲を調べます。「火災なし」とはしません。'];
    }else if(key==='landsat'){
      steps=[['Open EarthExplorer and define a small polygon around the study area. Choose Landsat Collection 2 Level-2 and two comparable seasonal windows.','EarthExplorerで対象地の小さなポリゴンを指定。Landsat Collection 2 Level-2と、季節をそろえた2期間を選択。'],['Inspect each scene footprint and cloud cover over the actual site. Use surface reflectance products, and record the satellite and product IDs.','各シーンの範囲と対象地点の雲を確認。地表面反射率製品を使い、衛星と製品IDを記録。'],['Apply the documented scale/offset and quality mask before computing an index. Match spectral meanings across sensors rather than copying band numbers.','指標の計算前に製品指定のスケール・オフセットと品質マスクを適用。センサー間で番号を流用せず、波長帯の意味を対応させます。'],['Compare a stable reference site and the target. Separate seasonal, sensor and atmospheric effects from plausible land change; export the comparison with metadata.','安定した参照地点と対象地を比較。季節・センサー・大気の影響と土地変化の可能性を分け、メタデータ付きで結果を保存。']];
      example=['Practice near Las Vegas, USA: search summer 1990 and summer 2020 Level-2 scenes. Compare city-edge land cover and a nearby stable desert area. Note the different sensors and avoid inferring population change directly from image color.','米国ラスベガス周辺で練習：1990年夏と2020年夏のLevel-2を検索。市街地の縁と、近くの変化が小さい砂漠を比較。センサーの違いを記録し、画像の色から人口変化を直接推定しないようにします。'];
    }else{
      steps=[['Open Copernicus Browser and choose Sentinel-2 Level-2A. Find a small site and two dates with usable daylight observations.','Copernicus BrowserでSentinel-2 Level-2Aを選択。小範囲の対象地と、昼間に良好な観測がある2日を探します。'],['Inspect true color first. Check cloud and shadow over your actual site, and keep the same visualization settings for both dates.','最初に自然色を確認。対象地点の雲と影を調べ、両日で表示設定をそろえます。'],q.phenomenon==='vegetation'?['Try NDVI = (B8 − B4) / (B8 + B4), using valid surface reflectance and excluding a zero denominator. Compare similar seasons when studying a long-term change.','有効な地表面反射率でNDVI = (B8 − B4) / (B8 + B4)を試し、分母0は除外。長期変化の比較では季節をそろえます。']:['Compare the shoreline in true color, then try NDWI = (B3 − B8) / (B3 + B8) on valid pixels. A threshold is a starting hypothesis, not a universal water classifier.','自然色で岸を比較し、有効画素でNDWI = (B3 − B8) / (B3 + B8)を試します。閾値は仮説の出発点で、万能な水域分類ではありません。'],['Save the dates, product IDs, cloud checks and one alternative explanation. A screenshot helps communicate; quantitative analysis needs the data and metadata.','日付、製品ID、雲の確認、別の説明を1つ記録。画像は説明に役立ちますが、定量分析には元データとメタデータが必要です。']];
      example=q.phenomenon==='vegetation'?['Practice in a large park near Tokyo: search April and July 2024, find cloud-free Sentinel-2 Level-2A scenes, and compare trees with a nearby paved area. Treat seasonal greenness as a hypothesis; NDVI alone does not diagnose tree health.','東京周辺の大きな公園で練習：2024年4月と7月の雲の少ないSentinel-2 Level-2Aを探し、樹木と近くの舗装面を比較。季節的な緑の変化を仮説とし、NDVIだけで樹木の健康を診断しないようにします。']:['Practice around Lake Mead, USA: search June 2021 and June 2022, inspect cloud-free Sentinel-2 Level-2A scenes, and compare a single shoreline segment. Describe apparent water extent; do not label every shoreline change a flood.','米国ミード湖で練習：2021年6月と2022年6月の雲のないSentinel-2 Level-2Aを探し、湖岸の一部を比較。見かけの水域範囲を記述し、湖岸変化をすべて洪水とは呼ばないようにします。'];
    }
    $('recommendation').textContent=d.name;
    $('fit').textContent=t(blocked?['Useful dataset, but your conditions need adjustment','有用なデータですが、入力条件の調整が必要です']:['A practical first candidate — verify coverage','最初の候補 — 実際の観測範囲を確認']);
    $('reason').textContent=t(reason);$('access').textContent=t(d.access);$('scope').textContent=t(['Availability is not checked. Satellite revisit does not guarantee a usable acquisition over your site.','提供状況は未確認です。衛星の再訪があっても、対象地点の利用可能な観測を保証しません。']);
    $('viewer').href=d.url;$('viewer').textContent=d.viewer+' ↗';
    for(const [id,values]of [['constraints',cautions],['workflow',steps]])$(id).replaceChildren(...values.map(v=>{const li=document.createElement('li');li.textContent=t(v);return li;}));
    $('worked-example').textContent=t(example);
    $('comparison').replaceChildren(...Object.entries(data).map(([id,row])=>{const tr=document.createElement('tr');[row.name,t(row.signal),t(row.tradeoff),id===key?t(['Selected','選択中']):t(['Alternative / different signal','代替候補・異なる情報'])].forEach(v=>{const td=document.createElement('td');td.textContent=v;tr.append(td);});return tr;}));
    const selection=['phenomenon','scale','cloud','light'].map(id=>$(id).selectedOptions[0].textContent).join(' / ');
    $('plan').value=[t(['BSV satellite workflow','BSV 衛星データ観測計画']),selection,d.name,t(reason),'',...cautions.map(v=>'• '+t(v)),'',...steps.map((v,i)=>(i+1)+'. '+t(v)),'',t(example),d.url,t(d.access)].join('\n');
  }
  ['phenomenon','scale','cloud','light'].forEach(id=>$(id).addEventListener('change',()=>{$('copy-status').textContent='';render();}));
  $('example').addEventListener('click',()=>{$('phenomenon').value='flood';$('scale').value='regional';$('cloud').value='cloudy';$('light').value='night';render();});
  $('copy').addEventListener('click',async()=>{try{await navigator.clipboard.writeText($('plan').value);$('copy-status').textContent=t(['Workflow copied.','手順をコピーしました。']);}catch{$('plan').focus();$('plan').select();$('copy-status').textContent=t(['Copy the selected workflow text manually.','選択された手順を手動でコピーしてください。']);}});
  document.addEventListener('bsv:language',render);render();
})();
