"""BSV field pages content (Healthcare & Medical Robotics, Space, Biotech, Quantum) — data only.

Written by BSV (New Bobby), 2026-10-06. Recipes are BSV-original workflows; code lives in fields/code/<field>/
(BSV original, MIT). Sources are outbound links with a short BSV summary; nothing third-party is rehosted.
Test status is NOT written here: it comes from fields/test_runs.json (smoke_fields_recipes.py) and
source HTTP status from fields/sources_check.json (check_fields_sources.py) at build time.
Text: en + ja for bodies; titles / summaries / UI also es / zh / ko (L5 order: en, ja, es, zh, ko).
"""

LANGS = ("en", "ja", "es", "zh", "ko")

UI = {  # page chrome, 5 languages
    "fldOnPage": ("On this page", "このページの内容", "En esta página", "本页内容", "이 페이지"),
    "fldRecipes": ("Build recipes", "作り方レシピ", "Recetas para construir", "构建配方", "제작 레시피"),
    "fldRecipesLead": ("Step-by-step workflows written by BSV. Each one combines real open tools into something you can make today.",
                       "BSVが書いた手順つきのワークフローです。実在するオープンなツールを組み合わせて、今日から作れるものにしています。",
                       "Flujos paso a paso escritos por BSV. Cada uno combina herramientas abiertas reales en algo que puedes construir hoy.",
                       "由 BSV 编写的分步工作流。每一个都把真实的开源工具组合成你今天就能做出来的东西。",
                       "BSV가 작성한 단계별 워크플로입니다. 실제 오픈 도구를 조합해 오늘 바로 만들 수 있게 했습니다."),
    "fldCompare": ("Compare the tools", "ツールを比べる", "Comparar herramientas", "比较工具", "도구 비교"),
    "fldCompareLead": ("Difficulty is BSV's own rating for a first project. Check each licence on the official page before you ship anything.",
                       "難易度は、最初のプロジェクトを想定したBSVの目安です。何かを公開・配布する前に、各ライセンスを公式ページで確認してください。",
                       "La dificultad es una valoración propia de BSV para un primer proyecto. Revisa cada licencia en la página oficial antes de publicar.",
                       "难度是 BSV 针对第一个项目给出的参考。发布任何东西之前，请在官方页面确认各自的许可证。",
                       "난이도는 첫 프로젝트를 기준으로 한 BSV의 자체 평가입니다. 배포 전에 공식 페이지에서 라이선스를 꼭 확인하세요."),
    "fldStack": ("Starter stack: verified sources", "スターターセット：確認済みの出典", "Kit inicial: fuentes verificadas", "入门清单：已核实的来源", "스타터 스택: 확인된 출처"),
    "fldStackLead": ("Official pages only. BSV opened each link and recorded the HTTP status and date shown. We link out and summarise; we do not copy or rehost their code.",
                     "公式ページだけを載せています。BSVが各リンクを開き、表示しているHTTPステータスと日付を記録しました。リンクと要約のみで、コードの転載や再配布はしていません。",
                     "Solo páginas oficiales. BSV abrió cada enlace y registró el estado HTTP y la fecha indicados. Enlazamos y resumimos; no copiamos ni alojamos su código.",
                     "仅收录官方页面。BSV 逐一打开链接并记录了所示的 HTTP 状态和日期。我们只做链接和摘要，不复制、不转载其代码。",
                     "공식 페이지만 실었습니다. BSV가 각 링크를 열어 HTTP 상태와 날짜를 기록했습니다. 링크와 요약만 제공하며 코드를 복제하거나 재배포하지 않습니다."),
    "fldInput": ("Input", "入力", "Entrada", "输入", "입력"),
    "fldOutput": ("Output", "出力", "Salida", "输出", "출력"),
    "fldPrereq": ("Prerequisites", "前提", "Requisitos", "前提条件", "준비물"),
    "fldSteps": ("Steps", "手順", "Pasos", "步骤", "단계"),
    "fldExpected": ("Expected result", "期待される結果", "Resultado esperado", "预期结果", "예상 결과"),
    "fldNext": ("Next step", "次の一歩", "Siguiente paso", "下一步", "다음 단계"),
    "fldCode": ("Code (BSV original, MIT licence)", "コード（BSVオリジナル・MITライセンス）", "Código (original de BSV, licencia MIT)", "代码（BSV 原创，MIT 许可）", "코드 (BSV 오리지널, MIT 라이선스)"),
    "fldDownload": ("Download .py", ".py をダウンロード", "Descargar .py", "下载 .py", ".py 다운로드"),
    "fldBsvRun": ("Output of BSV's own test run", "BSVのテスト実行で実際に出た出力", "Salida de la prueba de BSV", "BSV 实际测试运行的输出", "BSV 테스트 실행의 실제 출력"),
    "fldTested": ("Tested by BSV", "BSVで動作確認済み", "Probado por BSV", "BSV 已测试", "BSV 테스트 완료"),
    "fldUntested": ("Not run by BSV", "BSVでは未実行", "No ejecutado por BSV", "BSV 未运行", "BSV 미실행"),
    "fldTool": ("Tool", "ツール", "Herramienta", "工具", "도구"),
    "fldJob": ("Job", "用途", "Para qué sirve", "用途", "용도"),
    "fldLicense": ("Licence", "ライセンス", "Licencia", "许可证", "라이선스"),
    "fldDifficulty": ("Difficulty", "難易度", "Dificultad", "难度", "난이도"),
    "fldWhere": ("Local / cloud", "ローカル／クラウド", "Local / nube", "本地 / 云端", "로컬 / 클라우드"),
    "fldOrg": ("Organisation", "運営", "Organización", "机构", "운영 주체"),
    "fldChecked": ("Checked", "確認日", "Comprobado", "核实日期", "확인일"),
    "fldRelated": ("Related on BSV", "BSV内の関連ページ", "Relacionado en BSV", "BSV 相关内容", "BSV 관련 페이지"),
    "fldAllCats": ("All categories", "すべてのカテゴリー", "Todas las categorías", "全部类别", "모든 카테고리"),
    "diff_beginner": ("Beginner", "初級", "Inicial", "入门", "입문"),
    "diff_intermediate": ("Intermediate", "中級", "Intermedio", "中级", "중급"),
    "diff_advanced": ("Advanced", "上級", "Avanzado", "高级", "고급"),
    "where_local": ("Local", "ローカル", "Local", "本地", "로컬"),
    "where_cloud": ("Cloud / web API", "クラウド／Web API", "Nube / API web", "云端 / Web API", "클라우드 / 웹 API"),
    "where_both": ("Local + cloud", "ローカル＋クラウド", "Local + nube", "本地 + 云端", "로컬 + 클라우드"),
    "where_gpu": ("Local (GPU helps)", "ローカル（GPU推奨）", "Local (mejor con GPU)", "本地（建议 GPU）", "로컬 (GPU 권장)"),
}

F = {}

# ---------------------------------------------------------------- Healthcare & Medical Robotics
F["healthcare"] = {
    "name": ("Healthcare & Medical Robotics", "ヘルスケア・医療ロボティクス", "Salud y robótica médica", "医疗健康与医疗机器人", "헬스케어·의료 로보틱스"),
    "h1": ("Healthcare & medical robotics: simulate, measure, learn", "ヘルスケア・医療ロボティクス：シミュレーションで試し、測り、学ぶ",
           "Salud y robótica médica: simular, medir, aprender", "医疗健康与医疗机器人：仿真、测量、学习", "헬스케어·의료 로보틱스: 시뮬레이션하고, 측정하고, 배우기"),
    "lead": ("Build simulation and data-handling exercises with open tools: robot positioning in MuJoCo, soft-tissue indentation in SOFA, DICOM housekeeping and 3D models from public sample scans.",
             "オープンなツールで、シミュレーションとデータの扱い方を練習できる題材を作ります。MuJoCoでのロボット位置決め、SOFAでの軟組織の押し込み、DICOMの整理、公開サンプル画像からの3Dモデル作成です。",
             "Ejercicios de simulación y manejo de datos con herramientas abiertas: posicionamiento robótico en MuJoCo, indentación de tejido blando en SOFA, DICOM y modelos 3D a partir de escaneos de muestra públicos.",
             "用开源工具做仿真与数据处理练习：在 MuJoCo 中做机器人定位，在 SOFA 中做软组织压入，整理 DICOM，并从公开样例扫描生成 3D 模型。",
             "오픈 도구로 시뮬레이션과 데이터 처리 연습 과제를 만듭니다. MuJoCo 로봇 위치 결정, SOFA 연조직 압입, DICOM 정리, 공개 샘플 스캔으로 3D 모델 만들기."),
    "notice": ("Research, education and simulation only. Nothing here is a medical device, a clinical method or advice for patient care, and none of it has been validated for clinical use.",
               "研究・教育・シミュレーション用途に限ります。ここにあるものは医療機器でも臨床手法でもなく、患者のケアに関する助言でもありません。臨床での使用について検証されたものは一つもありません。",
               "Solo para investigación, educación y simulación. Nada de esto es un dispositivo médico, un método clínico ni un consejo para la atención de pacientes, y nada ha sido validado para uso clínico.",
               "仅限研究、教育与仿真用途。这里的内容都不是医疗器械、临床方法或患者护理建议，也均未经过临床使用验证。",
               "연구·교육·시뮬레이션 전용입니다. 여기 있는 어떤 것도 의료기기, 임상 방법, 환자 치료에 관한 조언이 아니며 임상 사용에 대해 검증되지 않았습니다."),
    "recipes": [
        {"id": "mujoco-probe-positioning", "code": "mujoco_probe_reach.py",
         "title": ("Measure probe-tip positioning accuracy in MuJoCo", "MuJoCoで、プローブ先端の位置決め精度を測る", "Medir la precisión de posicionamiento de una sonda en MuJoCo", "在 MuJoCo 中测量探针尖端的定位精度", "MuJoCo로 프로브 끝 위치 결정 정확도 측정"),
         "summary": ("Model a small two-link arm, send its tip to target points and log how fast and how precisely it arrives — a first simulation check for a robot-assisted positioning idea.",
                     "小さな2リンクアームをモデル化し、先端を目標点へ動かして、どれだけ速く正確に届くかを記録します。ロボットで位置決めをするアイデアを、まずシミュレーションで確かめるための題材です。",
                     "Modela un brazo de dos eslabones, lleva su punta a puntos objetivo y registra la rapidez y precisión con que llega: una primera comprobación en simulación.",
                     "建立一个小型两连杆机械臂模型，把尖端送到目标点，记录到达的速度与精度——用仿真初步检验机器人辅助定位的想法。",
                     "작은 2링크 팔을 모델링해 끝을 목표점으로 보내고 얼마나 빠르고 정확하게 도달하는지 기록합니다. 로봇 보조 위치 결정 아이디어를 시뮬레이션으로 먼저 확인하는 과제입니다."),
         "input": ("Target points in millimetres (in reach: 20–220 mm from the base), controller gain kp, tolerance in mm.",
                   "目標点（ミリ単位。根元から20〜220 mmの範囲）、制御ゲイン kp、許容誤差（mm）。"),
         "output": ("probe_reach.csv — one row per target: time to first reach the tolerance, time it settles inside it, final error, how far the tip went past the target, reached yes/no.",
                    "probe_reach.csv（目標ごとに1行）：許容誤差に初めて入るまでの時間、その中に収まった時刻、最終誤差、先端が目標を行き過ぎた距離、到達の可否。"),
         "prereq": ("Python 3.10 or later and `pip install mujoco numpy`. No GPU and no robot hardware needed.",
                    "Python 3.10以上と `pip install mujoco numpy`。GPUもロボット実機も不要です。"),
         "steps": {"en": ["Save the code below as mujoco_probe_reach.py (it contains the arm model, closed-form inverse kinematics and the logger).",
                          "Run `python mujoco_probe_reach.py` to use the four default targets.",
                          "Open probe_reach.csv and read time_to_tol_s, settled_at_s, final_err_mm and overshoot_mm side by side.",
                          "Run again with a softer controller: `python mujoco_probe_reach.py \"150,60;120,-80;180,0;90,120\" 20`, and compare the two files.",
                          "Replace the targets with points that matter for your idea and keep each run's CSV, named by its settings."],
                   "ja": ["下のコードを mujoco_probe_reach.py として保存します（アームのモデル、逆運動学の解析解、記録処理が入っています）。",
                          "`python mujoco_probe_reach.py` を実行すると、既定の4つの目標点で動きます。",
                          "probe_reach.csv を開き、time_to_tol_s・settled_at_s・final_err_mm・overshoot_mm を並べて見ます。",
                          "制御を弱めてもう一度実行します：`python mujoco_probe_reach.py \"150,60;120,-80;180,0;90,120\" 20`。2つのファイルを比べてください。",
                          "目標点を、ご自身のアイデアで意味のある位置に置き換えます。実行ごとのCSVは、設定値がわかる名前で残しておきます。"]},
         "expected": ("Every target is reached and the final error is close to zero. A lower gain arrives later. Because the arm moves in joint space, the tip path curves, so it can travel well past the target along the straight line before settling — exactly the kind of behaviour worth logging before anyone trusts a positioning idea.",
                      "すべての目標に到達し、最終誤差はほぼゼロになります。ゲインを下げると到達は遅くなります。アームは関節空間で動くため先端の軌跡は曲がり、直線上で見ると目標をかなり行き過ぎてから収まることがあります。位置決めのアイデアを信用する前に、まさに記録しておきたい挙動です。"),
         "next": ("Swap in your own robot's MJCF/URDF model and add a third joint, then practise teleoperation in BSV's Robot Pilot Academy (simulation first).",
                  "ご自身のロボットのMJCF／URDFモデルに差し替え、関節を1つ増やしてみてください。そのうえで、BSVのRobot Pilot Academyで遠隔操作を練習できます（まずはシミュレーションから）。"),
         "next_href": "/robot-pilot/"},
        {"id": "sofa-tissue-indentation", "code": "sofa_tissue_indent.py",
         "title": ("Soft-tissue indentation in SOFA: log force against displacement", "SOFAで軟組織を押し込み、力と変位を記録する", "Indentación de tejido blando en SOFA: fuerza frente a desplazamiento", "在 SOFA 中压入软组织：记录力与位移", "SOFA에서 연조직 압입: 힘과 변위 기록"),
         "summary": ("A warm-up for needle-insertion studies: press on a finite-element tissue block, ramp the force and record how far the surface moves.",
                     "針刺入の研究に入る前の準備運動です。有限要素で作った組織ブロックを押し、力を少しずつ上げながら表面がどれだけ沈むかを記録します。",
                     "Calentamiento para estudios de inserción de agujas: presiona un bloque de tejido de elementos finitos, aumenta la fuerza y registra el desplazamiento.",
                     "针刺入研究的热身：按压有限元组织块，逐步加大力，记录表面下陷多少。",
                     "바늘 삽입 연구 전의 준비 과정입니다. 유한요소 조직 블록을 누르며 힘을 올리고 표면이 얼마나 들어가는지 기록합니다."),
         "input": ("Block size, Young's modulus and Poisson ratio (the defaults are example values for a soft gel phantom), maximum probe force.",
                   "ブロックの寸法、ヤング率とポアソン比（既定値は柔らかいゲルファントムを想定した例の値です）、プローブの最大の力。"),
         "output": ("indent_log.csv — step, applied force (N), downward displacement of the top-centre node (mm).",
                    "indent_log.csv：ステップ、加えた力（N）、上面中央の節点の沈み込み（mm）。"),
         "prereq": ("SOFA v24.06 or later with the SofaPython3 plugin (binary release from the SOFA GitHub page) and the Python version that build expects. Basic familiarity with runSofa.",
                    "SofaPython3プラグイン付きのSOFA v24.06以降（SOFAのGitHubページのバイナリ版）と、そのビルドが想定するPythonのバージョン。runSofaの基本的な操作。"),
         "steps": {"en": ["Install a SOFA binary release and confirm that runSofa opens one of the bundled examples.",
                          "Save the code below as sofa_tissue_indent.py. Component names follow SOFA v24.06; if your version reports an unknown component, look up its current name in the SOFA documentation.",
                          "Run `runSofa -l SofaPython3 sofa_tissue_indent.py` and press Animate. Let it run for at least 400 steps (the force ramp).",
                          "Close runSofa and open indent_log.csv. Plot displacement_mm against force_N.",
                          "Change YOUNG (for example 2500 and 10000) and compare the curves."],
                   "ja": ["SOFAのバイナリ版をインストールし、同梱のサンプルが runSofa で開けることを確認します。",
                          "下のコードを sofa_tissue_indent.py として保存します。コンポーネント名はSOFA v24.06に合わせています。お使いの版で「不明なコンポーネント」と出た場合は、SOFAのドキュメントで現在の名前を確認してください。",
                          "`runSofa -l SofaPython3 sofa_tissue_indent.py` を実行し、Animate を押します。力を上げきる400ステップ以上は動かしてください。",
                          "runSofa を閉じて indent_log.csv を開き、force_N に対する displacement_mm をグラフにします。",
                          "YOUNG を変えて（たとえば2500と10000）、曲線を比べます。"]},
         "expected": ("A displacement curve that rises with the force and levels off once the ramp ends; a stiffer block moves less for the same force. This is linear-elastic indentation only — puncture, friction and needle bending need further models that this recipe deliberately leaves out.",
                      "力とともに沈み込みが増え、力が一定になると落ち着く曲線になります。硬いブロックほど、同じ力での沈み込みは小さくなります。扱っているのは線形弾性の押し込みだけです。穿刺、摩擦、針のたわみには別のモデルが必要で、このレシピではあえて扱っていません。"),
         "next": ("Read the SofaPython3 documentation on controllers, then look at how published needle-insertion work adds puncture and friction before you extend the scene.",
                  "SofaPython3のドキュメントでコントローラーの章を読み、論文などで公開されている針刺入の研究が穿刺や摩擦をどう加えているかを調べてから、シーンを拡張してください。"),
         "next_href": "https://sofapython3.readthedocs.io/en/latest/"},
        {"id": "dicom-deid-audit", "code": "dicom_deid_audit.py",
         "title": ("Check and blank identifying DICOM fields before you share a teaching file", "教材用にDICOMを共有する前に、個人を特定できる項目を確認して消す", "Revisar y vaciar campos identificativos de DICOM antes de compartir un archivo docente", "共享教学用 DICOM 前，检查并清除可识别身份的字段", "교육용 DICOM 공유 전, 식별 가능한 항목 확인 및 삭제"),
         "summary": ("Read a DICOM file, report which identifying fields are present, blank or remove them, strip private tags and save a copy — without ever printing the values.",
                     "DICOMファイルを読み込み、個人を特定できる項目のうちどれが入っているかを報告し、空欄化または削除します。プライベートタグも外してコピーを保存します。値そのものは一度も表示しません。",
                     "Lee un archivo DICOM, informa de los campos identificativos presentes, los vacía o elimina, quita las etiquetas privadas y guarda una copia, sin mostrar nunca los valores.",
                     "读取 DICOM 文件，报告存在哪些可识别字段，清空或删除它们，去掉私有标签并另存一份——全程不显示字段值。",
                     "DICOM 파일을 읽어 식별 가능한 항목이 있는지 보고하고, 비우거나 삭제하며, 사설 태그를 제거한 사본을 저장합니다. 값 자체는 출력하지 않습니다."),
         "input": ("A DICOM file. The default is CT_small.dcm, a public test file that ships with pydicom.",
                   "DICOMファイル。既定では、pydicomに同梱されている公開テストファイル CT_small.dcm を使います。"),
         "output": ("CT_small_deid.dcm (the cleaned copy) and deid_report.csv (field, present before, action taken).",
                    "CT_small_deid.dcm（処理後のコピー）と deid_report.csv（項目、処理前にあったか、行った処理）。"),
         "prereq": ("Python 3.10 or later and `pip install pydicom`. Use only files you are allowed to handle.",
                    "Python 3.10以上と `pip install pydicom`。扱う権限のあるファイルだけを使ってください。"),
         "steps": {"en": ["Save the code below as dicom_deid_audit.py.",
                          "Run `python dicom_deid_audit.py` to process the bundled public test file.",
                          "Open deid_report.csv: every field in the list shows whether it was present and what was done.",
                          "Open CT_small_deid.dcm in a viewer (3D Slicer, for example) and confirm the image is intact.",
                          "Compare the field list with the DICOM PS3.15 Annex E profile and note what it does not cover yet — dates, UIDs and burned-in text in the pixels."],
                   "ja": ["下のコードを dicom_deid_audit.py として保存します。",
                          "`python dicom_deid_audit.py` を実行すると、同梱の公開テストファイルを処理します。",
                          "deid_report.csv を開くと、リストの各項目について、元からあったか、どう処理したかがわかります。",
                          "CT_small_deid.dcm をビューア（3D Slicerなど）で開き、画像が壊れていないことを確かめます。",
                          "項目リストをDICOM PS3.15 Annex Eのプロファイルと見比べ、まだ扱っていないもの（日付、UID、画素に焼き込まれた文字）を書き出します。"]},
         "expected": ("A report and a cleaned copy whose image is unchanged. This is a learning exercise with a short field list, not a complete de-identification tool; real data sharing follows the PS3.15 profiles and your institution's rules.",
                      "レポートと、画像はそのままの処理済みコピーができます。短い項目リストで学ぶための練習で、完全な匿名化ツールではありません。実際のデータ共有は、PS3.15のプロファイルと所属機関のルールに従ってください。"),
         "next": ("Read the DICOM standard's confidentiality profiles and extend the field list; then open the cleaned file in 3D Slicer (next recipe).",
                  "DICOM規格の機密保護プロファイルを読んで項目リストを広げてください。そのあと、処理済みファイルを3D Slicerで開いてみましょう（次のレシピ）。"),
         "next_href": "https://www.dicomstandard.org/"},
        {"id": "slicer-sample-to-stl", "code": None,
         "title": ("From a public CT sample to a 3D model in 3D Slicer", "公開CTサンプルから、3D Slicerで3Dモデルを作る", "De una TC de muestra pública a un modelo 3D en 3D Slicer", "用 3D Slicer 把公开 CT 样例做成 3D 模型", "3D Slicer로 공개 CT 샘플에서 3D 모델 만들기"),
         "summary": ("Load a sample scan that ships with 3D Slicer, segment bone with a threshold, clean it up and export an STL you can print or load into a simulator.",
                     "3D Slicerに付属のサンプル画像を読み込み、しきい値で骨を抽出して整え、印刷やシミュレーターに使えるSTLとして書き出します。",
                     "Carga una exploración de muestra incluida en 3D Slicer, segmenta hueso por umbral, límpialo y exporta un STL para imprimir o simular.",
                     "载入 3D Slicer 自带的样例扫描，用阈值分割骨骼，清理后导出 STL，可用于打印或载入仿真器。",
                     "3D Slicer에 포함된 샘플 스캔을 불러와 임계값으로 뼈를 분할하고 정리한 뒤, 출력하거나 시뮬레이터에 넣을 STL로 내보냅니다."),
         "input": ("The CTChest sample data set from Slicer's Sample Data module (public sample data).",
                   "SlicerのSample Dataモジュールにある CTChest（公開サンプルデータ）。"),
         "output": ("An STL surface mesh of the segmented bone.", "抽出した骨の表面メッシュ（STL）。"),
         "prereq": ("3D Slicer (current stable release) on Windows, macOS or Linux. A mouse helps.",
                    "3D Slicer（最新の安定版。Windows・macOS・Linux）。マウスがあると作業しやすくなります。"),
         "steps": {"en": ["Install the stable release from slicer.org and open it.",
                          "Open the Sample Data module and load CTChest.",
                          "Open Segment Editor, add a segment and choose the Threshold effect. Start from a lower bound around bone intensity, adjust until bone is highlighted, then Apply.",
                          "Use Islands → Keep largest island, then Smoothing (median) to remove specks.",
                          "Click Show 3D to check the surface.",
                          "Export the segment to an STL file (Segmentations → Export to files)."],
                   "ja": ["slicer.org から安定版をインストールして起動します。",
                          "Sample Data モジュールを開き、CTChest を読み込みます。",
                          "Segment Editor でセグメントを追加し、Threshold を選びます。骨の濃度あたりを下限にして始め、骨が強調されるまで調整してから Apply を押します。",
                          "Islands → Keep largest island のあと、Smoothing（median）で細かい点を取り除きます。",
                          "Show 3D で表面の形を確認します。",
                          "セグメントをSTLとして書き出します（Segmentations → Export to files）。"]},
         "expected": ("A rib-cage and spine surface in the 3D view and an STL file on disk. The threshold is a visual choice on sample data, not a measurement.",
                      "3Dビューに胸郭と背骨の表面が表示され、STLファイルが保存されます。しきい値はサンプル画像を見ながら選んだもので、計測値ではありません。"),
         "next": ("Reduce the mesh in a mesh editor and load it as a mesh geom in MuJoCo, or as a collision model in SOFA.",
                  "メッシュ編集ソフトでポリゴン数を減らし、MuJoCoのメッシュや、SOFAの衝突モデルとして読み込んでみてください。"),
         "next_href": "https://slicer.readthedocs.io/en/latest/"},
    ],
    "compare": [
        ("SOFA", "https://github.com/sofa-framework/sofa", ("Soft-tissue and surgical simulation (FEM, contact, haptics)", "軟組織・手術シミュレーション（有限要素、接触、ハプティクス）"), "LGPL-2.1", "advanced", "local"),
        ("MuJoCo", "https://mujoco.org/", ("Fast rigid-body physics for robot control and learning", "ロボット制御・学習向けの高速な剛体物理"), "Apache-2.0", "intermediate", "local"),
        ("PyBullet / Bullet", "https://github.com/bulletphysics/bullet3", ("Robot simulation and reinforcement-learning prototypes", "ロボットシミュレーションと強化学習の試作"), "zlib", "intermediate", "local"),
        ("3D Slicer", "https://www.slicer.org/", ("Medical image viewing, segmentation and 3D models (research)", "医用画像の表示・セグメンテーション・3Dモデル（研究用）"), "BSD-style (3D Slicer License)", "intermediate", "local"),
        ("MONAI", "https://github.com/Project-MONAI/MONAI", ("Deep learning for medical-imaging research (PyTorch)", "医用画像研究向けのディープラーニング（PyTorch）"), "Apache-2.0", "advanced", "gpu"),
        ("pydicom", "https://github.com/pydicom/pydicom", ("Read, inspect and write DICOM files in Python", "PythonでDICOMを読む・調べる・書く"), "MIT", "beginner", "local"),
    ],
    "stack": [
        ("SOFA (GitHub)", "https://github.com/sofa-framework/sofa", "SOFA Consortium / Inria", "LGPL-2.1", ("Open-source framework for real-time physics simulation with a focus on medical simulation.", "医療シミュレーションに強い、リアルタイム物理シミュレーションのオープンソース基盤。")),
        ("SofaPython3 documentation", "https://sofapython3.readthedocs.io/en/latest/", "SOFA Consortium", "LGPL-2.1", ("Python bindings for writing SOFA scenes and controllers.", "SOFAのシーンやコントローラーをPythonで書くためのバインディング。")),
        ("MuJoCo", "https://mujoco.org/", "Google DeepMind", "Apache-2.0", ("Physics engine for robotics and biomechanics research; Python bindings via pip.", "ロボティクスと生体力学の研究向け物理エンジン。Pythonバインディングはpipで入ります。")),
        ("MuJoCo Python bindings docs", "https://mujoco.readthedocs.io/en/stable/python.html", "Google DeepMind", "Apache-2.0", ("How to load models, step the simulation and read state from Python.", "Pythonからモデルを読み込み、シミュレーションを進め、状態を読む方法。")),
        ("3D Slicer", "https://www.slicer.org/", "3D Slicer community", "BSD-style (3D Slicer License)", ("Free platform for medical image computing research; not approved for clinical use.", "医用画像処理研究のための無償プラットフォーム。臨床使用の承認は受けていません。")),
        ("3D Slicer documentation", "https://slicer.readthedocs.io/en/latest/", "3D Slicer community", "BSD-style (3D Slicer License)", ("User guide for Sample Data, Segment Editor and exporting models.", "Sample Data、Segment Editor、モデル書き出しの使い方。")),
        ("MONAI", "https://github.com/Project-MONAI/MONAI", "Project MONAI", "Apache-2.0", ("PyTorch-based framework for deep learning in healthcare imaging research.", "医用画像研究のためのPyTorchベースのディープラーニング基盤。")),
        ("pydicom", "https://github.com/pydicom/pydicom", "pydicom contributors", "MIT", ("Pure-Python package for working with DICOM files.", "DICOMファイルを扱うための純Pythonパッケージ。")),
        ("DICOM Standard", "https://www.dicomstandard.org/", "NEMA / DICOM Standards Committee", "Standard (free to read online)", ("The standard itself, including the PS3.15 confidentiality profiles.", "PS3.15の機密保護プロファイルを含む、DICOM規格そのもの。")),
    ],
    "related": [("/robot-pilot/", ("Robot Pilot Academy — teleoperation practice in simulation", "Robot Pilot Academy：シミュレーションで遠隔操作を練習")),
                ("/library/toolkit/", ("AI agent toolkits (for summarising your logs)", "AIエージェントのツールキット（ログの要約などに）"))],
}

# ---------------------------------------------------------------- Space
F["space"] = {
    "name": ("Space", "宇宙", "Espacio", "航天", "우주"),
    "h1": ("Space: build with public space data", "宇宙：公開データで作る", "Espacio: construir con datos espaciales públicos", "航天：用公开数据动手做", "우주: 공개 우주 데이터로 만들기"),
    "lead": ("Turn NASA, NOAA, CelesTrak and Copernicus data into things you use every day: an asteroid close-approach brief, a satellite pass table for your city, a cloud-free image finder and a space-weather log.",
             "NASA、NOAA、CelesTrak、Copernicusのデータを、日常で使えるものに変えます。小惑星の接近ブリーフ、自分の街での衛星通過表、雲の少ない衛星画像の探し方、宇宙天気の記録です。",
             "Convierte datos de NASA, NOAA, CelesTrak y Copernicus en herramientas diarias: un informe de aproximaciones de asteroides, pasos de satélites sobre tu ciudad, un buscador de imágenes sin nubes y un registro de clima espacial.",
             "把 NASA、NOAA、CelesTrak 和 Copernicus 的数据变成日常可用的东西：小行星近地简报、你所在城市的卫星过境表、少云卫星影像查找器和空间天气日志。",
             "NASA, NOAA, CelesTrak, Copernicus 데이터를 매일 쓰는 도구로 바꿉니다. 소행성 근접 브리핑, 우리 도시 위성 통과표, 구름 없는 위성 영상 찾기, 우주 날씨 기록."),
    "notice": None,
    "recipes": [
        {"id": "neo-close-approach-brief", "code": "neo_brief.py",
         "title": ("Daily close-approach brief for near-Earth objects (with an optional AI summary)", "地球に近づく小天体の接近ブリーフを毎日作る（AI要約は任意）", "Informe diario de aproximaciones de objetos cercanos a la Tierra (resumen IA opcional)", "每日近地天体接近简报（可选 AI 摘要）", "근지구 천체 일일 근접 브리핑 (AI 요약 선택)"),
         "summary": ("Pull NASA/JPL close-approach data for the coming week and write a clean Markdown table you can read in a minute or hand to an AI agent.",
                     "NASA／JPLの接近データを今後1週間ぶん取得し、1分で読める、AIエージェントにも渡しやすいMarkdownの表にまとめます。",
                     "Descarga los datos de aproximaciones de NASA/JPL de la próxima semana y genera una tabla Markdown que se lee en un minuto o se pasa a un agente de IA.",
                     "获取 NASA/JPL 未来一周的接近数据，写成一分钟就能读完、也方便交给 AI 智能体的 Markdown 表格。",
                     "NASA/JPL의 다음 주 근접 데이터를 받아 1분이면 읽을 수 있고 AI 에이전트에도 넘기기 쉬운 Markdown 표로 정리합니다."),
         "input": ("Start date (default today, UTC), days ahead (default 7), distance limit in au (default 0.05). No API key.",
                   "開始日（既定は今日・UTC）、何日先まで（既定7日）、距離の上限（au、既定0.05）。APIキーは不要です。"),
         "output": ("neo_brief_<date>.md (closest first: distance in km and lunar distances, speed, absolute magnitude H) and neo_brief_<date>.json.",
                    "neo_brief_<日付>.md（近い順。距離はkmと月までの距離の何倍か、速度、絶対等級H）と neo_brief_<日付>.json。"),
         "prereq": ("Python 3.10 or later; standard library only.", "Python 3.10以上。標準ライブラリだけで動きます。"),
         "steps": {"en": ["Save the code below as neo_brief.py.",
                          "Run `python neo_brief.py` (or `python neo_brief.py 2026-10-10 14` for another window).",
                          "Open the .md file; check one object on JPL's Small-Body Database before quoting it anywhere.",
                          "Optional AI step: pass the Markdown to a local model, for example `ollama run llama3.2 \"Summarise this table in three plain sentences. Do not add facts.\" < neo_brief_<date>.md`.",
                          "Schedule it (cron or Task Scheduler) to get a fresh brief every morning."],
                   "ja": ["下のコードを neo_brief.py として保存します。",
                          "`python neo_brief.py` を実行します（期間を変えるなら `python neo_brief.py 2026-10-10 14`）。",
                          ".md ファイルを開きます。どこかで引用する前に、少なくとも1天体はJPLのSmall-Body Databaseで確認してください。",
                          "AIで要約する場合（任意）：Markdownをローカルモデルに渡します。例：`ollama run llama3.2 \"この表を平易な3文で要約してください。事実を付け足さないでください。\" < neo_brief_<日付>.md`",
                          "cronやタスクスケジューラに登録すると、毎朝新しいブリーフが届きます。"]},
         "expected": ("A table of every approach inside the distance limit, closest first. Size is not published for most small objects, so the brief says so instead of guessing.",
                      "距離の上限内に入る接近がすべて、近い順に並んだ表になります。小さな天体の多くは大きさが公表されていないため、推測で埋めずに「未公表」と書きます。"),
         "next": ("Add a check against JPL's Sentry impact-risk table for any object in your brief, or post the brief to your own channel with an AI agent from BSV's toolkit list.",
                  "ブリーフに載った天体についてJPLのSentry（衝突リスク表）も確認する処理を足すか、BSVのツールキット一覧にあるAIエージェントで、ご自身のチャンネルに投稿する仕組みにしてみてください。"),
         "next_href": "/library/toolkit/", "untested_parts": ("The optional AI-summary step was not run by BSV.", "任意のAI要約の手順は、BSVでは実行していません。")},
        {"id": "satellite-pass-table", "code": "iss_passes.py",
         "title": ("When can you see the ISS? A pass table for your city", "ISSはいつ見える？自分の街の通過予報表を作る", "¿Cuándo se ve la ISS? Tabla de pasos para tu ciudad", "什么时候能看到国际空间站？做一张你所在城市的过境表", "ISS는 언제 보일까? 우리 도시 통과표 만들기"),
         "summary": ("Fetch fresh orbital elements from CelesTrak and let Skyfield compute rise, highest point and set times above your location, with a sunlit flag.",
                     "CelesTrakから最新の軌道要素を取得し、Skyfieldで自分のいる場所の上を昇る・最も高くなる・沈む時刻を計算します。太陽光が当たっているかも表示します。",
                     "Obtén elementos orbitales recientes de CelesTrak y deja que Skyfield calcule salida, culminación y puesta sobre tu ubicación, con indicador de iluminación solar.",
                     "从 CelesTrak 获取最新轨道根数，用 Skyfield 计算卫星在你上空升起、最高点和落下的时间，并标出是否被阳光照亮。",
                     "CelesTrak에서 최신 궤도 요소를 받아 Skyfield로 내 위치 위로 뜨고, 가장 높아지고, 지는 시각을 계산합니다. 햇빛을 받는지도 표시합니다."),
         "input": ("NORAD catalogue number (default 25544, the ISS), latitude, longitude, hours ahead.", "NORADカタログ番号（既定は25544＝ISS）、緯度、経度、何時間先まで。"),
         "output": ("passes_<number>.csv with rise / culmination / set times in UTC, maximum elevation and a sunlit flag.", "passes_<番号>.csv：昇る・最高点・沈む時刻（UTC）、最大仰角、太陽光が当たっているか。"),
         "prereq": ("Python 3.10 or later and `pip install skyfield`. The first run downloads a 17 MB planetary ephemeris for the sunlit flag.",
                    "Python 3.10以上と `pip install skyfield`。初回は、日照判定のために17 MBの惑星暦をダウンロードします。"),
         "steps": {"en": ["Save the code below as iss_passes.py.",
                          "Run it for your location, for example Tokyo: `python iss_passes.py 25544 35.68 139.77 48`.",
                          "Open the CSV. Passes high in the sky while you are in darkness and the satellite is sunlit are the ones worth going outside for.",
                          "Convert the UTC times to your time zone when you share them.",
                          "Try another object by its NORAD number, such as the Hubble Space Telescope (20580)."],
                   "ja": ["下のコードを iss_passes.py として保存します。",
                          "自分の場所で実行します。東京なら `python iss_passes.py 25544 35.68 139.77 48`。",
                          "CSVを開きます。自分の側は暗く、衛星には日が当たっていて、しかも高く昇る通過が、外に出て見る価値のある回です。",
                          "人に伝えるときは、UTCの時刻を現地時間に直してください。",
                          "NORAD番号を変えれば別の衛星も試せます。例：ハッブル宇宙望遠鏡（20580）。"]},
         "expected": ("A short list of passes for the next hours with times and elevations. The script also prints the age of the orbital elements; predictions drift as they get older, so refresh daily.",
                      "今後数時間の通過が、時刻と仰角つきで数件並びます。軌道要素の古さも表示します。要素が古くなるほど予報はずれていくので、毎日取り直してください。"),
         "next": ("Turn the CSV into calendar reminders, or combine it with the Sentinel-2 recipe to see what a satellite actually photographed over your area.",
                  "CSVをカレンダーの通知にしたり、次のSentinel-2のレシピと組み合わせて、衛星が実際に自分の地域で何を撮ったかを見たりできます。"),
         "next_href": "https://rhodesmill.org/skyfield/"},
        {"id": "sentinel2-scene-finder", "code": "s2_scene_finder.py",
         "title": ("Find a cloud-free Sentinel-2 image of your area", "自分の地域の、雲の少ないSentinel-2画像を探す", "Encuentra una imagen Sentinel-2 sin nubes de tu zona", "查找你所在地区少云的 Sentinel-2 影像", "우리 지역의 구름 적은 Sentinel-2 영상 찾기"),
         "summary": ("Search the public Earth Search STAC catalogue for Sentinel-2 scenes over a bounding box, sorted by cloud cover, with direct links to the preview and the true-colour image.",
                     "公開されているEarth SearchのSTACカタログで、指定した範囲のSentinel-2画像を探し、雲の少ない順に並べます。プレビューとトゥルーカラー画像への直接リンクもつけます。",
                     "Busca escenas Sentinel-2 sobre un recuadro en el catálogo STAC público Earth Search, ordenadas por nubosidad, con enlaces directos a la vista previa y a la imagen en color real.",
                     "在公开的 Earth Search STAC 目录中按范围搜索 Sentinel-2 影像，按云量排序，并附上预览图和真彩色影像的直接链接。",
                     "공개 Earth Search STAC 카탈로그에서 지정 범위의 Sentinel-2 장면을 구름 적은 순으로 찾고, 미리보기와 트루컬러 영상 링크를 붙입니다."),
         "input": ("Bounding box (min lon, min lat, max lon, max lat), date range, maximum cloud cover %.", "範囲（最小経度、最小緯度、最大経度、最大緯度）、期間、雲量の上限（%）。"),
         "output": ("scenes.csv: scene id, date, cloud %, preview URL, true-colour Cloud-Optimised GeoTIFF URL.", "scenes.csv：シーンID、日付、雲量（%）、プレビューのURL、トゥルーカラーのCloud-Optimised GeoTIFFのURL。"),
         "prereq": ("Python 3.10 or later and `pip install pystac-client`. No account needed for searching.", "Python 3.10以上と `pip install pystac-client`。検索だけならアカウントは不要です。"),
         "steps": {"en": ["Save the code below as s2_scene_finder.py.",
                          "Run it for your area: `python s2_scene_finder.py 139.70,35.62,139.82,35.72 2026-08-01/2026-09-30 20`.",
                          "Open the preview URL of the first row to check the scene by eye.",
                          "Open the visual COG URL in QGIS (Layer → Add Raster Layer → protocol HTTP) to view it at full resolution without downloading the whole file.",
                          "Widen the date range or raise the cloud limit if nothing comes back."],
                   "ja": ["下のコードを s2_scene_finder.py として保存します。",
                          "自分の地域で実行します：`python s2_scene_finder.py 139.70,35.62,139.82,35.72 2026-08-01/2026-09-30 20`。",
                          "1行目のプレビューURLを開いて、画像を目で確かめます。",
                          "visualのCOGのURLをQGISで開くと（レイヤ → ラスタレイヤを追加 → プロトコル HTTP）、ファイル全体をダウンロードせずに高解像度で見られます。",
                          "何も見つからないときは、期間を広げるか、雲量の上限を上げてください。"]},
         "expected": ("A CSV of matching scenes, least cloudy first. In a rainy season the list can be short; that is the data, not a bug.",
                      "条件に合うシーンが、雲の少ない順にCSVで並びます。雨の多い季節は件数が少なくなることがありますが、それはデータの事情で、不具合ではありません。"),
         "next": ("Compare two dates of the same place to see change, or move on to Copernicus Data Space Ecosystem for processing in the cloud.",
                  "同じ場所の2つの日付を比べて変化を見るか、Copernicus Data Space Ecosystemに移ってクラウド上で処理してみてください。"),
         "next_href": "https://dataspace.copernicus.eu/"},
        {"id": "kp-storm-watch", "code": "kp_watch.py",
         "title": ("A geomagnetic storm watch log from the Kp index", "Kp指数で、磁気嵐の見張りログを作る", "Registro de vigilancia de tormentas geomagnéticas con el índice Kp", "用 Kp 指数做地磁暴监测日志", "Kp 지수로 지자기 폭풍 감시 로그 만들기"),
         "summary": ("Read NOAA SWPC's planetary K-index feed, append new 3-hour readings to a CSV and flag anything at storm level.",
                     "NOAA SWPCの惑星K指数フィードを読み、3時間ごとの新しい値をCSVに追記して、嵐のレベルに達したものに印をつけます。",
                     "Lee el feed del índice K planetario de NOAA SWPC, añade las lecturas trihorarias nuevas a un CSV y marca las de nivel de tormenta.",
                     "读取 NOAA SWPC 的行星 K 指数数据，把新的三小时读数追加到 CSV，并标出达到暴级的记录。",
                     "NOAA SWPC의 행성 K 지수 피드를 읽어 3시간 단위 새 값을 CSV에 추가하고 폭풍 수준에 표시합니다."),
         "input": ("Threshold Kp (default 5, the level NOAA's space weather scales call a G1 minor storm).", "しきい値のKp（既定は5。NOAAの宇宙天気スケールでG1＝小規模な磁気嵐にあたる水準）。"),
         "output": ("kp_log.csv (time, Kp), growing with each run, plus printed lines for readings at or above the threshold.", "kp_log.csv（時刻、Kp）。実行するたびに追記され、しきい値以上の値は画面にも表示します。"),
         "prereq": ("Python 3.10 or later; standard library only.", "Python 3.10以上。標準ライブラリだけで動きます。"),
         "steps": {"en": ["Save the code below as kp_watch.py.",
                          "Run `python kp_watch.py` once to create kp_log.csv.",
                          "Schedule it every 3 hours; only new readings are added.",
                          "Plot the CSV to see quiet and stormy periods; compare them with aurora reports or GNSS issues you noticed.",
                          "Lower the threshold to 4 if you want early notice."],
                   "ja": ["下のコードを kp_watch.py として保存します。",
                          "`python kp_watch.py` を一度実行して kp_log.csv を作ります。",
                          "3時間ごとに実行するよう登録します。追記されるのは新しい値だけです。",
                          "CSVをグラフにして、静かな時期と荒れた時期を見比べます。オーロラの報告や、気づいたGNSSの不調と照らし合わせるのもおすすめです。",
                          "早めに知りたい場合は、しきい値を4に下げてください。"]},
         "expected": ("A growing log of real readings. Whether any line crosses the threshold depends entirely on the Sun that week.",
                      "実際の観測値が積み重なっていくログになります。しきい値を超える行が出るかどうかは、その週の太陽の活動しだいです。"),
         "next": ("Read NOAA's explanation of the Kp index and the G-scale, then add the solar-wind feeds from the same service.",
                  "NOAAによるKp指数とGスケールの解説を読み、同じサービスの太陽風のデータも追加してみてください。"),
         "next_href": "https://www.spaceweather.gov/products/planetary-k-index"},
    ],
    "compare": [
        ("JPL SBDB Close-Approach Data API", "https://ssd-api.jpl.nasa.gov/doc/cad.html", ("Asteroid and comet close approaches", "小惑星・彗星の接近データ"), "US Government public data (NASA/JPL)", "beginner", "cloud"),
        ("NASA APIs (NeoWs and others)", "https://api.nasa.gov/", ("Public NASA data APIs; free key", "NASAの公開データAPI（無料のキー）"), "US Government public data (NASA)", "beginner", "cloud"),
        ("CelesTrak GP data", "https://celestrak.org/NORAD/documentation/gp-data-formats.php", ("Current orbital elements for satellites", "人工衛星の最新軌道要素"), "Free public data (CelesTrak terms)", "beginner", "cloud"),
        ("Skyfield", "https://rhodesmill.org/skyfield/", ("Positions of stars, planets and satellites; pass prediction", "恒星・惑星・人工衛星の位置計算と通過予報"), "MIT", "beginner", "local"),
        ("Astropy", "https://www.astropy.org/", ("Core astronomy library: time, coordinates, units, FITS", "天文学の基本ライブラリ（時刻、座標、単位、FITS）"), "BSD-3-Clause", "intermediate", "local"),
        ("pystac-client + Earth Search", "https://github.com/stac-utils/pystac-client", ("Search satellite imagery catalogues (STAC)", "衛星画像カタログ（STAC）の検索"), "Apache-2.0 (client); Copernicus terms (data)", "intermediate", "both"),
        ("NASA GMAT", "https://software.nasa.gov/software/GSC-17177-1", ("Mission design and trajectory optimisation", "ミッション設計と軌道最適化"), "Open source (NASA Software Catalog)", "advanced", "local"),
    ],
    "stack": [
        ("JPL SBDB Close-Approach Data API", "https://ssd-api.jpl.nasa.gov/doc/cad.html", "NASA Jet Propulsion Laboratory", "US Government public data", ("Documented JSON API for close approaches of asteroids and comets.", "小惑星・彗星の接近データを返すJSON API（仕様書つき）。")),
        ("CNEOS", "https://cneos.jpl.nasa.gov/", "NASA/JPL Center for Near Earth Object Studies", "US Government public data", ("NASA's centre for near-Earth object orbits, close approaches and impact-risk tables.", "地球近傍天体の軌道、接近、衝突リスク表を扱うNASAのセンター。")),
        ("NASA APIs", "https://api.nasa.gov/", "NASA", "US Government public data", ("Portal for NASA's public APIs, including NeoWs; free API key.", "NeoWsなど、NASAの公開APIの入口。APIキーは無料。")),
        ("Skyfield", "https://rhodesmill.org/skyfield/", "Brandon Rhodes / Skyfield contributors", "MIT", ("Python astronomy library used here for satellite passes.", "このページで衛星の通過計算に使っているPythonの天文ライブラリ。")),
        ("CelesTrak GP data formats", "https://celestrak.org/NORAD/documentation/gp-data-formats.php", "CelesTrak", "Free public data (CelesTrak terms)", ("How to query current orbital elements by catalogue number, in TLE, JSON or CSV.", "カタログ番号で最新の軌道要素をTLE・JSON・CSVで取得する方法。")),
        ("Earth Search", "https://element84.com/earth-search/", "Element 84", "Free STAC API; Copernicus data terms", ("Public STAC API over Sentinel and Landsat data on AWS Open Data.", "AWS Open Data上のSentinelやLandsatを検索できる公開STAC API。")),
        ("Sentinel-2 COGs on AWS", "https://registry.opendata.aws/sentinel-2-l2a-cogs/", "AWS Open Data / Element 84", "Copernicus Sentinel data terms", ("Registry entry for the Cloud-Optimised GeoTIFF Sentinel-2 archive.", "Sentinel-2のCloud-Optimised GeoTIFFアーカイブの登録ページ。")),
        ("Copernicus Data Space Ecosystem", "https://dataspace.copernicus.eu/", "European Commission / ESA", "Free access with registration", ("Official Copernicus portal for browsing, downloading and processing Sentinel data.", "Sentinelデータの閲覧・ダウンロード・処理ができるCopernicusの公式ポータル。")),
        ("NOAA SWPC planetary K-index", "https://www.spaceweather.gov/products/planetary-k-index", "NOAA Space Weather Prediction Center", "US Government public data", ("What the Kp index means, with links to the live data feeds.", "Kp指数の意味と、リアルタイムのデータへのリンク。")),
    ],
    "related": [("/library/toolkit/", ("AI agent toolkits (for the optional summary step)", "AIエージェントのツールキット（任意の要約手順に）")),
                ("/library/workflows/", ("Workflow templates to schedule and chain these scripts", "スクリプトを定期実行・連結するためのワークフロー"))],
}

# ---------------------------------------------------------------- Biotech
F["biotech"] = {
    "name": ("Biotech", "バイオ", "Biotecnología", "生物技术", "바이오"),
    "h1": ("Biotech: open data, real tools, reproducible steps", "バイオ：公開データと実在のツールで、再現できる手順を", "Biotecnología: datos abiertos, herramientas reales, pasos reproducibles", "生物技术：公开数据、真实工具、可复现的步骤", "바이오: 공개 데이터, 실제 도구, 재현 가능한 단계"),
    "lead": ("Screen known actives with RDKit, check how far an AlphaFold model can be trusted, profile a protein from UniProt and keep up with PubMed — each in a few commands you can rerun.",
             "RDKitで既知の活性化合物をふるい分け、AlphaFoldのモデルをどこまで信頼できるかを確かめ、UniProtからタンパク質の特徴をまとめ、PubMedの新着を追います。どれも数コマンドで、何度でもやり直せます。",
             "Filtra compuestos activos con RDKit, comprueba cuánto fiarte de un modelo de AlphaFold, perfila una proteína de UniProt y sigue PubMed, con pocos comandos repetibles.",
             "用 RDKit 筛选已知活性化合物，判断 AlphaFold 模型的可信程度，从 UniProt 生成蛋白质概况，并跟进 PubMed——每项只需几条可重复运行的命令。",
             "RDKit로 알려진 활성 화합물을 거르고, AlphaFold 모델의 신뢰 범위를 확인하고, UniProt로 단백질 특성을 정리하고, PubMed를 따라갑니다. 모두 다시 실행할 수 있는 몇 개의 명령입니다."),
    "notice": ("For research and learning. Calculated properties and predicted structures are not evidence of efficacy or safety.",
               "研究と学習のための内容です。計算で求めた性質や予測構造は、有効性や安全性の根拠にはなりません。",
               "Para investigación y aprendizaje. Las propiedades calculadas y las estructuras predichas no demuestran eficacia ni seguridad.",
               "供研究与学习使用。计算得到的性质和预测结构不能作为有效性或安全性的证据。",
               "연구와 학습용입니다. 계산된 성질과 예측 구조는 효능이나 안전성의 근거가 아닙니다."),
    "recipes": [
        {"id": "chembl-rdkit-screen", "code": "chembl_screen.py",
         "title": ("Drug-likeness screen of known actives with ChEMBL and RDKit", "ChEMBLとRDKitで、既知の活性化合物の薬らしさをふるい分ける", "Cribado de semejanza a fármaco de activos conocidos con ChEMBL y RDKit", "用 ChEMBL 和 RDKit 对已知活性化合物做类药性筛选", "ChEMBL과 RDKit로 알려진 활성 화합물의 약물 유사성 선별"),
         "summary": ("Pull potent compounds for one target from ChEMBL, compute standard descriptors and QED with RDKit, and rank them with a rule-of-five flag.",
                     "ChEMBLから1つの標的に対して強い活性を持つ化合物を取得し、RDKitで代表的な記述子とQEDを計算して、Rule of Fiveの判定つきで並べます。",
                     "Descarga compuestos potentes para una diana desde ChEMBL, calcula descriptores y QED con RDKit y ordénalos con la regla de cinco.",
                     "从 ChEMBL 获取针对某一靶点的强活性化合物，用 RDKit 计算常用描述符和 QED，并按五规则标记排序。",
                     "ChEMBL에서 한 표적에 강한 활성을 보이는 화합물을 받아 RDKit로 기술자와 QED를 계산하고 5의 법칙 판정과 함께 정렬합니다."),
         "input": ("ChEMBL target id (default CHEMBL203, EGFR), minimum pChEMBL value (default 7), number of compounds.",
                   "ChEMBLの標的ID（既定はCHEMBL203＝EGFR）、pChEMBL値の下限（既定7）、化合物の数。"),
         "output": ("screen_<target>.csv: MW, cLogP, H-bond donors and acceptors, TPSA, rotatable bonds, QED, rule-of-five violations and pass flag, SMILES.",
                    "screen_<標的>.csv：分子量、cLogP、水素結合ドナー・アクセプター数、TPSA、回転可能結合数、QED、Rule of Fiveの違反数と判定、SMILES。"),
         "prereq": ("Python 3.10 or later and `pip install rdkit`. The public ChEMBL API can be slow; the script retries.", "Python 3.10以上と `pip install rdkit`。公開されているChEMBLのAPIは遅いことがあるため、スクリプトは自動で再試行します。"),
         "steps": {"en": ["Save the code below as chembl_screen.py.",
                          "Run `python chembl_screen.py CHEMBL203 7 60`.",
                          "Open the CSV, sort by QED and look at the structures of the top rows (paste a SMILES into any structure viewer).",
                          "Change the target id to one you study; find ids by searching the ChEMBL website.",
                          "Keep the CSV with the date: ChEMBL releases change the data."],
                   "ja": ["下のコードを chembl_screen.py として保存します。",
                          "`python chembl_screen.py CHEMBL203 7 60` を実行します。",
                          "CSVを開いてQEDで並べ替え、上位の構造を見てみます（SMILESを構造ビューアに貼り付けます）。",
                          "標的IDを、ご自身が扱っているものに変えます。IDはChEMBLのサイトで検索すると見つかります。",
                          "CSVは日付つきで保存してください。ChEMBLは版が変わるとデータも変わります。"]},
         "expected": ("Most potent, published actives pass the rule of five; the useful part is seeing which ones do not and why. Rule of five and QED are rough filters, not predictions.",
                      "公表されている強い活性化合物の多くはRule of Fiveを満たします。役に立つのは、満たさないものがどれで、なぜかを見ることです。Rule of FiveもQEDも大まかなふるいで、予測ではありません。"),
         "next": ("Check the target's predicted structure confidence before any docking idea (the next recipe uses the same target, EGFR, UniProt P00533).",
                  "ドッキングなどを考える前に、標的の予測構造の信頼度を確かめてください（次のレシピでは同じEGFR、UniProt P00533を使います）。"),
         "next_href": "#afdb-confidence-bands"},
        {"id": "afdb-confidence-bands", "code": "afdb_confidence.py",
         "title": ("How far can you trust an AlphaFold model? Confidence per residue", "AlphaFoldのモデルはどこまで信頼できる？残基ごとの信頼度を見る", "¿Cuánto fiarte de un modelo de AlphaFold? Confianza por residuo", "AlphaFold 模型可信到什么程度？逐残基看置信度", "AlphaFold 모델은 어디까지 믿을 수 있나? 잔기별 신뢰도"),
         "summary": ("Download a predicted structure from AlphaFold DB, read the per-residue pLDDT and summarise it in the database's own four confidence bands, with low-confidence stretches listed.",
                     "AlphaFold DBから予測構造をダウンロードし、残基ごとのpLDDTを読み取って、データベースが定める4段階の信頼度帯でまとめます。信頼度の低い区間も一覧にします。",
                     "Descarga una estructura predicha de AlphaFold DB, lee el pLDDT por residuo y resúmelo en las cuatro bandas de confianza de la base de datos, con los tramos de baja confianza.",
                     "从 AlphaFold DB 下载预测结构，读取逐残基 pLDDT，按数据库自身的四个置信区间汇总，并列出低置信区段。",
                     "AlphaFold DB에서 예측 구조를 받아 잔기별 pLDDT를 읽고, 데이터베이스의 4단계 신뢰 구간으로 요약하며 낮은 신뢰 구간을 나열합니다."),
         "input": ("UniProt accession (default P00533, human EGFR).", "UniProtのアクセッション番号（既定はP00533＝ヒトEGFR）。"),
         "output": ("afdb_<acc>.pdb, afdb_<acc>_confidence.csv (residue, amino acid, pLDDT, band) and a printed band summary.", "afdb_<番号>.pdb、afdb_<番号>_confidence.csv（残基番号、アミノ酸、pLDDT、信頼度帯）と、信頼度帯のまとめ。"),
         "prereq": ("Python 3.10 or later; standard library only.", "Python 3.10以上。標準ライブラリだけで動きます。"),
         "steps": {"en": ["Save the code below as afdb_confidence.py.",
                          "Run `python afdb_confidence.py P00533`.",
                          "Read the band summary: very high (pLDDT ≥ 90), confident (70–90), low (50–70), very low (< 50).",
                          "Open the PDB in a viewer (for example Mol* on rcsb.org) coloured by B-factor; the low stretches are usually flexible or disordered regions.",
                          "Before using a region for docking or design, check whether an experimental structure exists in the PDB."],
                   "ja": ["下のコードを afdb_confidence.py として保存します。",
                          "`python afdb_confidence.py P00533` を実行します。",
                          "信頼度帯のまとめを読みます：とても高い（pLDDT 90以上）、高い（70〜90）、低い（50〜70）、とても低い（50未満）。",
                          "PDBファイルをビューア（rcsb.org のMol*など）でB因子に基づいて色分けして開きます。信頼度の低い区間は、たいてい柔軟な部分や構造をとらない部分です。",
                          "ある領域をドッキングや設計に使う前に、PDBに実験構造があるかを確認してください。"]},
         "expected": ("A per-residue table and a band summary. For a large multi-domain protein, expect well-predicted domains next to long low-confidence tails — a map of where the model is useful.",
                      "残基ごとの表と、信頼度帯のまとめができます。大きなマルチドメインタンパク質では、よく予測されたドメインの隣に、信頼度の低い長い末端が続くのが普通です。モデルがどこで役に立つかを示す地図になります。"),
         "next": ("Look up experimental structures of the same protein on RCSB PDB and compare.", "同じタンパク質の実験構造をRCSB PDBで探し、比べてみてください。"),
         "next_href": "https://www.rcsb.org/"},
        {"id": "uniprot-protein-profile", "code": "uniprot_profile.py",
         "title": ("One-page protein profile from UniProt", "UniProtから、タンパク質の特徴を1ページにまとめる", "Perfil de proteína en una página desde UniProt", "从 UniProt 生成一页蛋白质概况", "UniProt로 단백질 특성 한 페이지 정리"),
         "summary": ("Fetch a sequence from UniProt and compute length, molecular weight, theoretical pI, hydropathy, instability index and aromaticity with Biopython.",
                     "UniProtから配列を取得し、Biopythonで長さ、分子量、理論等電点、疎水性、不安定性指数、芳香族性を計算します。",
                     "Obtén una secuencia de UniProt y calcula longitud, peso molecular, pI teórico, hidropatía, índice de inestabilidad y aromaticidad con Biopython.",
                     "从 UniProt 获取序列，用 Biopython 计算长度、分子量、理论等电点、亲疏水性、不稳定指数和芳香性。",
                     "UniProt에서 서열을 받아 Biopython으로 길이, 분자량, 이론 등전점, 소수성, 불안정성 지수, 방향족성을 계산합니다."),
         "input": ("UniProt accession (default P69905, human haemoglobin subunit alpha).", "UniProtのアクセッション番号（既定はP69905＝ヒトヘモグロビンαサブユニット）。"),
         "output": ("profile_<acc>.md with the six values and the source.", "profile_<番号>.md（6つの値と出典）。"),
         "prereq": ("Python 3.10 or later and `pip install biopython`.", "Python 3.10以上と `pip install biopython`。"),
         "steps": {"en": ["Save the code below as uniprot_profile.py.", "Run `python uniprot_profile.py P69905`.",
                          "Compare with the same protein on the Expasy ProtParam web tool; the methods are the same, so values should agree closely.",
                          "Loop over a list of accessions to build a comparison table."],
                   "ja": ["下のコードを uniprot_profile.py として保存します。", "`python uniprot_profile.py P69905` を実行します。",
                          "同じタンパク質をExpasyのProtParam（Webツール）でも計算して比べます。手法が同じなので、値はほぼ一致するはずです。",
                          "アクセッション番号のリストをループで回すと、比較表が作れます。"]},
         "expected": ("A short Markdown profile. These are sequence-based calculations, not measurements; the instability index in particular is only a rough guide.",
                      "短いMarkdownのプロフィールができます。配列からの計算値であって実測値ではありません。とくに不安定性指数は大まかな目安です。"),
         "next": ("Feed the accession into the AlphaFold recipe above to add structure confidence to the profile.", "同じアクセッション番号を上のAlphaFoldのレシピに渡し、構造の信頼度もプロフィールに加えてみてください。"),
         "next_href": "#afdb-confidence-bands"},
        {"id": "pubmed-weekly-digest", "code": "pubmed_digest.py",
         "title": ("Weekly PubMed digest for your topic, ready for an AI summary", "自分のテーマのPubMed週報を作る（AI要約にも使える形で）", "Resumen semanal de PubMed sobre tu tema, listo para un resumen con IA", "为你的主题生成 PubMed 周报，方便交给 AI 摘要", "내 주제의 PubMed 주간 다이제스트 (AI 요약용)"),
         "summary": ("Query PubMed through NCBI E-utilities for the last seven days and write a linked Markdown list you can skim or hand to an AI agent.",
                     "NCBIのE-utilitiesでPubMedを直近7日ぶん検索し、リンクつきのMarkdownリストにします。ざっと眺めるのにも、AIエージェントに渡すのにも使えます。",
                     "Consulta PubMed con NCBI E-utilities para los últimos siete días y genera una lista Markdown enlazada para leer o pasar a un agente de IA.",
                     "通过 NCBI E-utilities 检索最近七天的 PubMed，生成带链接的 Markdown 列表，可以快速浏览，也可交给 AI 智能体。",
                     "NCBI E-utilities로 최근 7일 PubMed를 검색해 링크가 달린 Markdown 목록을 만듭니다. 훑어보거나 AI 에이전트에 넘길 수 있습니다."),
         "input": ("A PubMed query, days back (default 7), maximum papers (default 20). Set NCBI_EMAIL as NCBI asks; an NCBI API key is optional.",
                   "PubMedの検索式、何日さかのぼるか（既定7日）、最大件数（既定20件）。NCBIの求めに従って NCBI_EMAIL を設定してください。APIキーは任意です。"),
         "output": ("digest_<date>.md: title, journal, publication date and PubMed link for each paper.", "digest_<日付>.md：論文ごとのタイトル、掲載誌、出版日、PubMedへのリンク。"),
         "prereq": ("Python 3.10 or later; standard library only. Keep within NCBI's request-rate guidance.", "Python 3.10以上。標準ライブラリだけで動きます。NCBIが定めるリクエスト頻度の目安を守ってください。"),
         "steps": {"en": ["Save the code below as pubmed_digest.py.",
                          "Run `NCBI_EMAIL=you@example.com python pubmed_digest.py \"AlphaFold protein structure\" 7 20`.",
                          "Skim the list and open the abstracts that matter.",
                          "Optional AI step: give the Markdown to a local model and ask for grouping by topic, with the instruction not to add facts.",
                          "Schedule it weekly and keep the files: they become your reading log."],
                   "ja": ["下のコードを pubmed_digest.py として保存します。",
                          "`NCBI_EMAIL=you@example.com python pubmed_digest.py \"AlphaFold protein structure\" 7 20` を実行します。",
                          "リストにざっと目を通し、気になる論文のアブストラクトを開きます。",
                          "AIを使う場合（任意）：Markdownをローカルモデルに渡し、「事実を付け足さないこと」と指示したうえで、テーマごとに分けてもらいます。",
                          "毎週実行するよう登録し、ファイルを残していくと、そのまま読書記録になります。"]},
         "expected": ("A dated list of recent papers with working links. Search terms matter: refine the query until the list matches what you actually follow.",
                      "最近の論文が、日付つき・リンクつきで並びます。結果は検索語しだいなので、普段追っている内容と合うまで検索式を調整してください。"),
         "next": ("Chain it with an agent workflow from BSV's library to post the digest where your team reads.", "BSVのライブラリにあるエージェントのワークフローとつなげて、チームが読む場所に週報を届けてみてください。"),
         "next_href": "/library/workflows/", "untested_parts": ("The optional AI-summary step was not run by BSV.", "任意のAI要約の手順は、BSVでは実行していません。")},
    ],
    "compare": [
        ("RDKit", "https://www.rdkit.org/", ("Cheminformatics: descriptors, fingerprints, substructure search", "ケモインフォマティクス（記述子、フィンガープリント、部分構造検索）"), "BSD-3-Clause", "intermediate", "local"),
        ("ChEMBL web services", "https://chembl.gitbook.io/chembl-interface-documentation/web-services/chembl-data-web-services", ("Bioactivity data for drug-like molecules", "薬らしい分子の生物活性データ"), "CC BY-SA 3.0 (data)", "beginner", "cloud"),
        ("AlphaFold DB", "https://alphafold.ebi.ac.uk/", ("Predicted protein structures with confidence scores", "信頼度スコアつきのタンパク質予測構造"), "CC BY 4.0 (data)", "beginner", "cloud"),
        ("UniProt REST API", "https://www.uniprot.org/help/api", ("Protein sequences and functional annotation", "タンパク質の配列と機能注釈"), "CC BY 4.0 (data)", "beginner", "cloud"),
        ("Biopython", "https://biopython.org/", ("Sequences, structures and bioinformatics file formats", "配列・構造・バイオインフォマティクスのファイル形式"), "Biopython License / BSD-3-Clause", "beginner", "local"),
        ("NCBI E-utilities", "https://www.ncbi.nlm.nih.gov/books/NBK25501/", ("Programmatic access to PubMed and other NCBI databases", "PubMedなどNCBIのデータベースへのプログラムからのアクセス"), "Public service (NCBI usage guidelines)", "beginner", "cloud"),
        ("RCSB PDB", "https://www.rcsb.org/", ("Experimentally determined 3D structures", "実験で決定された立体構造"), "CC0 1.0 (PDB data)", "beginner", "cloud"),
    ],
    "stack": [
        ("RDKit", "https://www.rdkit.org/", "RDKit community", "BSD-3-Clause", ("Open-source cheminformatics toolkit with Python bindings.", "Pythonから使える、オープンソースのケモインフォマティクスのツールキット。")),
        ("ChEMBL", "https://www.ebi.ac.uk/chembl/", "EMBL-EBI", "CC BY-SA 3.0 (data)", ("Manually curated database of bioactive molecules with drug-like properties.", "薬らしい性質をもつ生理活性分子を、人の手で整理したデータベース。")),
        ("ChEMBL web services docs", "https://chembl.gitbook.io/chembl-interface-documentation/web-services/chembl-data-web-services", "EMBL-EBI", "CC BY-SA 3.0 (data)", ("How to query activities, molecules and targets over REST.", "活性・分子・標的をRESTで取得する方法。")),
        ("AlphaFold Protein Structure Database", "https://alphafold.ebi.ac.uk/", "Google DeepMind / EMBL-EBI", "CC BY 4.0 (data)", ("Open database of protein structure predictions with per-residue confidence.", "残基ごとの信頼度つきで、タンパク質の予測構造を公開しているデータベース。")),
        ("AlphaFold DB API docs", "https://alphafold.ebi.ac.uk/api-docs", "EMBL-EBI", "CC BY 4.0 (data)", ("Endpoint used here to locate the model file for an accession.", "このページでアクセッション番号からモデルファイルを探すのに使っているAPI。")),
        ("UniProt", "https://www.uniprot.org/", "UniProt Consortium", "CC BY 4.0", ("Comprehensive resource for protein sequence and functional information.", "タンパク質の配列と機能情報をまとめた総合リソース。")),
        ("Biopython", "https://biopython.org/", "Biopython contributors", "Biopython License / BSD-3-Clause", ("Python tools for computational molecular biology.", "計算分子生物学のためのPythonツール群。")),
        ("NCBI E-utilities", "https://www.ncbi.nlm.nih.gov/books/NBK25501/", "NCBI / US National Library of Medicine", "Public service (NCBI usage guidelines)", ("Official guide to the Entrez programming utilities for PubMed and more.", "PubMedなどに使えるEntrezプログラミングユーティリティの公式ガイド。")),
        ("RCSB PDB", "https://www.rcsb.org/", "RCSB Protein Data Bank", "CC0 1.0 (PDB data)", ("US data centre for the global Protein Data Bank archive of experimental structures.", "実験構造を集めた国際的なProtein Data Bankの米国データセンター。")),
    ],
    "related": [("/library/workflows/", ("Workflow templates for scheduling and chaining", "定期実行・連結のためのワークフロー")),
                ("/library/toolkit/", ("AI agent toolkits (for the optional summary step)", "AIエージェントのツールキット（任意の要約手順に）"))],
}

# ---------------------------------------------------------------- Quantum
F["quantum"] = {
    "name": ("Quantum", "量子", "Cuántica", "量子", "양자"),
    "h1": ("Quantum: first real programs on a simulator", "量子：シミュレーターで、最初の本格的なプログラムを", "Cuántica: primeros programas reales en un simulador", "量子：在模拟器上写出第一批真正的程序", "양자: 시뮬레이터에서 첫 실전 프로그램"),
    "lead": ("Four short projects that run on a laptop and check themselves: a VQE for the hydrogen molecule, a Bell pair with and without noise, Grover search against theory, and QAOA against brute force.",
             "ノートPCで動き、結果を自分で検算する4つの小さなプロジェクトです。水素分子のVQE、ノイズの有無で比べるベル対、理論値と比べるGrover探索、総当たりと比べるQAOAです。",
             "Cuatro proyectos cortos que se ejecutan en un portátil y se comprueban solos: VQE para la molécula de hidrógeno, un par de Bell con y sin ruido, Grover frente a la teoría y QAOA frente a fuerza bruta.",
             "四个可在笔记本电脑上运行并能自我校验的小项目：氢分子 VQE、有噪声与无噪声的贝尔对、与理论对照的 Grover 搜索，以及与穷举对照的 QAOA。",
             "노트북에서 돌아가고 스스로 검산하는 작은 프로젝트 네 가지: 수소 분자 VQE, 노이즈 유무로 비교하는 벨 쌍, 이론값과 비교하는 Grover 탐색, 전수 탐색과 비교하는 QAOA."),
    "notice": ("All recipes run on simulators. Results on real quantum hardware will be noisier and depend on the device.",
               "どのレシピもシミュレーター上で動かします。実機の量子コンピューターでは、結果はもっとノイズが多く、機種によっても変わります。",
               "Todas las recetas se ejecutan en simuladores. En hardware cuántico real los resultados serán más ruidosos y dependerán del dispositivo.",
               "所有配方都在模拟器上运行。在真实量子硬件上，结果噪声更大，并因设备而异。",
               "모든 레시피는 시뮬레이터에서 실행합니다. 실제 양자 하드웨어에서는 노이즈가 더 많고 기기마다 결과가 다릅니다."),
    "recipes": [
        {"id": "first-vqe-h2", "code": "vqe_h2_pennylane.py",
         "title": ("Your first VQE: the H₂ ground-state energy on a simulator (PennyLane)", "はじめてのVQE：シミュレーターで水素分子の基底エネルギーを求める（PennyLane）", "Tu primer VQE: energía del estado fundamental de H₂ en un simulador (PennyLane)", "第一个 VQE：在模拟器上求 H₂ 基态能量（PennyLane）", "첫 VQE: 시뮬레이터로 H₂ 바닥 상태 에너지 구하기 (PennyLane)"),
         "summary": ("Build the 4-qubit hydrogen Hamiltonian, optimise a one-parameter double-excitation circuit and compare the result with exact diagonalisation of the same Hamiltonian.",
                     "4量子ビットの水素分子ハミルトニアンを作り、パラメータ1つの二電子励起回路を最適化して、同じハミルトニアンの厳密対角化の値と比べます。",
                     "Construye el hamiltoniano del hidrógeno con 4 cúbits, optimiza un circuito de doble excitación de un parámetro y compáralo con la diagonalización exacta.",
                     "构建 4 量子比特的氢分子哈密顿量，优化单参数双激发电路，并与同一哈密顿量的精确对角化结果比较。",
                     "4큐비트 수소 해밀토니안을 만들고 파라미터 하나짜리 이중 들뜸 회로를 최적화해 같은 해밀토니안의 정확한 대각화 값과 비교합니다."),
         "input": ("H–H bond length in ångström (default 0.74), optimiser steps (default 60).", "H–Hの結合長（オングストローム、既定0.74）、最適化のステップ数（既定60）。"),
         "output": ("vqe_h2.csv (step, energy in hartree) and printed Hartree–Fock start, VQE result, exact value and error in mHa.", "vqe_h2.csv（ステップ、エネルギー〔ハートリー〕）と、Hartree–Fockの初期値、VQEの結果、厳密値、誤差（mHa）の表示。"),
         "prereq": ("Python 3.10 or later and `pip install pennylane`.", "Python 3.10以上と `pip install pennylane`。"),
         "steps": {"en": ["Save the code below as vqe_h2_pennylane.py.", "Run `python vqe_h2_pennylane.py`.",
                          "Plot vqe_h2.csv to watch the energy fall from the Hartree–Fock value.",
                          "Scan the bond length (for example 0.5 to 2.0 Å) and plot energy against distance: that is a potential-energy curve.",
                          "Try fewer steps or a different step size and see when the error rises above chemical accuracy (about 1.6 mHa)."],
                   "ja": ["下のコードを vqe_h2_pennylane.py として保存します。", "`python vqe_h2_pennylane.py` を実行します。",
                          "vqe_h2.csv をグラフにすると、Hartree–Fockの値からエネルギーが下がっていく様子が見えます。",
                          "結合長を変えながら（たとえば0.5〜2.0 Å）実行し、距離に対するエネルギーをグラフにします。これがポテンシャルエネルギー曲線です。",
                          "ステップ数を減らしたり、刻み幅を変えたりして、誤差が化学的精度（約1.6 mHa）を超えるのはどんなときかを確かめます。"]},
         "expected": ("The VQE energy ends below the Hartree–Fock start and matches the exact value of the same 4-qubit Hamiltonian to well within chemical accuracy. Matching the exact value of a small-basis model is not the same as matching experiment.",
                      "VQEのエネルギーはHartree–Fockの初期値より下がり、同じ4量子ビットのハミルトニアンの厳密値と、化学的精度を十分に下回る誤差で一致します。ただし、小さな基底での模型の厳密値に合うことと、実験値に合うことは別の話です。"),
         "next": ("Read PennyLane's VQE demo for other ansätze and optimisers, then try a slightly larger molecule.", "PennyLaneのVQEのデモで他のアンザッツや最適化手法を見たうえで、少し大きな分子に挑戦してみてください。"),
         "next_href": "https://pennylane.ai/demos/tutorial_vqe"},
        {"id": "bell-pair-noise", "code": "bell_noise_qiskit.py",
         "title": ("Bell pair: ideal versus noisy simulator (Qiskit Aer)", "ベル対：理想的なシミュレーターとノイズありを比べる（Qiskit Aer）", "Par de Bell: simulador ideal frente a ruidoso (Qiskit Aer)", "贝尔对：理想模拟器与有噪声模拟器对比（Qiskit Aer）", "벨 쌍: 이상적 시뮬레이터 대 노이즈 시뮬레이터 (Qiskit Aer)"),
         "summary": ("Entangle two qubits, measure them thousands of times, then add a simple depolarising and readout noise model and see how the correlations degrade.",
                     "2つの量子ビットをもつれさせて何千回も測定し、そのあと簡単な脱分極ノイズと読み出しノイズを加えて、相関がどう崩れるかを見ます。",
                     "Entrelaza dos cúbits, mídelos miles de veces y añade un modelo simple de ruido despolarizante y de lectura para ver cómo se degradan las correlaciones.",
                     "让两个量子比特纠缠并测量数千次，再加入简单的退极化噪声和读出噪声，观察相关性如何下降。",
                     "두 큐비트를 얽히게 하고 수천 번 측정한 뒤, 간단한 탈분극·판독 노이즈를 넣어 상관이 어떻게 무너지는지 봅니다."),
         "input": ("One- and two-qubit error rates (defaults 0.01 and 0.03 — example settings, not any real device's figures), shots.", "1量子ビット・2量子ビットの誤り率（既定0.01と0.03。例として置いた値で、実機の数値ではありません）、測定回数。"),
         "output": ("bell_counts.csv (outcome, ideal count, noisy count) and the share of correlated outcomes (00 + 11) for each run.", "bell_counts.csv（結果、理想の回数、ノイズありの回数）と、それぞれの相関した結果（00と11）の割合。"),
         "prereq": ("Python 3.10 or later and `pip install qiskit qiskit-aer`.", "Python 3.10以上と `pip install qiskit qiskit-aer`。"),
         "steps": {"en": ["Save the code below as bell_noise_qiskit.py.", "Run `python bell_noise_qiskit.py`.",
                          "Compare the two rows: the ideal run shows only 00 and 11; the noisy run also shows 01 and 10.",
                          "Raise the two-qubit error, e.g. `python bell_noise_qiskit.py 0.01 0.10`, and watch the correlated share drop.",
                          "Look up a real backend's published error rates on the IBM Quantum Platform and plug them in for a closer comparison."],
                   "ja": ["下のコードを bell_noise_qiskit.py として保存します。", "`python bell_noise_qiskit.py` を実行します。",
                          "2つの行を比べます。理想の実行では00と11しか出ませんが、ノイズありでは01と10も出ます。",
                          "2量子ビットの誤り率を上げて実行し（例：`python bell_noise_qiskit.py 0.01 0.10`）、相関の割合が下がるのを確かめます。",
                          "IBM Quantum Platformで公開されている実機の誤り率を調べて入れると、より実機に近い比較になります。"]},
         "expected": ("The ideal run splits roughly evenly between 00 and 11. The noisy run leaks into 01 and 10; how much depends on the rates you set.",
                      "理想の実行では、00と11がほぼ半々になります。ノイズありでは01や10にも漏れ出し、その量は設定した誤り率で決まります。"),
         "next": ("Add a third qubit to make a GHZ state and see how noise scales with circuit size.", "3つ目の量子ビットを加えてGHZ状態を作り、回路が大きくなるとノイズの影響がどう増えるかを見てみてください。"),
         "next_href": "https://github.com/Qiskit/qiskit-aer"},
        {"id": "grover-three-qubits", "code": "grover_qiskit.py",
         "title": ("Grover search on 3 qubits: measured against theory (Qiskit)", "3量子ビットのGrover探索：測定結果を理論値と比べる（Qiskit）", "Búsqueda de Grover con 3 cúbits: medición frente a teoría (Qiskit)", "3 量子比特 Grover 搜索：测量结果对照理论（Qiskit）", "3큐비트 Grover 탐색: 측정값 대 이론값 (Qiskit)"),
         "summary": ("Mark one bitstring with an oracle, amplify it with the diffuser and compare the measured success rate with the textbook formula.",
                     "オラクルで1つのビット列に印をつけ、拡散演算子で確率を増幅して、測定した成功率を教科書の式による値と比べます。",
                     "Marca una cadena de bits con un oráculo, amplifícala con el difusor y compara la tasa de éxito medida con la fórmula de libro.",
                     "用 oracle 标记一个比特串，用扩散算子放大，再把测得的成功率与教科书公式比较。",
                     "오라클로 비트열 하나를 표시하고 확산 연산자로 증폭한 뒤, 측정된 성공률을 교과서 공식과 비교합니다."),
         "input": ("The marked bitstring (default 101), shots.", "印をつけるビット列（既定は101）、測定回数。"),
         "output": ("grover_counts.csv and a printed line: measured success, theoretical success, random-guess probability.", "grover_counts.csv と、測定した成功率・理論上の成功率・当てずっぽうの確率を並べた表示。"),
         "prereq": ("Python 3.10 or later and `pip install qiskit`.", "Python 3.10以上と `pip install qiskit`。"),
         "steps": {"en": ["Save the code below as grover_qiskit.py.", "Run `python grover_qiskit.py 101`.",
                          "Check that the marked string dominates grover_counts.csv.",
                          "Try a 4-bit string (`python grover_qiskit.py 1011`): the script picks the iteration count for you.",
                          "Change the code to run one iteration too many and watch the success rate fall — the 'overcooking' effect."],
                   "ja": ["下のコードを grover_qiskit.py として保存します。", "`python grover_qiskit.py 101` を実行します。",
                          "grover_counts.csv で、印をつけたビット列が大半を占めているかを確かめます。",
                          "4ビットでも試せます（`python grover_qiskit.py 1011`）。反復回数はスクリプトが自動で決めます。",
                          "コードを書き換えて反復を1回多くすると、成功率が下がります。いわゆる「回しすぎ」の効果です。"]},
         "expected": ("Measured success close to the theoretical value and far above random guessing. Small differences come from finite shots.",
                      "測定した成功率は理論値に近く、当てずっぽうよりはるかに高くなります。わずかな差は、測定回数が有限であることによるものです。"),
         "next": ("Run the same circuit through the noisy simulator from the Bell-pair recipe and see how fast the advantage shrinks.", "同じ回路をベル対のレシピのノイズありシミュレーターで動かし、優位がどれだけ早く縮むかを見てみてください。"),
         "next_href": "#bell-pair-noise"},
        {"id": "qaoa-maxcut", "code": "qaoa_maxcut_pennylane.py",
         "title": ("QAOA for Max-Cut on a small graph, checked by brute force (PennyLane)", "小さなグラフのMax-CutをQAOAで解き、総当たりで検算する（PennyLane）", "QAOA para Max-Cut en un grafo pequeño, verificado por fuerza bruta (PennyLane)", "用 QAOA 解小图 Max-Cut，并用穷举校验（PennyLane）", "작은 그래프 Max-Cut을 QAOA로 풀고 전수 탐색으로 검산 (PennyLane)"),
         "summary": ("Optimise a depth-2 QAOA circuit for a 5-node graph, read off the most likely cut and compare it with the true optimum found by trying every partition.",
                     "5頂点のグラフに対して深さ2のQAOA回路を最適化し、最も出やすい分割を読み取って、すべての分け方を試して求めた真の最適解と比べます。",
                     "Optimiza un circuito QAOA de profundidad 2 para un grafo de 5 nodos, lee el corte más probable y compáralo con el óptimo real por fuerza bruta.",
                     "为 5 节点图优化深度为 2 的 QAOA 电路，读出最可能的割，并与穷举所有划分得到的真实最优解比较。",
                     "5노드 그래프에 깊이 2 QAOA 회로를 최적화해 가장 가능성 높은 분할을 읽고, 모든 분할을 시도한 실제 최적해와 비교합니다."),
         "input": ("Edge list (default 0-1,1-2,2-3,3-4,4-0,0-2), depth p, optimiser steps.", "辺のリスト（既定は 0-1,1-2,2-3,3-4,4-0,0-2）、深さp、最適化のステップ数。"),
         "output": ("qaoa_result.json: most likely bitstring, its cut size, brute-force maximum cut, probability on optimal cuts and the random-guess baseline.", "qaoa_result.json：最も出やすいビット列、その分割の大きさ、総当たりでの最大カット、最適解に乗る確率、当てずっぽうの場合の基準値。"),
         "prereq": ("Python 3.10 or later and `pip install pennylane networkx`.", "Python 3.10以上と `pip install pennylane networkx`。"),
         "steps": {"en": ["Save the code below as qaoa_maxcut_pennylane.py.", "Run `python qaoa_maxcut_pennylane.py`.",
                          "Compare its_cut with brute_force_max_cut and prob_on_optimal_cuts with random_guess_prob.",
                          "Try p = 1 and p = 3 and see how the probability on optimal cuts changes.",
                          "Use your own small graph (up to about 12 nodes stays fast on a laptop)."],
                   "ja": ["下のコードを qaoa_maxcut_pennylane.py として保存します。", "`python qaoa_maxcut_pennylane.py` を実行します。",
                          "its_cut と brute_force_max_cut、prob_on_optimal_cuts と random_guess_prob をそれぞれ比べます。",
                          "p = 1 と p = 3 も試し、最適解に乗る確率がどう変わるかを見ます。",
                          "ご自身の小さなグラフでも試せます（12頂点くらいまでならノートPCでもすぐ終わります）。"]},
         "expected": ("The most likely bitstring is an optimal cut, and the probability on optimal cuts is clearly above the random baseline. For graphs this small a classical solver is faster — the point is to learn the workflow and verify it.",
                      "最も出やすいビット列は最適な分割になり、最適解に乗る確率は当てずっぽうの基準をはっきり上回ります。この大きさのグラフなら古典的な解法のほうが速いので、目的はワークフローを覚えて検算することにあります。"),
         "next": ("Compare against a classical heuristic on a 20-node graph and write down where each approach stands.", "20頂点のグラフで古典的なヒューリスティックと比べ、それぞれの立ち位置を書き出してみてください。"),
         "next_href": "https://pennylane.ai/"},
    ],
    "compare": [
        ("Qiskit", "https://www.ibm.com/quantum/qiskit", ("Build, transpile and run circuits; primitives", "回路の作成・トランスパイル・実行（プリミティブ）"), "Apache-2.0", "beginner", "both"),
        ("Qiskit Aer", "https://github.com/Qiskit/qiskit-aer", ("High-performance simulators with noise models", "ノイズモデル対応の高速シミュレーター"), "Apache-2.0", "intermediate", "local"),
        ("PennyLane", "https://pennylane.ai/", ("Differentiable quantum programming, VQE and QML", "微分可能な量子プログラミング、VQE、量子機械学習"), "Apache-2.0", "beginner", "both"),
        ("Cirq", "https://quantumai.google/cirq", ("Circuits for near-term devices", "近い将来のデバイス向けの回路記述"), "Apache-2.0", "intermediate", "local"),
        ("QuTiP", "https://qutip.org/", ("Dynamics of open quantum systems", "開放量子系のダイナミクス"), "BSD-3-Clause", "advanced", "local"),
        ("Amazon Braket SDK", "https://github.com/amazon-braket/amazon-braket-sdk-python", ("One SDK for several hardware providers (paid service)", "複数のハードウェア事業者に1つのSDKでアクセス（有料サービス）"), "Apache-2.0 (SDK)", "intermediate", "cloud"),
    ],
    "stack": [
        ("Qiskit", "https://www.ibm.com/quantum/qiskit", "IBM", "Apache-2.0", ("Open-source SDK for working with quantum computers at the circuit and primitive level.", "回路とプリミティブのレベルで量子コンピューターを扱うオープンソースSDK。")),
        ("Qiskit (GitHub)", "https://github.com/Qiskit/qiskit", "Qiskit / IBM", "Apache-2.0", ("Source, issues and release notes; check here when an API name changes.", "ソース、課題、リリースノート。APIの名前が変わったときはここを確認します。")),
        ("Qiskit Aer", "https://github.com/Qiskit/qiskit-aer", "Qiskit / IBM", "Apache-2.0", ("Simulator backends, including noise models, used in the Bell-pair recipe.", "ベル対のレシピで使っている、ノイズモデル対応のシミュレーター。")),
        ("IBM Quantum documentation", "https://quantum.cloud.ibm.com/docs/en/guides", "IBM", "Service terms apply", ("Guides for running on IBM hardware; check plan terms before submitting jobs.", "IBMの実機で動かすためのガイド。ジョブを送る前にプランの条件を確認してください。")),
        ("PennyLane", "https://pennylane.ai/", "Xanadu", "Apache-2.0", ("Library for quantum computing, quantum chemistry and quantum machine learning.", "量子計算、量子化学、量子機械学習のためのライブラリ。")),
        ("PennyLane VQE demo", "https://pennylane.ai/demos/tutorial_vqe", "Xanadu", "Apache-2.0", ("Official walkthrough of VQE that the first recipe builds on.", "最初のレシピの土台になっている、公式のVQE解説。")),
        ("PennyLane qchem docs", "https://docs.pennylane.ai/en/stable/code/qp_qchem.html", "Xanadu", "Apache-2.0", ("Reference for building molecular Hamiltonians.", "分子ハミルトニアンを作る関数のリファレンス。")),
        ("Cirq", "https://quantumai.google/cirq", "Google Quantum AI", "Apache-2.0", ("Python framework for writing and simulating circuits.", "回路を書いてシミュレーションするためのPythonフレームワーク。")),
        ("QuTiP", "https://qutip.org/", "QuTiP developers", "BSD-3-Clause", ("Toolbox for simulating the dynamics of open quantum systems.", "開放量子系のダイナミクスをシミュレーションするツールボックス。")),
    ],
    "related": [("/library/toolkit/", ("AI agent toolkits (for explaining results to your team)", "AIエージェントのツールキット（結果をチームに説明するときに）")),
                ("/search/", ("Search the whole site", "サイト全体を検索"))],
}

UI.update({  # hub + units, 5 languages
    "fldHubTitle": ("Fields: build recipes and verified sources", "分野別：作り方レシピと確認済みの出典", "Áreas: recetas y fuentes verificadas", "领域：构建配方与已核实来源", "분야별: 제작 레시피와 확인된 출처"),
    "fldHubLead": ("Four fields where open tools and public data let you build something real today. Every recipe is written by BSV, every source is an official page we checked.",
                   "オープンなツールと公開データで、今日から本物を作れる4つの分野です。レシピはすべてBSVが書き、出典はすべてBSVが確認した公式ページです。",
                   "Cuatro áreas donde herramientas abiertas y datos públicos permiten construir algo real hoy. Cada receta la escribe BSV y cada fuente es una página oficial comprobada.",
                   "四个领域：用开源工具和公开数据，今天就能做出真东西。每个配方都由 BSV 编写，每个来源都是我们核实过的官方页面。",
                   "오픈 도구와 공개 데이터로 오늘 바로 실제 결과물을 만들 수 있는 4개 분야입니다. 레시피는 모두 BSV가 작성했고 출처는 모두 확인한 공식 페이지입니다."),
    "fldUnitRecipes": ("recipes", "レシピ", "recetas", "个配方", "개 레시피"),
    "fldUnitTested": ("tested by BSV", "BSVで動作確認済み", "probadas por BSV", "经 BSV 测试", "BSV 테스트 완료"),
    "fldUnitSources": ("verified sources", "確認済みの出典", "fuentes verificadas", "个已核实来源", "개 확인된 출처"),
    "fldLab": ("Interactive tool, runs in your browser (English / Japanese)", "ブラウザで動くインタラクティブツール（英語／日本語）", "Herramienta interactiva en el navegador (inglés / japonés)", "在浏览器中运行的交互工具（英文 / 日文）", "브라우저에서 실행되는 인터랙티브 도구 (영어 / 일본어)"),
    "fldUnitTools": ("interactive tool", "インタラクティブツール", "herramienta interactiva", "个交互工具", "개 인터랙티브 도구"),
    "fldOpen": ("Open", "開く", "Abrir", "打开", "열기"),
    "fldRunAt": ("Run on", "実行日時", "Ejecutado el", "运行时间", "실행 일시"),
    "fldNotRunWhy": ("BSV has not run this one, so there is no test output to show. Use the steps as a guide and check them against the official documentation.",
                     "BSVではまだ実行していないため、テスト出力はありません。手順は目安として使い、公式ドキュメントと照らし合わせて確認してください。",
                     "BSV aún no lo ha ejecutado, así que no hay salida de prueba. Usa los pasos como guía y contrástalos con la documentación oficial.",
                     "BSV 尚未运行此配方，因此没有测试输出。请把步骤当作参考，并对照官方文档确认。",
                     "BSV가 아직 실행하지 않아 테스트 출력이 없습니다. 단계는 참고용으로 보시고 공식 문서와 대조해 확인하세요."),
})
