import test from 'node:test';
import assert from 'node:assert/strict';
import { buildReport } from './funnel-report.mjs';
const e = (kind, n, extra = {}) => ({ event_id: `event-${n}`, kind, at: '2026-09-02T12:00:00Z', actor_id: 'customer-1', actor_kind: 'customer', environment: 'production', ...extra });
const run = (n, extra = {}) => e('run_completed', n, { run_id: `run-${n}`, execution_kind: 'runtime', accepted: true, evidence_ref: `evidence-${n}`, ...extra });
const pay = (n, extra = {}) => e('payment_verified', n, { order_id: `order-${n}`, amount: '20.00', currency: 'USDT', verification_source: 'server_ledger', evidence_ref: `evidence-${n}`, ...extra });
const snapshot = (events = [], coverage = {}) => ({ schema_version: 1, window: { start: '2026-09-01T00:00:00Z', end: '2026-10-01T00:00:00Z', timezone: 'Asia/Tokyo' }, coverage: { registrations: 'complete', runs: 'complete', payments: 'complete', ...coverage }, events });

test('empty complete ledger reports known zero', () => assert.equal(buildReport(snapshot()).totals.verified_orders, 0));
test('missing ledgers remain unknown, not zero', () => assert.equal(buildReport(snapshot([], { payments: 'missing' })).totals.verified_orders, null));
test('partial totals stay null despite observations', () => { const r = buildReport(snapshot([pay(1)], { payments: 'partial' })); assert.equal(r.observed.verified_orders, 1); assert.equal(r.totals.verified_orders, null); });
test('test/internal/vendor/unknown actors excluded', () => { const events = ['test', 'internal', 'vendor', 'unknown'].map((kind, i) => e('registration', i, { actor_id: `actor-${i}`, actor_kind: kind })); assert.equal(buildReport(snapshot(events)).observed.registered_users, 0); });
test('test environment never a sale', () => assert.equal(buildReport(snapshot([pay(1, { environment: 'test' })])).observed.verified_orders, 0));
test('submitted transaction is not a sale', () => assert.equal(buildReport(snapshot([e('payment_submitted', 1, { order_id: 'order-1' })])).observed.verified_orders, 0));
test('exact duplicate events count once', () => { const p = pay(1); assert.equal(buildReport(snapshot([p, { ...p }])).observed.verified_orders, 1); });
test('conflicting event IDs fail closed', () => assert.throws(() => buildReport(snapshot([pay(1), pay(1, { amount: '21' })]))));
test('same order with new event ID counts once', () => assert.equal(buildReport(snapshot([pay(1), pay(2, { order_id: 'order-1' })])).observed.verified_orders, 1));
test('conflicting order amounts fail closed', () => assert.throws(() => buildReport(snapshot([pay(1), pay(2, { order_id: 'order-1', amount: '21' })]))));
test('structural checks and sample outputs are not runtime use', () => assert.equal(buildReport(snapshot([run(1, { execution_kind: 'structural' }), run(2, { execution_kind: 'sample' })])).observed.accepted_runs, 0));
test('failed runtime run is not accepted use', () => assert.equal(buildReport(snapshot([run(1, { accepted: false })])).observed.accepted_runs, 0));
test('accepted runtime run needs evidence reference', () => assert.throws(() => buildReport(snapshot([run(1, { evidence_ref: '' })]))));
test('repeated runs on same day are not return-on-another-day', () => assert.equal(buildReport(snapshot([run(1), run(2)])).observed.users_with_runs_on_multiple_days, 0));
test('return days respect Tokyo midnight', () => { const r = buildReport(snapshot([run(1, { at: '2026-09-02T14:59:00Z' }), run(2, { at: '2026-09-02T15:01:00Z' })])); assert.equal(r.observed.users_with_runs_on_multiple_days, 1); });
test('same run replayed on another day counts once', () => assert.equal(buildReport(snapshot([run(1), run(2, { run_id: 'run-1', at: '2026-09-03T12:00:00Z' })])).observed.users_with_runs_on_multiple_days, 0));
test('end boundary is exclusive', () => assert.equal(buildReport(snapshot([pay(1, { at: '2026-10-01T00:00:00Z' })])).observed.verified_orders, 0));
test('invalid calendar date rejected', () => assert.throws(() => buildReport(snapshot([pay(1, { at: '2026-02-30T00:00:00Z' })]))));
test('milliseconds accepted', () => assert.equal(buildReport(snapshot([pay(1, { at: '2026-09-02T12:00:00.001Z' })])).observed.verified_orders, 1));
test('decimal arithmetic avoids float rounding', () => assert.equal(buildReport(snapshot([pay(1, { amount: '0.1' }), pay(2, { amount: '0.2' })])).observed.gross_collected_by_currency.USDT, '0.3'));
test('different currencies never added together', () => assert.deepEqual(buildReport(snapshot([pay(1), pay(2, { currency: 'USD' })])).observed.gross_collected_by_currency, { USD: '20', USDT: '20' }));
test('negative or numeric payment amount rejected', () => { for (const amount of ['-20', 20, 'NaN', '1e3']) assert.throws(() => buildReport(snapshot([pay(1, { amount })]))); });
test('client claim is not server verification', () => assert.throws(() => buildReport(snapshot([pay(1, { verification_source: 'browser' })]))));
test('email identifiers and extra PII fields rejected', () => { assert.throws(() => buildReport(snapshot([pay(1, { actor_id: 'name@example.com' })]))); assert.throws(() => buildReport(snapshot([pay(1, { email: 'name@example.com' })]))); });
test('output omits customer/order/evidence identifiers', () => { const output = JSON.stringify(buildReport(snapshot([pay(1), run(2)]))); for (const id of ['customer-1', 'order-1', 'evidence-1', 'run-2']) assert.equal(output.includes(id), false); });
test('missing coverage cannot contain eligible source events', () => assert.throws(() => buildReport(snapshot([pay(1)], { payments: 'missing' }))));
test('contradictory actor labels fail closed', () => assert.throws(() => buildReport(snapshot([e('registration', 1), e('registration', 2, { actor_kind: 'test' })]))));
test('repeat registrations deduplicate by actor', () => assert.equal(buildReport(snapshot([e('registration', 1), e('registration', 2)])).observed.registered_users, 1));
