#!/usr/bin/env python3
"""Editorial source directory. These entries link to authors; they do not mirror code.
Public upstream README/platform and Apache-2.0 repository listings checked on
2026-10-01. Per-file provenance and dependency audits have not been completed.
No author code, images, README prose or reported performance is reproduced.
"""
import json
from pathlib import Path
B=Path(__file__).resolve().parent
D=[]
def add(repo,name,kind,category,doc,en,ja,branch='main',platforms=None,credit=None,research=False):
    root='https://github.com/EarnForex/'+repo
    D.append(dict(id='earnforex-'+repo.lower(),name=name,platforms=platforms or ['MT4','MT5'],kind=kind,category=category,license='Apache-2.0',provider='EarnForex',repo='EarnForex/'+repo,branch=branch,commit=None,source_url=root,license_url=root+'/blob/'+branch+'/LICENSE',documentation_url=('https://www.earnforex.com/'+doc if doc else root+'/blob/'+branch+'/README.md'),distribution='author-hosted',compiled=False,runtime_tested=False,check_date='2026-10-01',risk_level=('Research only' if research else 'Not runtime tested'),version='Author-maintained source',text={'en':dict(zip(['purpose','mechanism','settings','caution'],en)), 'ja':dict(zip(['purpose','mechanism','settings','caution'],ja))},credit_note=credit,review_scope='Original publisher README, available source platforms and explicit Apache-2.0 repository license listing reviewed. This is a directory link, not a BSV redistribution or a full source/dependency audit.',source_count=None))
add('PositionSizer','Position Sizer','Trade manager','Risk tools','metatrader-expert-advisors/Position-Sizer/',
['Plan position size before placing an order. Useful for traders who want an explicit entry, stop and account-currency risk calculation rather than mental lot arithmetic.',
 'A chart panel calculates lots from account and instrument information, the chosen risk, commission and related settings. It also provides margin, portfolio and swap information and can submit trades from its calculations.',
 'Follow the complete author installation instructions, including associated files. First compare a demo calculation against the broker’s contract size, tick value, lot step and commission; only then test the order button.',
 'This is a sizing and execution assistant, not an entry strategy. A calculated loss is not a guaranteed maximum; gaps and execution costs can change the realized result. The panel can place real orders.'],
['発注前に、エントリー・損切り位置と口座通貨ベースのリスクからロットを確認するためのツールです。',
 'チャート上のパネルで、口座・銘柄・リスク・手数料などを使ってロットを計算します。必要証拠金や保有全体の情報も確認でき、計算に基づく発注機能もあります。',
 '作者の導入手順に従い、関連ファイルも配置します。最初にデモで契約サイズ・ティック価値・ロット刻み・手数料と計算結果を照合し、その後に発注ボタンを試します。',
 '売買方向を決める戦略ではありません。計算上の損失額が実損失の上限になるとは限らず、窓開けや滑りの影響を受けます。実注文を出せるツールです。'],branch='master')
add('Account-Protector','Account Protector','Trade manager','Trade management','metatrader-expert-advisors/Account-Protector/',
['Define account-management actions before an emergency. Useful for testing conditional position closing, timed actions and a manual emergency control.',
 'The EA combines configurable conditions with position/order filters and actions. Its panel includes trailing and break-even management as well as an emergency action button.',
 'Use a separate demo account. Select exactly which positions the rules should cover, enable one condition at a time and verify both the trigger and the no-trigger case. Test a terminal restart.',
 'Incorrect filters can close positions that you meant to retain. Do not run overlapping trade managers without testing their interaction. This is not a guarantee against account loss.'],
['緊急時に行う操作を、あらかじめ条件と対象を決めて検証する取引管理ツールです。',
 '条件判定と注文・ポジションの絞り込みを組み合わせ、決済や時刻指定の操作を行います。追従ストップ、建値管理、緊急操作ボタンも備えます。',
 '独立したデモ口座で、対象ポジションを絞って一条件ずつ設定します。条件を満たす場合と満たさない場合、端末再起動後の動作を確認します。',
 '対象の設定を間違えると、残したい建玉まで決済する恐れがあります。他の管理EAと同時に動かす際は競合確認が必要です。口座損失を防ぐ保証ではありません。'],branch='master')
add('ATR-Trailing-Stop','ATR Trailing Stop','Trade manager','Trade management','metatrader-expert-advisors/atr-trailing-stop/',
['Explore volatility-based trailing exits on positions you already hold. Use it to compare a changing stop distance with a fixed-distance exit.',
 'The EA adjusts stop-losses using Average True Range for trades selected by its filters. A chart button switches the management on or off.',
 'Select the target trades and review the ATR-related inputs. On demo, record the initial stop, subsequent modifications and rejected modifications under your broker’s minimum-distance rules.',
 'This is an exit manager, not a signal generator. A volatile ATR or too-tight setting can produce unwanted exits. Terminal operation and accepted broker modifications remain necessary.'],
['保有済みポジションの出口を、固定幅ではなく値動きの大きさに合わせて比較検証したいときの管理EAです。',
 '対象フィルターに一致する取引の損切り位置をATRに基づいて追従させます。チャートのボタンで管理の有効・無効を切り替えます。',
 '対象取引とATR関連の入力を確認し、デモで初期ストップと更新履歴を記録します。業者の最小ストップ距離による変更拒否も確認します。',
 '新規エントリーを判断する戦略ではありません。設定が狭すぎると意図しない決済につながります。端末の稼働と注文変更の成立が必要です。'])
add('Fractals-Trailing-Stop','Fractals Trailing Stop','Trade manager','Trade management','metatrader-expert-advisors/fractals-trailing-stop/',
['Test exits that follow confirmed swing structures rather than a constant number of points.',
 'The EA trails filtered trades’ stop-losses using Bill Williams Fractals. A chart control enables or disables the manager.',
 'Choose the target positions and inspect the fractal-related settings. On demo, compare each stop movement with the fractal that became available at that moment, not one visible only afterward.',
 'Fractal confirmation requires subsequent bars. A historical turning point was not necessarily known at its plotted bar. Exit management can conflict with another EA changing the same stop.'],
['一定幅ではなく、確認されたスイング構造をたどる決済管理を検証するためのEAです。',
 '対象取引の損切り位置をBill Williamsのフラクタルに基づいて追従させます。チャート操作で有効・無効を切り替えます。',
 '対象建玉とフラクタル関連設定を確認します。デモでは、各ストップ更新時点で実際に確定していたフラクタルと照合します。',
 'フラクタルは後続足を使って確定します。過去チャートの転換点が、その足の時点で分かっていたとは限りません。同じストップを動かす他のEAとの競合にも注意が必要です。'])
add('Heiken-Ashi-Naive','Heiken Ashi Naive','Expert Advisor','Trend','metatrader-expert-advisors/Heiken-Ashi-Naive/',
['Study a simple automated interpretation of strong Heiken Ashi candles. Treat this as a strategy-research example, not a ready-made income system.',
 'The author describes buying very bullish Heiken Ashi candles and selling very bearish ones. A separate Z-Score-oriented variant is also provided upstream.',
 'Start with the ordinary version on demo and inspect its inputs and trade list. Compare signal candles against actual executable prices; keep the advanced variant separate until its behavior is understood.',
 'The author warns that the EA can lose the whole account. Heiken Ashi prices are transformed chart values, not executable market quotes. BSV has not reproduced any performance claims.'],
['強い平均足を売買条件に使う、シンプルな自動売買ロジックを研究するためのサンプルです。',
 '作者の説明では、非常に強い陽の平均足で買い、非常に強い陰の平均足で売ります。別途Zスコアを利用する派生版も提供されています。',
 'まず通常版をデモで確認し、入力条件と売買履歴を照合します。平均足の表示価格と実際の約定可能価格を区別し、派生版は仕組みを理解してから別に検証します。',
 '作者は資金を全て失う可能性を警告しています。平均足は加工された価格表示であり、表示値で約定するとは限りません。収益性はBSVでは検証していません。'],research=True)
add('Adjustable-MA','Adjustable MA','Expert Advisor','Trend','metatrader-expert-advisors/Adjustable-MA/',
['Compare moving-average crossover rules in MetaTrader’s tester. A configurable teaching EA for testing, not a profitable-system claim.',
 'Two moving averages generate cross-based trades. Their parameters and some position-management settings can be changed to compare variations.',
 'Install as an EA in the matching MT4 or MT5 terminal. Test one parameter change at a time, include transaction costs, and inspect individual trades before comparing summary results.',
 'The author explicitly states that this EA is not profitable and should be used only on a demo account. Optimizing a historical result does not establish a future advantage.'],
['移動平均線の交差条件を、MetaTraderのテスターで比較する学習用EAです。',
 '2本の移動平均線の交差を使って売買します。移動平均線の条件と一部の取引管理設定を変更し、違いを比較できます。',
 'MT4・MT5に合う版をEAとして導入します。一度に変える設定を一つに絞り、取引コストを入れ、集計値だけでなく個別の売買履歴も確認します。',
 '作者が「収益性がない」「デモ口座でのみ使用」と明記しています。過去成績が良くなる設定を探しても、将来の優位性が確認されたことにはなりません。'],research=True)
add('RSI-EA','RSI EA','Expert Advisor','Momentum',None,
['Study how an RSI signal is connected to an MT5 EA structure. Useful as an editable test case for developers.',
 'The project implements RSI-based trading in the author’s MT5 EA template, which separates signal logic from sizing and order management.',
 'Use the complete MT5 repository and its dependency layout. Read the RSI signal conditions in the current source, select a demo symbol and check the generated entries and exits against that exact logic.',
 'The author labels it unprofitable and demo-only. It is an MT5 project; a .mq5 file is not an MT4 EA. Parameters and signal rules must not be inferred from the product name.'],
['RSIの判定をMT5のEAへ組み込む構造を学ぶ、編集・検証用のサンプルです。',
 '作者のMT5用EAひな形にRSIベースの売買処理を実装したプロジェクトです。売買条件とロット・注文管理の構造を確認できます。',
 'MT5用の関連ファイル一式を取得し、現在のソースに書かれたRSI条件を先に確認します。デモ銘柄を選び、発生した売買がその条件と一致するか照合します。',
 '作者は収益性がなくデモ専用としています。MT5用であり、.mq5をMT4で使うことはできません。名前だけから売買条件を決めつけないことが大切です。'],platforms=['MT5'],research=True)
add('News-Trader','News Trader','Expert Advisor','Sessions','metatrader-expert-advisors/News-Trader/',
['Inspect a scheduled news-trading implementation and the execution risks of trading around announcements.',
 'The EA requires the trader to supply event timing and price settings. The author describes pre-release positioning with a take-profit distance larger than the stop distance; it does not autonomously understand a news release.',
 'Read the author’s current event-time and order settings. Test only on demo and verify the terminal time zone, spread behavior, rejected orders and what happens when the specified event is missed.',
 'This is not fully automatic news analysis. Scheduled releases can involve gaps and severe slippage, so nominal stop distance and a large profit target do not ensure controlled realized loss.'],
['指標発表の時刻を使う売買実装と、イベント前後の約定リスクを調べるためのEAです。',
 'イベントの時刻や価格設定は利用者が入力します。作者は、発表前のポジションと損切り幅より広い利益目標を使う構成を説明しています。ニュース内容を自律的に理解する仕組みではありません。',
 '作者の現行の時刻・注文設定を読み、デモだけで検証します。端末時刻、スプレッド、注文拒否、指定時刻を過ぎた場合の挙動を確認します。',
 '完全自動のニュース分析システムではありません。発表時は窓や大きな滑りが起こり得るため、設定した損切り幅どおりに損失が収まるとは限りません。'],research=True)
# Exit managers have distinct references and setup checks; none is marketed as an entry algorithm.
add('PSAR-Trailing-Stop','PSAR Trailing Stop','Trade manager','Trade management','metatrader-expert-advisors/psar-trailing-stop/',
['Compare a Parabolic SAR exit with your current stop-management rule.', 'Filtered positions have their stop-losses trailed from Parabolic SAR. A chart button controls whether management is active.', 'Check the SAR-related inputs and target filters in the author version. On demo, compare each modification to the visible SAR and broker stop-distance constraints.', 'SAR can change sides as market conditions change. This manager does not assess whether an entry is appropriate. Check conflicts with other automated exits.'],
['現在の決済ルールと、パラボリックSARを使う追従決済を比較する管理EAです。','対象ポジションの損切り位置をパラボリックSARに基づいて更新します。チャートのボタンで管理の有効・無効を切り替えます。','作者版のSAR関連入力と対象フィルターを確認し、デモで各更新をSARの値と業者のストップ距離制限に照合します。','SARは相場状況によって価格の反対側へ切り替わります。新規売買の妥当性を判定するものではありません。他の決済EAとの競合も確認します。'])
add('MA-Trailing-Stop','MA Trailing Stop','Trade manager','Trade management','metatrader-expert-advisors/moving-average-trailing-stop/',
['Test a moving average as a dynamic exit reference for existing positions.', 'The EA trails stops using a moving-average value for trades selected by its filters. It includes an on/off chart control.', 'Review the chosen moving average and target trades. In a demo terminal, confirm that modifications follow the intended line and remain valid for the broker.', 'A moving average can lag a fast move and is not a guaranteed execution price. Running another manager on the same position can produce contradictory updates.'],
['保有ポジションの出口の基準として、移動平均線を使う方法を検証するEAです。','対象フィルターに一致する取引のストップを移動平均線の値に基づいて追従させます。チャート上で有効・無効を切り替えられます。','選択した移動平均線と対象取引を確認します。デモで更新先が意図する線と一致するか、業者の注文条件を満たすかを確認します。','移動平均線は急変に遅れて反応します。線の位置での約定を保証するものではありません。同じ建玉に別の管理EAを使う場合は更新の競合に注意します。'])
add('Supertrend-Trailing-Stop','Supertrend Trailing Stop','Trade manager','Trade management','metatrader-expert-advisors/supertrend-trailing-stop/',
['Explore stop management tied to a Supertrend line rather than a fixed point distance.', 'The EA uses its custom Supertrend reference to trail stop-losses on filtered trades, with a chart control to switch it on or off.', 'Use the complete author files and check whether the current build needs a companion indicator. Test selected positions in demo and record line values and accepted stop updates.', 'This is trade management, not a verified Supertrend entry system. Line changes, terminal downtime and rejected modifications can make actual exits differ from chart expectations.'],
['固定のポイント幅ではなく、スーパートレンドの線を追う決済管理を調べるEAです。','独自のスーパートレンドを基準に、対象取引の損切り位置を追従させます。チャート上の操作で有効・無効を切り替えます。','作者のファイル一式を使い、現行版に関連インジケーターが必要か確認します。デモの対象建玉で、線の値と受理されたストップ更新を記録します。','実証されたエントリー戦略ではなく管理機能です。線の切り替わり、端末停止、注文変更の拒否により、チャート上の想定と実際の出口は変わります。'])
add('Trailing-Stop-on-Profit','Trailing Stop on Profit','Trade manager','Trade management','metatrader-expert-advisors/Trailing-Stop-on-Profit/',
['Delay trailing management until a position reaches a chosen profit threshold.', 'The EA activates trailing after a configurable profit threshold expressed in points. A chart button can disable or enable management.', 'Check threshold and trailing-distance units for the instrument. Use demo to test just below, at and above the activation level, including a reversal after activation.', 'Points are not necessarily pips. This does not guarantee preservation of a displayed floating profit during gaps, spread widening or rejected stop changes.'],
['含み益が一定の水準に達してから、追従ストップを開始したいときの管理EAです。','ポイント単位で設定した利益条件を満たすと追従処理を開始します。チャートのボタンで有効・無効を切り替えます。','銘柄のポイントとpipsの違いを確認し、デモで開始条件の直前・到達時・通過後、さらに反転した場合をテストします。','ポイントをpipsと取り違えると設定幅が変わります。窓、スプレッド拡大、ストップ変更拒否があるため、表示された含み益を確保できる保証はありません。'])
add('Timed-Order','Timed Order','Expert Advisor','Sessions','metatrader-expert-advisors/Timed-Order/',
['Schedule a specific order for a chosen time instead of watching the clock manually.', 'The EA submits a user-configured order at the specified time and reports progress or results through chart/log information and alerts.', 'Set symbol, order details and terminal time carefully. Test one small demo order and inspect both successful submission and deliberate rejection. Remove obsolete schedules.', 'This is scheduled execution, not a market-direction strategy. The broker’s receipt and execution time can differ from the requested time; a disconnected terminal cannot assure timely submission.'],
['指定時刻の注文を、手動の時計監視ではなくEAで送る仕組みです。','利用者が指定した注文を時刻に合わせて送信し、チャート・ログ・通知で進行や結果を確認できます。','銘柄、注文内容、端末時刻を確認します。デモで一回の注文を試し、受理と意図的な拒否の両方を確認します。不要になった予定は残さないようにします。','売買方向を予測する戦略ではありません。指定時刻と業者の受信・約定時刻は一致するとは限らず、端末切断中の送信も保証されません。'])
add('Chart-Pattern-Helper','Chart Pattern Helper','Expert Advisor','Breakout','metatrader-expert-advisors/ChartPatternHelper/',
['Turn trader-drawn chart patterns into explicit breakout order management.', 'The trader draws and names the required chart objects. The EA uses those objects to set up and manage breakout trades; it is not an automatic chart-pattern recognizer or a pullback system.', 'Follow the author’s exact object names and drawing procedure. On demo, move each boundary and verify pending-order levels, cancellation and what happens after a breakout.', 'A mislabeled or misplaced chart object can change orders. Pattern interpretation remains the trader’s responsibility. Test gaps and duplicate instances before relying on the automation.'],
['自分で描いたチャートパターンから、ブレイク時の注文管理につなげる補助EAです。','必要な線などを利用者が描き、指定の名前を付けます。それを使ってブレイクの注文を管理します。パターンの自動認識や押し戻り狙いのシステムではありません。','作者が指定するオブジェクト名と描画手順に従います。デモで境界を動かし、待機注文の価格・取消・ブレイク後の処理を確認します。','線の名前や位置を間違えると注文内容が変わる可能性があります。パターンを解釈する役割は利用者に残ります。窓開けや二重起動も確認します。'])
add('Amazing','Amazing','Expert Advisor','Sessions','metatrader-expert-advisors/Amazing/',
['Study a two-sided pending-order approach around scheduled announcements.', 'The author-maintained project is based on an earlier EA by FiFtHeLeMeNt. It requires the trader’s event and price settings and prepares orders on both sides before the event.', 'Read the current author settings, then use demo to check order distances, event time, expiry and how the opposite order is handled after a fill.', 'Event gaps can fill far from the intended price or trigger both sides. This directory preserves upstream attribution and does not redistribute or certify the underlying derivative code.'],
['予定された発表の前に、上下の待機注文を用意する方式を研究するEAです。','FiFtHeLeMeNt氏の旧作を基に作者が保守しているプロジェクトです。利用者がイベントと価格条件を指定し、発表前に上下の注文を準備します。','現行の作者説明を読み、デモで注文距離・指定時刻・有効期限・片側約定後の反対注文の処理を確認します。','発表時の窓や滑りで想定外の価格や両側約定になる恐れがあります。この項目は出所を明記した原作者への案内であり、派生コードの再配布や権利保証ではありません。'],credit='Upstream credits an earlier version by FiFtHeLeMeNt.',research=True)
add('Binario','Binario','Expert Advisor','Breakout','metatrader-expert-advisors/Binario/',
['Study a moving-average channel breakout as an automated research example.', 'The project, adapted from an earlier MT4 EA by don_forex, uses two moving averages with the same period to form a channel and trades breakouts.', 'Compare the author’s MA source/method and channel setup before testing. In demo, inspect boundary touches separately from the actual entry condition.', 'The author warns of possible total loss. This listing links to the maintained source and its stated license; it is not a BSV code mirror or performance endorsement.'],
['移動平均線のチャネル抜けを、自動売買の研究用サンプルとして確認するEAです。','don_forex氏の旧MT4版に由来するプロジェクトです。同じ期間の2本の移動平均線でチャネルを作り、ブレイクを売買に使います。','作者版の平均線の価格種類・計算方法・チャネル条件を読み、デモで境界に触れただけの場合と実際の発注条件を区別します。','作者は全損の可能性を警告しています。保守元のソースと表示ライセンスへの案内であり、BSVでのコード再配布や収益性の推薦ではありません。'],credit='Upstream credits the earlier MT4 EA by don_forex.',research=True)
add('PersistentAnti','PersistentAnti','Expert Advisor','Mean reversion',None,
['Experiment with a counter-trend hypothesis based on detected trend persistence.', 'Instead of following its persistence finding, the EA takes the opposing side in anticipation of reversal. The upstream project provides MT4 and MT5 sources.', 'Read the persistence calculation and exact reversal conditions in the current source. Test prolonged one-way periods separately from range-bound periods on demo.', 'The author warns that all funds can be lost. A persistent trend can keep extending; a good historical weekly result would not establish intraday or live suitability.'],
['トレンドの持続性を検出し、その反転を狙う仮説を調べるEAです。','検出した持続傾向に追随するのではなく、反対側を売買する構成です。原作者はMT4版とMT5版のソースを公開しています。','現行ソースの持続性計算と反転条件を確認し、デモで一方向の相場と持ち合いの相場を分けて比較します。','作者は資金全てを失う可能性を警告しています。強いトレンドはさらに続く場合があります。週足の過去結果から短期足や実運用への適性を推定しないでください。'],research=True)
add('MarketProfile','Market Profile','Indicator','Levels','indicators/MarketProfile/',
['Find price areas where the market spent more time. Useful for examining session structure and repeated acceptance of a price zone.', 'The indicator builds a time-at-price profile and displays its structure on the chart. MT4 and MT5 source versions are available.', 'Install the matching version and review the selected period/session and price resolution. Compare a displayed concentration with the underlying candles.', 'Time at price is not actual traded volume. A profile level describes the selected sample; it does not guarantee support or resistance in the next session.'],
['相場が長く滞在した価格帯を確認し、セッションの構造を比較するインジケーターです。','価格ごとの滞在時間を基にプロファイルを作り、チャートへ表示します。MT4・MT5のソース版が用意されています。','対応する版を導入し、対象期間・セッション・価格の刻みを確認します。分布の集中が元のローソク足と整合するかを見ます。','滞在時間は実売買量ではありません。分布の水準は選んだ期間を表すもので、次の相場で支持や抵抗になる保証はありません。'],branch='master')
add('Volume-Profile','Volume Profile','Indicator','Volume','indicators/volume-profile/',
['Explore which price zones had more activity in the selected chart sample.', 'This implementation builds a profile using candles and their associated tick volume. It is offered for MT4 and MT5.', 'Check the selected range, price resolution and volume interpretation in the author documentation. Compare profiles from the same feed and time window.', 'Tick activity is not centralized exchange volume. Different brokers or feeds can create different profiles; do not present this histogram as a complete order book.'],
['選んだチャート範囲の中で、活動が集中した価格帯を調べるためのプロファイルです。','ローソク足とティック出来高を使って価格帯別の分布を作ります。MT4・MT5向けの実装です。','対象範囲、価格の刻み、出来高の扱いを作者説明で確認します。比較する際はデータ配信元と時間範囲を合わせます。','ティックの活動量は取引所の全約定量ではありません。業者や配信元によって分布が変わり得るため、完全な注文板のようには扱えません。'])
add('Cumulative-Volume-Delta','Cumulative Volume Delta','Indicator','Volume','indicators/CVD/',
['Examine divergence between price and an accumulated bullish/bearish activity estimate.', 'The indicator accumulates volume classified through price action. Its MT5 version can also use real volume on instruments that supply that data.', 'Select the available volume type and period settings, then compare price and the cumulative series on the same feed. Verify that the requested volume field is actually populated.', 'This construction must not be confused with verified exchange bid/ask aggressor delta. Broker tick data and the classification method affect the result; missing volume invalidates interpretation.'],
['価格と、上昇・下降側へ分類して累積した活動量の食い違いを見るインジケーターです。','値動きを使って出来高を分類・累積します。MT5版では、データが提供される銘柄に限って実出来高も使えます。','利用できる出来高の種類と期間を選び、同じ配信元で価格と累積系列を比較します。選んだ出来高データが実際に存在するかを先に確認します。','取引所の売り買い成行を厳密に分類したデルタと同一ではありません。ティックデータと分類方式の影響を受け、出来高欠損時は解釈できません。'])
add('Trading-Session-Time','Trading Session Time','Indicator','Sessions','indicators/trading-session-time/',
['Mark the trading hours you care about without repeatedly drawing them by hand.', 'Trader-supplied sessions can be displayed using vertical lines, rectangles or candle coloring. Multiple instances and start/end alerts are supported.', 'Translate the intended session into the time base required by the author settings. Test one known session boundary and repeat that check after a daylight-saving change.', 'A colored session is a time annotation, not evidence of liquidity or a trading signal. Do not assume automatic daylight-saving correction without confirming the current implementation.'],
['監視したい時間帯を、毎回手描きせずチャートに表示するインジケーターです。','利用者が指定したセッションを縦線・四角形・ローソク足の色で表示します。複数配置と開始・終了通知にも対応します。','作者設定が使う時刻基準に合わせ、既知の市場開始時刻を一つ確認します。夏時間の変更後も境界が合うかを再確認します。','時間帯の色は流動性の証拠や売買サインではありません。現行コードを確認せず、夏時間が自動補正されるとは考えないでください。'])
add('Candle-Timer-and-Spread-Indicator','Candle Timer & Spread','Indicator','Sessions',None,
['Keep the next candle time and current spread visible while monitoring a chart.', 'The indicator provides basic, detailed and symbol-information views. It can show the remaining candle time, elapsed time or spread and issue a countdown alert.', 'Choose the panel view and alert lead time. Check the display against the terminal clock and the symbol’s quoted spread during both active and quiet periods.', 'A countdown does not forecast the next price move. A stale feed or closed market can make timing and spread displays less informative; verify the source of current quotes.'],
['次の足への残り時間とスプレッドを、チャート監視中に確認しやすくする表示ツールです。','基本・詳細・銘柄情報の表示を選べ、残り時間や経過時間、スプレッドを確認できます。残り時間に応じた通知も設定できます。','表示形式と通知のタイミングを選び、活発な時間と静かな時間の両方で端末時計・提示スプレッドと照合します。','カウントダウンは次の値動きの予測ではありません。配信停止や休場時には表示の意味が変わるため、最新価格が届いているかも確認します。'])
add('Pinbar-Detector','Pinbar Detector','Indicator','Price action','indicators/Pinbar-Detector/',
['Find candles that match a chosen pinbar definition for manual review.', 'The indicator marks bullish and bearish pinbar candidates on the chart. Its shape criteria are configurable and alerts are available.', 'Choose body/wick criteria from the current input descriptions, then compare a small set of marked and unmarked candles by hand. Review the signal in its surrounding price context.', 'A pinbar shape alone does not establish a reversal or a tradable advantage. Changing the definition changes the sample; confirm signal timing before using historical markers in a test.'],
['自分で定めたピンバー条件に合う足を抽出し、目視確認しやすくするインジケーターです。','上昇側・下降側のピンバー候補をチャートへ表示します。形状の条件を調整でき、通知にも対応します。','現行入力の説明から実体・ヒゲの条件を選び、表示された足と表示されなかった足を少数ずつ手で照合します。前後の価格構造も合わせて確認します。','ピンバーの形だけで反転や優位性が確認されたことにはなりません。条件を変えると標本も変わります。過去の印を検証に使う前に表示タイミングを確認します。'])
add('WRB-Hidden-Gap','WRB Hidden Gap','Indicator','Price action',None,
['Identify wide-range bars and the associated hidden-gap zones for price-action study.', 'The author-maintained MT4/MT5 implementation follows the WRB/HG framework described upstream and supports alerts. Upstream credits Akif Tokuz and the WRB work of M. A. Perry.', 'Read the author’s definition before selecting the detection settings. Compare identified zones to their original candles and examine how zones change when price revisits them.', 'These zones are not a promise that a gap must fill. This entry links upstream rather than redistributing the derivative code or the underlying tutorial.'],
['大きな値幅の足と、それに関連する隠れたギャップ領域を値動きの研究に使う指標です。','作者が説明するWRB・HGの定義を使うMT4・MT5実装で、通知にも対応します。原配布元にはAkif Tokuz氏とM. A. Perry氏のWRB研究への言及があります。','先に作者の検出定義を読み、設定を選びます。表示領域を元の足と比較し、価格が戻ったときに領域がどう更新されるかを確認します。','領域が必ず埋まることを意味しません。この項目は原配布元への案内で、派生ソースや元の教材の転載は行っていません。'],credit='Upstream credits Akif Tokuz and M. A. Perry / TheStrategyLab WRB methodology.')
add('Support-and-Resistance','Support & Resistance','Indicator','Levels','indicators/Support-and-Resistance/',
['Display fractal-based horizontal levels instead of drawing each swing reference manually.', 'This MT4/MT5 indicator uses standard Fractals to draw support and resistance. It alerts when price closes beyond a corresponding level; upstream credits an earlier version by Barry Stander.', 'Compare marked levels against confirmed fractals. Distinguish a wick crossing from the author’s close-based alert condition, and check when each level first became available.', 'A level plotted at an earlier swing was not necessarily known then. This is an author-hosted source listing, not a BSV audit of every inherited component.'],
['フラクタルに基づく水平線を表示し、スイング水準の手描きを補助する指標です。','標準フラクタルから支持・抵抗を描き、価格が線の外側で引けた場合に通知します。原配布元はBarry Stander氏の旧版への由来を明記しています。','確定したフラクタルと線を照合します。ヒゲでの通過と、この指標の終値ベース通知を分け、線がいつ認識可能になったかも確認します。','過去のスイング位置に線があっても、その時点で認識できたとは限りません。これは原配布元への案内で、継承部分全体をBSVが監査した表示ではありません。'],credit='Upstream credits an earlier version by Barry Stander.')
add('Supertrend-Multi-Timeframe','Supertrend Multi-Timeframe','Indicator','Trend','indicators/supertrend-multi-timeframe/',
['Compare Supertrend states across timeframes while retaining a line on the current chart.', 'The implementation combines a multi-timeframe panel with the current timeframe’s Supertrend line and provides terminal, mobile and email alerts.', 'Choose the timeframes and line settings. Check a higher timeframe while its bar is open and again after it closes; verify alert delivery separately from the displayed panel.', 'Higher-timeframe values can change before their bars finish. Agreement across correlated timeframes is not independent confirmation or a tested entry strategy.'],
['現在足の線を見ながら、複数時間足のスーパートレンド状態を比較する指標です。','複数時間足のパネルと現在足のスーパートレンド線を組み合わせ、端末・スマホ・メール通知に対応します。','時間足と線の設定を選び、上位足が未確定の間と確定後を比較します。表示の確認と通知が届くかの確認は分けて行います。','上位足は確定まで値が変化します。相関した時間足の一致を、独立した証拠や検証済みの売買条件とは扱えません。'])
add('QQE','QQE','Indicator','Momentum','indicators/QQE/',
['Study smoothed momentum and neutral-level transitions using Quantitative Qualitative Estimation.', 'The author’s multi-timeframe implementation combines RSI, moving-average and ATR calculations and includes signals around the neutral level of 50.', 'Review smoothing, timeframe, arrow and alert inputs. Compare signals with the oscillator and verify which bar is used when a higher timeframe is selected.', 'Smoothing adds delay, and higher-timeframe updates can change during an open bar. The upstream project credits earlier versions by Roman Ignatov and Tim Hyder; this listing does not mirror their code.'],
['QQEで平滑化された勢いと、中立水準をまたぐ変化を研究する指標です。','作者の複数時間足版はRSI・移動平均・ATRの計算を組み合わせ、中立の50付近の変化を表示します。','平滑化、時間足、矢印、通知の設定を確認し、サインをオシレーターと照合します。上位足を選ぶ際はどの足の値を使うかも確認します。','平滑化には遅れがあり、上位足の値は未確定の間に変わります。原配布元が記すRoman Ignatov氏・Tim Hyder氏の旧版を含め、ここでソース転載は行っていません。'],credit='Upstream credits early versions by Roman Ignatov and Tim Hyder.')
add('Traders-Dynamic-Index','Traders Dynamic Index','Indicator','Momentum','indicators/Traders-Dynamic-Index/',
['View several aspects of momentum in one oscillator rather than treating every line as an independent signal.', 'TDI uses RSI and moving-average calculations, supports alerts and chart arrows, and can show a higher timeframe on a lower-timeframe chart. Upstream credits Dean Malone’s earlier version.', 'Read what each line represents, choose one signal condition to test, and confirm higher-timeframe timing. Keep a record of the exact settings used.', 'Multiple lines built from related inputs do not create multiple independent confirmations. This is an upstream source directory entry, with no copied author chart or claimed return.'],
['複数のモメンタムの見方を、一つのオシレーターで比較する指標です。','RSIと移動平均の計算を使い、通知・チャート矢印・上位足表示に対応します。原配布元はDean Malone氏の旧版を基にしたことを明記しています。','各線の意味を読んで、一つのサイン条件から検証します。上位足の表示タイミングと使用設定を記録します。','関連した入力から作る複数の線は、独立した複数の証拠ではありません。原配布元への案内であり、作者のチャート転載や利益実績の主張は付けていません。'],credit='Upstream credits Dean Malone.')
add('Donchian-Ultimate','Donchian Ultimate','Indicator','Breakout','indicators/Donchian-Ultimate/',
['Inspect rolling high/low boundaries for breakout and range studies.', 'The author provides a configurable Donchian-channel implementation with alerts and higher-timeframe display for MT4 and MT5.', 'Choose the lookback and timeframe, then verify whether the current candle participates in each boundary. Compare alerts to the exact channel available at that moment.', 'A boundary can move when the lookback window advances. Including the current bar changes the interpretation of a touch or breakout; do not infer strategy results from the channel alone.'],
['一定期間の高値・安値の境界を使い、ブレイクやレンジを研究する指標です。','調整機能を備えたドンチアンチャネルで、MT4・MT5の通知と上位足表示に対応します。','参照期間と時間足を選び、境界の計算に現在足が入るかを確認します。通知は、その時点で利用できたチャネルと照合します。','参照範囲が進むと境界が動きます。現在足を含むかによって接触・突破の意味も変わるため、線だけから戦略の成績を判断できません。'])
add('Bollinger-Squeeze-Advanced','Bollinger Squeeze Advanced','Indicator','Volatility','indicators/Bollinger-Squeeze-Advanced/',
['Separate volatility compression from the accompanying momentum direction.', 'The indicator compares Bollinger Bands and Keltner Channel relationships and offers eight oscillator choices for its histogram. Alerts cover relationship changes and zero-line crosses.', 'Choose the oscillator and band/channel inputs deliberately. Inspect squeeze transitions separately from directional signals and record both before testing a combined rule.', 'Compression does not guarantee the direction or size of a subsequent move. Upstream credits Nick Bilak’s earlier MT4 version; BSV links the maintained project without mirroring its code.'],
['値幅の収縮と、そのときの勢いの方向を分けて確認する指標です。','ボリンジャーバンドとケルトナーチャネルの関係を見ながら、8種類から選ぶオシレーターをヒストグラムに使います。関係変化とゼロ交差を通知します。','オシレーターとバンド・チャネルの設定を選び、収縮の切り替わりと方向サインを別々に記録してから組み合わせを検証します。','収縮しても次の値動きの方向・大きさは保証されません。原配布元はNick Bilak氏の旧版を記しています。BSVは保守元へ案内し、コードを転載していません。'],credit='Upstream credits Nick Bilak.')
add('Moving-Average-Crossover-Alert','MA Crossover Alert','Indicator','Trend','indicators/moving-average-crossover-alert/',
['Receive a visual or notification prompt when two moving averages cross.', 'The indicator displays the moving-average lines and marks crossing points with arrows on the main chart. It supports the terminal’s alert mechanisms.', 'Set the two averages and alert options. Compare an intrabar cross, a reversed cross and the final bar state on demo; test notification delivery independently.', 'The author calls it non-repainting, but BSV has not verified that claim in runtime. Crossovers in a sideways market can occur repeatedly and are not a complete strategy.'],
['2本の移動平均線の交差を、矢印や通知で監視するインジケーターです。','メインチャートに移動平均線と交差位置の矢印を描き、通知機能を利用できます。','2本の平均線と通知条件を設定し、デモで足の途中の交差・交差の取消・足の確定後を比べます。通知の到達も別に試します。','作者は非リペイントと説明していますが、BSVでは実行検証していません。持ち合いでは交差が繰り返され、これだけでは完結した戦略になりません。'])
add('RSI-with-Alert','RSI with Alert','Indicator','Momentum','indicators/rsi-alert/',
['Monitor RSI boundary exits, returns or crossings of a manually drawn horizontal level.', 'RSI is displayed in a separate pane while signal arrows can appear on the price chart. Alert and threshold behavior is configurable.', 'Choose whether an alert concerns leaving a zone or returning to it. Match the observed arrow and notification to that chosen event rather than just the RSI value.', 'Leaving an extreme zone and entering it are different conditions. The upstream non-repainting description is not a BSV runtime certification, and extreme RSI can persist.'],
['RSIが境界の外へ出る、内側へ戻る、任意の水平線をまたぐ動きを監視する指標です。','RSIは別窓に表示し、価格チャートへサイン矢印を描けます。しきい値と通知の条件を設定できます。','ゾーンから外へ出る条件なのか、内側へ戻る条件なのかを先に選びます。RSIの数値だけでなく、選んだ変化と矢印・通知を照合します。','極端なゾーンへの進入と退出は別の条件です。作者の非リペイント表記はBSVの実行認証ではありません。RSIが極端なまま推移する場合もあります。'])
add('Currency-Strength-Lines','Currency Strength Lines','Indicator','Momentum','indicators/currency-strength-lines/',
['Compare the relative behavior of major currencies instead of looking at one pair in isolation.', 'A separate-window indicator derives strength for up to eight currencies from their pairs. It includes basic higher-timeframe display and alerts.', 'Check available symbol names and data histories in your terminal, select currencies and timeframe, and compare the output with the underlying pairs.', 'Missing or differently named broker symbols can affect the calculation. Relative strength is an indicator construction, not an official index or a forecast of the next tick.'],
['一つの通貨ペアだけでなく、主要通貨同士の相対的な動きを比較する指標です。','通貨ペアから最大8通貨の強さを計算して別窓に表示します。基本的な上位足表示と通知にも対応します。','端末の銘柄名と価格履歴を確認し、通貨と時間足を選びます。表示された強弱を、計算元の通貨ペアの動きと照合します。','業者による銘柄名の違いやデータ欠損が計算へ影響する場合があります。公式指数や次のティックを予測するものではありません。'])
add('RoundLevels','Round Levels','Indicator','Levels','indicators/Round-Levels/',
['Place a consistent round-number grid on your chart to help organize manual price observations.', 'The indicator draws configurable lines or zones at and between round price levels. Distance, colors and styles can be changed.', 'Set the interval to the instrument’s quoted price scale, then compare a few generated levels by hand. Check whether zones or exact lines better match your intended study.', 'Round numbers are annotations, not verified liquidity data. An interval that fits a currency pair may be inappropriate for gold, an index or a different quote precision.'],
['ラウンドナンバーの線や帯を整然と表示し、裁量で価格を見る際の基準を作る指標です。','一定間隔の価格やその間に線・ゾーンを配置します。間隔、色、線の見た目を変更できます。','銘柄の価格スケールに合う間隔を設定し、表示水準を少数手で照合します。研究目的に応じて線と帯を使い分けます。','ラウンドナンバーは確認済みの流動性データではありません。通貨ペアで使う間隔が、ゴールド・指数・異なる価格桁にも適切とは限りません。'],branch='master')
add('Candle-Wicks-Length-Display','Candle Wicks Length Display','Indicator','Price action',None,
['Make candle-shadow measurements visible without repeatedly using a ruler.', 'The indicator displays wick lengths according to user settings and can highlight or alert on unusually long shadows.', 'Choose the measurement units and display threshold, then manually verify several upper and lower wicks against the instrument’s point value.', 'A long wick measures a price excursion, not proof of a stop hunt or a reversal. Feed differences and quote precision affect the measured length.'],
['ヒゲの長さを毎回計測せず、チャート上で見比べやすくする指標です。','設定に応じてヒゲの長さを表示し、異常に長いヒゲの監視にも使えます。','長さの単位と表示しきい値を選び、上ヒゲ・下ヒゲを数本ずつ銘柄のポイント価値と手作業で照合します。','長いヒゲは値幅の記録であり、ストップ狩りや反転を証明するものではありません。配信元や価格の桁によって計測値も変わり得ます。'])
add('Close-All-Orders','Close All Orders / Positions','Script','Trade management','metatrader-scripts/close-all-orders/',
['Close a defined set of trades in one operation rather than handling each position manually.', 'The script closes MT4 trades or MT5 positions according to configurable filtering and ordering preferences.', 'Install in the correct Scripts folder. Before any use, inspect every filter on demo, including a trade that should remain untouched. Review the broker’s actual close results afterward.', 'Running the script can immediately submit closing orders. A partial failure can leave some trades open; a matching filter is more important than the product’s “all” label.'],
['複数の取引を一つずつ手で閉じる代わりに、対象を決めて一括決済するスクリプトです。','設定した絞り込みと順序に応じて、MT4の取引またはMT5のポジションを閉じます。','対応するScriptsフォルダーへ導入し、デモで全フィルターを確認します。閉じない対象も含めて試し、実行後に業者の決済結果を照合します。','実行すると直ちに決済注文が送られる場合があります。一部の拒否で建玉が残ることもあるため、名前の「All」だけで対象や完了を判断しないでください。'])
add('RiskCalculator','Risk Calculator','Indicator','Risk tools','indicators/Risk-Calculator/',
['Review combined potential risk and reward across open positions and pending orders.', 'The indicator calculates an aggregate view and presents it in a separate chart window, with settings to adapt the calculation to the trader’s needs.', 'Check which trades and pending orders are included, then compare a small demo portfolio with independent manual calculations. Review missing-stop cases explicitly.', 'This is a calculation aid, not an automatic account-protection function. Slippage, gaps and different order activation paths can make realized loss differ from a simplified aggregate.'],
['保有ポジションと待機注文をまとめて、想定リスクと利益を確認する指標です。','複数取引の計算結果を別窓へ表示し、用途に合わせて設定を調整できます。','どの建玉・待機注文が対象になるか確認し、少数のデモ取引で手計算と照合します。損切り未設定の取引をどう扱うかも確認します。','自動で口座を保護する機能ではなく計算補助です。滑り、窓、待機注文が有効になる順序などにより、単純な合計と実損失は変わります。'],branch='master')
add('Box-Breakout-Alert','Box Breakout Alert','Indicator','Breakout','indicators/box-breakout-alert/',
['Monitor a breakout beyond the high/low range of a chosen number of previous candles.', 'The indicator compares current price with a prior-candle range directly, marks a detected breakout with an arrow and supports alerts.', 'Choose the lookback and alert settings. Verify that the box corresponds to the intended prior candles, then compare first touch, actual break and return into the box.', 'An arrow does not imply follow-through. The source is an alerting indicator, not an EA that places orders or a backtested breakout strategy.'],
['指定本数の過去足が作る高値・安値の範囲から、現在価格が外へ出る動きを監視します。','既存指標を使うのではなく、価格と過去足レンジを直接比較し、突破を矢印・通知で知らせます。','参照本数と通知条件を選び、範囲が意図した過去足と一致するかを確認します。最初の接触、突破、範囲内への戻りを分けて見ます。','矢印が出てもその後の継続は保証されません。これは通知用インジケーターであり、発注EAやバックテスト済み戦略ではありません。'])
add('Breakeven-Line','Breakeven Line','Indicator','Risk tools','indicators/Breakeven-Line/',
['See the combined break-even reference for multiple trades on the same symbol.', 'The indicator displays a cumulative break-even price together with distance, total profit/loss, volume and trade count.', 'Compare a simple demo position set with a manual weighted calculation. Verify how the author’s current version handles costs and mixed long/short exposure.', 'A displayed line is not an instruction to hold until recovery. Equal opposite exposures and cost assumptions require careful interpretation; this indicator does not move stops.'],
['同じ銘柄で複数の建玉を持つ際に、合算した建値の目安を確認する指標です。','合算の建値とそこまでの距離、損益、総ロット、取引数などを表示します。','単純なデモ建玉で加重計算と比較し、手数料・スワップ・買い売り混在時を現行版がどう扱うか確認します。','建値まで待つべきという売買指示ではありません。同量の両建てやコストの扱いには注意が必要です。ストップを移動するEAではありません。'])
add('MT5-Expert-Advisor-Template','MT5 Expert Advisor Template','Template','Research','metatrader-expert-advisors/mt5-ea-template/',
['Build an MT5 EA around your own explicit entry and exit rules.', 'The template provides a structure for adding signals, plus position sizing, ATR-based stop and target calculations and basic error handling.', 'Preserve the Experts, Include and Files folder relationships from the author package. Add one minimal signal rule, compile in MetaEditor and test the trade lifecycle on demo.', 'This is a development starting point, not a finished strategy. Template error handling does not prove safety; validate symbol specifications, failure paths and position ownership in the final code.'],
['自分のエントリー・決済条件を入れて、MT5用EAを開発するためのひな形です。','売買条件を追加する構造のほか、ロット計算、ATRに基づくストップ・利益目標、基本的なエラー処理が用意されています。','作者パッケージのExperts・Include・Filesの関係を保って配置します。まず最小の売買条件を入れ、MetaEditorでコンパイルし、デモで取引の一連の動作を検証します。','完成した戦略ではありません。基本エラー処理があるだけで安全性は確認できません。銘柄仕様、失敗時処理、どの建玉を管理するかを完成コードで検証します。'],platforms=['MT5'],research=True)
assert len(D)==40,len(D)
(B/'author_catalog.json').write_text(json.dumps(D,ensure_ascii=False,indent=2))
print('Created',len(D),'author source directory entries. No code mirrored for these entries.')
